---
sidebar: sidebar 
permalink: oracle/host-configuration/aix.html 
keywords: oracle, database, ontap, aix, cio 
summary: 使用 AIX 的 ONTAP 上的 Oracle 
---
= IBM AIX
:allow-uri-read: 


[role="lead"]
特定於 IBM AIX 作業系統的組態主題。



== 並行 I/O

若要在 IBM AIX 上達到最佳效能、必須同時使用 I/O如果沒有並行 I/O 、效能限制很可能是因為 AIX 執行序列化的原子 I/O 、這會產生重大的負荷。

NetApp 最初建議使用 `cio` 掛載選項可強制在檔案系統上使用並行 I/O 、但此程序有缺點、不再需要。自從推出 AIX 5.2 和 Oracle 10gR1 之後、 AIX 上的 Oracle 就可以開啟個別檔案來同時執行 IO 、而不是強制在整個檔案系統上同時執行 I/O 。

啟用並行 I/O 的最佳方法是設定 `init.ora` 參數 `filesystemio_options` 至 `setall`。這樣做可讓 Oracle 開啟特定檔案、以與並行 I/O 搭配使用

使用 `cio` 作爲掛載選項，強制使用並行 I/O ，這可能會產生負面影響。例如、強制並行 I/O 會停用檔案系統上的預先讀取、這可能會損害 Oracle 資料庫軟體以外的 I/O 效能、例如複製檔案和執行磁帶備份。此外、 Oracle GoldenGate 和 SAP BR* Tools 等產品與使用不相容 `cio` 裝載選項搭配特定版本的 Oracle 。

[TIP]
====
* NetApp 建議 * 下列事項：

* 請勿使用 `cio` 檔案系統層級的掛載選項。而是透過使用來啟用並行 I/O `filesystemio_options=setall`。
* 請僅使用 `cio` 如果無法設定掛載選項、則應選擇掛載選項 `filesystemio_options=setall`。


====


== AIX NFS 裝載選項

下表列出 Oracle 單一執行個體資料庫的 AIX NFS 掛載選項。

|===
| 檔案類型 | 掛載選項 


| ADR 首頁 | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144` 


| 控制檔
資料檔案
重作記錄 | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144` 


| `ORACLE_HOME` | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144,
intr` 
|===
下表列出 RAC 的 AIX NFS 掛載選項。

|===
| 檔案類型 | 掛載選項 


| ADR 首頁 | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144` 


| 控制檔
資料檔案
重作記錄 | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144,
nointr,noac` 


| `CRS/Voting` | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144,
nointr,noac` 


| 專屬 `ORACLE_HOME` | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144` 


| 共享 `ORACLE_HOME` | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144,
nointr` 
|===
單一執行個體與 RAC 掛載選項之間的主要差異在於新增 `noac` 至掛載選項。此新增功能可停用主機作業系統快取、使 RAC 叢集中的所有執行個體都能一致地檢視資料狀態。

雖然使用 `cio` 裝載選項和 `init.ora` 參數 `filesystemio_options=setall` 停用主機快取的效果相同、仍需使用 `noac`。 `noac` 為共享的必要項目 `ORACLE_HOME` 部署以促進 Oracle 密碼檔案和等檔案的一致性 `spfile` 參數檔。如果 RAC 叢集中的每個執行個體都有專用的 `ORACLE_HOME`，則不需要此參數。



== AIX jfs/JFS2 掛載選項

下表列出 AIX jfs/JFS2 掛載選項。

|===
| 檔案類型 | 掛載選項 


| ADR 首頁 | 預設值 


| 控制檔
資料檔案
重作記錄 | 預設值 


| Oracle_Home | 預設值 
|===
使用 AIX 之前 `hdisk` 任何環境中的裝置（包括資料庫）都請檢查參數 `queue_depth`。此參數不是 HBA 佇列深度、而是與個別主機的 SCSI 佇列深度相關 `hdisk device. Depending on how the LUNs are configured, the value for `queue_depth` 效能可能太低。測試顯示最佳值為 64 。
