---
sidebar: sidebar 
permalink: oracle/oracle-asar2-config-failover.html 
keywords: failover, takeover, ASA r2, oracle 
summary: 要確保 Oracle 資料庫操作不會因這些操作而中斷，就需要了解儲存接管功能。此外，收購操作中使用的參數如果使用不當，可能會影響資料完整性。 
searchtitle: ASA r2 中的 Oracle 資料庫和ONTAP控制器故障轉移 
---
= ONTAP故障轉移
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
要確保 Oracle 資料庫操作在這些操作期間不會中斷，就需要了解儲存接管功能。此外，收購操作中使用的論點如果使用不當，可能會影響資料完整性。

正常情況下，寫入給定控制器的傳入資料會同步鏡像到其高可用性夥伴。在具有SnapMirror Active Sync (SM-as) 的ASA r2 環境中，寫入作業也會鏡像到輔助站台的遠端控制器。只有當寫入操作在所有位置都儲存在非揮發性媒體中時，主機應用程式才能收到確認。

儲存寫入資料的媒體稱為非揮發性記憶體（NVMEM）。它有時被稱為非揮發性隨機存取記憶體（NVRAM），可以將其視為寫入日誌而不是快取。正常運作期間，不會讀取NVMEM中的資料；它僅用於在軟體或硬體發生故障時保護資料。當資料寫入驅動器時，資料是從系統 RAM 傳輸的，而不是從NVMEM傳輸的。

在接手操作期間，HA 對中的一個節點從其夥伴節點接手操作。在ASA r2 中，由於不支援MetroCluster ，因此無法進行切換；取而代之的是， SnapMirror Active Sync 提供網站層級冗餘。例行維護期間的儲存接管操作應該是透明的，除了網路路徑改變時操作會短暫暫停之外。網路可能很複雜，而且很容易出錯，因此NetApp強烈建議在將儲存系統投入生產之前徹底測試接管操作。這樣做是確保所有網路路徑都正確配置的唯一方法。在 SAN 環境中，使用下列命令驗證路徑狀態 `sanlun lun show -p` 或使用作業系統自帶的多路徑工具，以確保所有預期路徑都可用。ASA r2 系統為 LUN 提供所有活動的最佳化路徑，使用 NVMe 命名空間的客戶應依賴作業系統原生工具，因為 sanlun 不涵蓋 NVMe 路徑。

強制收購時必須謹慎行事。強制更改儲存配置意味著忽略擁有驅動器的控制器的狀態，備用節點強制接管驅動器的控制權。強制接管操作不當可能導致資料遺失或損壞，因為強制接管操作可能會丟棄NVMEM的內容。接管完成後，資料遺失意味著從資料庫的角度來看，儲存在磁碟機上的資料可能會恢復到稍舊的狀態。

使用普通HA對進行強制接管的情況應該很少發生。在幾乎所有故障情況下，節點都會關閉並通知合作夥伴，以便進行自動故障轉移。有些極端情況，例如滾動故障，其中節點之間的互連丟失，然後一個控制器發生故障，在這種情況下需要強制接管。在這種情況下，節點之間的鏡像會在控制器發生故障之前遺失，這意味著倖存的控制器不再擁有正在進行的寫入操作的副本。收購必須強制執行，這意味著資料可能會遺失。

[TIP]
====
NetApp建議採取以下預防措施：

* 務必小心，不要意外地促成收購。通常情況下，不應該強制執行更改，強制更改可能會導致資料遺失。
* 如果需要強制接管，請確保應用程式已關閉，所有檔案系統已卸載，並且邏輯磁碟區管理器 (LVM) 磁碟區組已關閉。必須卸載 ASM 磁碟組。
* 在使用 SM-as 時，如果發生站點級故障， ONTAP Mediator 輔助的自動非計劃故障轉移將在倖存叢集上啟動，這將導致短暫的 I/O 暫停，然後資料庫轉換將從倖存叢集繼續進行。更多資訊請參見 https://docs.netapp.com/us-en/asa-r2/data-protection/configure-snapmirror-active-sync.html["ASA r2 系統上的SnapMirror主動同步"] 詳細配置步驟請見下文。


====