---
sidebar: sidebar 
permalink: oracle/oracle-virtualization-introduction.html 
keywords: oracle, database, ontap, virtualization, esx, hyper-v, KVM 
summary: 資料庫虛擬化簡介 
---
= 虛擬化
:allow-uri-read: 


[role="lead"]
使用 VMware ESX 、 Oracle OVM 或 KVM 來虛擬化資料庫、對於選擇虛擬化技術的 NetApp 客戶而言、這是越來越常見的選擇、即使是他們最關鍵的關鍵任務資料庫也一樣。

對於虛擬化的支援政策、特別是對於 VMware 產品、存在許多誤解。事實上、 Oracle 並不以任何方式支援虛擬化、這種說法並不罕見。這個概念不正確、導致錯失虛擬化的商機。Oracle Doc ID 249212.1 討論 Oracle 環境中的已知問題、並指定支援 RAC 。

Oracle 未知問題的客戶可能會被要求在實體硬體上重現問題。執行產品最新版本的 Oracle 客戶可能不想使用虛擬化、因為可能會發現新的錯誤。然而、對於使用一般可用產品版本的虛擬化客戶而言、這種情況並不是問題。



== 儲存簡報

考慮將資料庫虛擬化的客戶應根據其業務需求做出儲存決策。雖然這是所有 IT 決策的正確陳述、但對於虛擬化來說、這點尤其重要、因為專案的規模和範圍差異很大。

儲存簡報有四個基本選項：

* iSCSI LUN 由虛擬機器上的 iSCSI 啟動器管理、而非 Hypervisor
* 由 VM 掛載的 NFS 檔案系統、而非虛擬機器磁碟（ VMDK ）
* Hypervisor 資料存放區


一般而言、請避免將資料存放區用於 Oracle 檔案。這項建議有許多理由：

* * 透明度。 * VM 擁有其檔案系統時、資料庫管理員或系統管理員更容易識別其資料的檔案系統來源。
* * 效能。 * 測試顯示、透過 Hypervisor 資料存放區傳輸所有 I/O 會產生效能影響。
* * 管理能力。 * VM 擁有其檔案系統時、使用或不使用 Hypervisor 層會影響管理能力。資源配置、監控、資料保護等程序也可在整個資產中使用、包括虛擬化和非虛擬化環境。
* * 穩定性與疑難排解。 * VM 擁有其檔案系統時、由於整個儲存堆疊都存在於 VM 上、因此提供良好、穩定的效能與疑難排解問題會變得更簡單。Hypervisor 唯一的角色是傳輸 FC 或 IP 框架。當資料存放區包含在組態中時、它會引入另一組逾時、參數、記錄檔和潛在錯誤、使組態複雜化。
* * 可攜性。 * VM 擁有其檔案系統時、移動 Oracle 環境的程序會變得更簡單。檔案系統可在虛擬化與非虛擬化的來賓作業系統之間輕鬆移動。
* * 廠商鎖定 * 將資料放入資料存放區後、使用不同的 Hypervisor 或將資料從虛擬化環境中移出、將變得非常困難。
* * Snapshot 功能。 * 在某些情況下、虛擬化環境中的備份可能會因為頻寬相對有限而成為問題。例如、四埠 10GbE 主幹可能足以支援許多虛擬化資料庫的日常效能需求。不過、這類主幹不足以使用 RMAN 或其他需要串流完整資料複本的備份產品來執行備份。
+
使用 VM 擁有的檔案系統、可讓您更輕鬆地利用 Snapshot 型備份與還原。VM 擁有的檔案系統會將執行備份的工作卸載到儲存系統。完全不需要為了支援備份期間的頻寬和 CPU 需求而過度建置 Hypervisor 組態。




TIP: * NetApp 建議 * 避免將 Oracle 資料放置在資料存放區上、以達到最佳效能與管理能力。使用來賓擁有的檔案系統、例如由來賓管理的 NFS 或 iSCSI 檔案系統、或是搭配 RDM 使用。



== 半虛擬化驅動程式

為了達到最佳效能、使用半虛擬化網路驅動程式至關重要。使用資料存放區時、需要半虛擬化 SCSI 驅動程式。半虛擬化的裝置驅動程式可讓來賓更深入地整合至 Hypervisor 、而非模擬的驅動程式、在該驅動程式中、 Hypervisor 會花費更多的 CPU 時間來模擬實體硬體的行為。

大多數資料庫的效能受限於儲存設備。因此、網路或 SCSI 驅動程式所帶來的額外延遲特別明顯。NetApp 客戶支援部門遇到許多效能問題、這些問題都是透過安裝半虛擬化驅動程式來解決的。在一次客戶概念驗證期間、資料庫在 ESX 下的效能表現優於與裸機相同的硬體。測試的 I/O 密集度極高、效能差異則是因為使用 ESX 半虛擬化網路驅動程式所致。


TIP: * NetApp 建議 * 永遠使用半虛擬化網路驅動程式和 SCSI 驅動程式。



== 過度使用 RAM

過度使用 RAM 意味著在不同主機上設定的虛擬化 RAM 多於實體硬體上的虛擬化 RAM 。否則可能會造成非預期的效能問題。虛擬化資料庫時、 Oracle SGA 的基礎區塊不得由 Hypervisor 交換至儲存設備。這樣做會導致效能結果極不穩定。


TIP: * NetApp 建議 * 不要以允許換出 Oracle SGA 區塊的方式來設定 Hypervisor 。
