---
sidebar: sidebar 
permalink: oracle/oracle-dp-planning.html 
keywords: data protection, DR, snapshots, CG 
summary: Oracle 資料庫的資料保護規劃 
searchtitle: Oracle 資料庫的資料保護規劃 
---
= 資料保護規劃
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
正確的 Oracle 資料庫資料保護架構取決於資料保留、可恢復性、以及各種事件中斷的容錯能力等業務需求。

例如、請考慮範圍內的應用程式、資料庫和重要資料集數量。為單一資料集建立備份策略、以確保符合典型 SLA 的要求相當簡單、因為沒有太多物件需要管理。隨著資料集數量增加、監控作業變得更複雜、系統管理員可能不得不花費更多時間來解決備份故障。當環境達到雲端與服務供應商的規模時、需要完全不同的方法。

資料集大小也會影響策略。例如、由於資料集太小、因此有許多選項可用於 100GB 資料庫的備份與還原。只要使用傳統工具從備份媒體複製資料、通常就能提供足夠的恢復 RTO 。100TB 資料庫通常需要完全不同的策略、除非 RTO 允許多天中斷、否則傳統的複製備份與還原程序可能是可以接受的。

最後、除了備份與還原程序本身之外、還有其他因素。例如、是否有支援關鍵生產活動的資料庫、使恢復成為僅由熟練的 DBA 執行的罕見事件？或者、資料庫是否是大型開發環境的一部分、而在大型開發環境中、恢復是經常發生的事、並由一群通才的 IT 團隊負責管理？



== 快照是否為備份？

人們普遍反對使用快照做為資料保護策略、因為「真實」資料和快照資料位於同一個磁碟機上。遺失這些磁碟機將會導致主要資料和備份遺失。

這是一項有效的考量。本機快照是用於日常備份與還原需求、在這方面、快照是備份。在 NetApp 環境中、將近 99% 的還原案例都仰賴快照來滿足最嚴苛的 RTO 需求。

然而、本機快照不應是唯一的備份策略、因此 NetApp 提供 SnapMirror 複寫等技術、可快速有效地將快照複寫至一組不同的磁碟機。在架構正確的解決方案中、快照加上快照複寫功能可將磁帶的使用降至最低、甚至是每季歸檔、或完全消除。



== 損毀一致的備份

當機一致性備份涉及在單一原子時間點擷取資料集（或多個資料集）的狀態。以資料庫為例、這包括所有資料庫元件、例如資料檔案、記錄檔及其他與資料庫直接相關的檔案。這適用於幾乎所有關聯式資料庫產品、包括 Oracle RDBMS、Microsoft SQL Server、SAP HANA、PostgreSQL、MySQL 和 MariaDB。使用一致性群組備份來保護 VMware 組態也類似、在單一原子時間點擷取所有資料存放區、以及可能的 ESX 開機 LUN。

建立這類備份本質上是在模擬當機，因此這類備份稱為當機一致性備份。有時會擔心其對還原案例的支援，但重要的是要瞭解，通常不需要任何還原程序。應用程式在還原一致性群組備份後啟動時，會執行一般的記錄還原程序、檔案系統日誌重播以及其他工作，以重播備份時正在進行的任何 I/O 作業。然後，應用程式會照常啟動。

基本上、任何能夠承受停電或伺服器當機而不毀損資料的應用程式、都能以這種方式受到保護。許多不同廠商的同步與非同步鏡射產品、可保護大量應用程式、也能證明這項工作的成效。如果災難突然發生在主要站台、則複本站台會在發生災難時、包含原始環境的一致映像。再一次、不需要特殊的恢復程序。

這種方法的 RPO 通常僅限於備份點。一般來說，當機一致性備份的最低 RPO 為一小時。例如、 48 個每小時快照加上另外 30 天的夜間快照是合理的、而且不需要保留過多的快照。低於一小時的 RPO 更難實現、因此不建議在未諮詢 NetApp 專業服務部門以瞭解環境、規模和資料保護要求之前這樣做。

RTO 通常以秒為單位進行測量。當應用程式關閉時、NFS 磁碟區、LUN 或 NVMe 命名空間將被還原、然後應用程式將重新啟動。

最簡單的方法是將所有檔案或 LUN 放在單一 AFF 磁碟區或 ASA LUN/命名空間。如果資料集必須跨越多個儲存資源，則需要一致性群組。這可以透過 System Manager 或 RESTful API 呼叫進行配置，並且 SnapCenter 能夠建立簡單的一致性群組快照。



== 複寫與災難恢復架構

本節說明遠端資料保護、將資料複寫到遠端站台、以保護異地儲存和災難恢復的安全。請注意、這些表格並未解決同步鏡射資料保護問題。如需此需求、請參閱 NetApp MetroCluster 文件、包括link:oracle-dr-mcc-failover.html["MetroCluster"]和link:oracle-dr-smas-overview.html["SnapMirror 主動同步"]

災難恢復 RPO 受限於可用的網路頻寬和受保護資料的總大小。建立初始基準傳輸之後、更新僅以變更的資料為基礎、這通常是資料佔用空間總量的低百分比、但確實存在例外情況。

例如、每週變更率為 10% 的 10TB 資料庫、在總變更中、平均每小時約為 6GB 。10 Gb 的連線能力、此資料庫需要大約六分鐘的時間才能傳輸。變更率會因資料庫變更率的波動而異、但整體而言、 15 分鐘的更新間隔、因此應可達成 15 分鐘的 RPO 。如果有 100 個這樣的資料庫、則需要 600 分鐘才能傳輸資料。因此、一小時的 RPO 是不可能的。同樣地、單一資料庫的複本、每週變更率為 10% 、大小為 100TB 、無法在一小時內可靠地更新。

其他因素也會影響複寫，例如複寫開銷和並行複寫作業數量的限制。然而，單一資源複寫策略的整體規劃可以基於可用頻寬，通常可以實現一小時的複寫 RPO。低於一小時的 RPO 更難實現，應僅在諮詢 NetApp Professional Services 後進行。在某些情況下，如果站點間網路連線非常良好，15 分鐘的 RPO 也是可行的。但是，整體而言，當需要低於一小時的 RPO 時，多資源日誌重播架構能帶來更好的結果。

災難恢復案例中的 RTO 與一致性群組複寫功能非常出色、通常從儲存點算起、以秒為單位。最直接的方法是中斷鏡射、資料庫已準備就緒、可以開始運作。資料庫啟動時間通常約為 10 秒、但有大量記錄交易的大型資料庫可能需要幾分鐘的時間。

判斷 RTO 的最重要因素不是儲存系統、而是執行 RTO 的應用程式和主機作業系統。例如、複寫的資料可在一秒或兩秒內提供、但這只代表資料。此外、還必須有正確設定的作業系統、並具備應用程式二進位檔、才能使用資料。

在某些情況下、客戶已預先準備好災難恢復執行個體、並在作業系統上預先探索到儲存設備。在這些情況下、啟動災難恢復案例只需要中斷鏡射並啟動應用程式即可。在其他情況下、作業系統和相關應用程式可能會與資料庫一起鏡射、做為 ESX 虛擬機器磁碟（ VMDK ）。在這些案例中、 RPO 是由客戶投資多少自動化來快速啟動 VMDK 、以便啟動應用程式所決定。

保留時間部分受快照限制控制。例如，ONTAP 中的 AFF 磁碟區和 ASA LUN 的快照數量上限為 1024 個。在某些情況下，客戶會採用多工複寫來提高此限制。例如，如果需要 2000 天的備份，可以將來源複寫到兩個不同的目的地，並在不同日期進行更新。這需要增加所需的初始空間，但與涉及多次完整備份的傳統備份系統相比，這仍然是一種更有效率的方法。



=== 單一磁碟區一致性群組（AFF）

最簡單的方法是將所有檔案或 LUN 放在同一個磁碟區中。磁碟區本身就是一個一致性群組，這意味著 SnapMirror 和 SnapVault 更新可以直接在儲存系統上排程。不需要外部軟體。



=== 單一 LUN / 命名空間一致性群組（ASA）

將整個資料庫放在單一 LUN/ 命名空間上看似奇怪，但這種做法正變得越來越普遍。磁碟區管理器最初創建的目的就是為了克服實體硬碟的效能和容量限制。在現代陣列中，呈現給主機的單一區塊裝置實際上已經跨多個硬碟進行抽象化。其大小可以動態調整，效能也遠超單一硬碟。

結果是，從 ESX 資料儲存區到 Oracle 資料庫等各種工作負載通常都可以託管在單一區塊裝置上。這不僅極大地簡化了資料管理，還帶來了其他有益的附加效果，例如由於需要探索的裝置數量減少，主機重新開機速度也更快。



=== 多磁碟區一致性群組

當資料庫必須跨越 AFF 磁碟區或 ASA LUN/ 命名空間時，需要一致性群組快照。如上所述，可以使用 System Manager 或 RESTful API 呼叫進行設定，此外 SnapCenter 能夠建立簡單的一致性群組快照。

此外，在使用 AFF 多磁碟區或 ASA 多 LUN 一致性快照進行災難復原時，還需考慮以下一點。在更新多個 SnapMirror 關係時，傳輸過程中可能會發生災難。這會導致一組磁碟區、LUN 或命名空間彼此不一致。如果發生這種情況，則必須將部分磁碟區還原到先前的快照狀態，才能提供一個崩潰一致性且可供使用的資料庫映像。



== 災難恢復：啟動



=== NFS

啟動災難恢復複本的程序取決於儲存類型。有了 NFS 、檔案系統就可以預先掛載到災難恢復伺服器上。它們處於唯讀狀態、當鏡射中斷時會變成讀寫狀態。如此可提供極低的 RPO 、而且整體災難恢復程序更可靠、因為需要管理的零件較少。



=== SAN

在災難恢復變得更複雜時啟動 SAN 組態。最簡單的選項通常是暫時中斷鏡像並掛載 SAN 資源、包括探索 LVM 組態（包括 Oracle 自動儲存管理 [ASM/] 等應用程式特定功能）、以及新增項目至 /etc/fstab 。

結果是目標伺服器知道 LUN 裝置路徑、磁碟區群組名稱和其他裝置路徑。然後可以關閉這些資源、然後還原鏡像。結果是伺服器處於可快速將應用程式上線的狀態。啟動磁碟區群組、掛載檔案系統、或啟動資料庫和應用程式的步驟都能輕鬆自動化。

必須謹慎確保災難恢復環境是最新的。例如、新的 LUN 可能會新增至來源伺服器、這表示必須在目的地預先探索新的 LUN 、以確保災難恢復計畫能如預期般運作。
