---
sidebar: sidebar 
permalink: oracle/oracle-host-config-hp-ux.html 
keywords: oracle, database, ontap, hp-ux 
summary: 使用 HP-UX 的 Oracle 資料庫 
---
= 使用 HP-UX 的 Oracle 資料庫
:allow-uri-read: 


[role="lead"]
適用於 HP-UX with ONTAP 上 Oracle 資料庫的組態主題。



== HP-UX NFS 掛載選項

下表列出單一執行個體的 HP-UX NFS 掛載選項。

|===
| 檔案類型 | 掛載選項 


| ADR 首頁 | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144,
suid` 


| 控制檔
資料檔案
重作記錄 | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144,forcedirectio, nointr,suid` 


| `ORACLE_HOME` | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144,
suid` 
|===
下表列出適用於 RAC 的 HP-UX NFS 掛載選項。

|===
| 檔案類型 | 掛載選項 


| ADR 首頁 | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144,
noac,suid` 


| 控制檔
資料檔案
重作記錄 | `rw, bg,hard, [vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144,
nointr,noac,forcedirectio,suid` 


| CRS/ 投票 | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144,
nointr,noac,
forcedirectio,suid` 


| 專屬 `ORACLE_HOME` | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144,
suid` 


| 共享 `ORACLE_HOME` | `rw,bg,hard,[vers=3,vers=4.1],proto=tcp,
timeo=600,rsize=262144,wsize=262144,
nointr,noac,suid` 
|===
單一執行個體與 RAC 掛載選項之間的主要差異在於新增 `noac` 和 `forcedirectio` 至掛載選項。此新增功能可停用主機作業系統快取、使 RAC 叢集中的所有執行個體都能一致地檢視資料狀態。雖然使用 `init.ora` 參數 `filesystemio_options=setall` 停用主機快取的效果相同、仍需使用 `noac` 和 `forcedirectio`。

原因 `noac` 為共享的必要項目 `ORACLE_HOME` 部署是為了促進檔案的一致性、例如 Oracle 密碼檔案和 spfiles 。如果 RAC 叢集中的每個執行個體都有專用的 `ORACLE_HOME`，不需要此參數。



== HP-UX VxFS 掛載選項

對於託管 Oracle 二進位檔的檔案系統、請使用下列掛載選項：

....
delaylog,nodatainlog
....
對於包含資料檔案、重做記錄檔、歸檔記錄檔和控制檔的檔案系統、若 HP-UX 版本不支援並行 I/O 、請使用下列掛載選項：

....
nodatainlog,mincache=direct,convosync=direct
....
支援並行 I/O （ VxFS 5.0.1 及更新版本、或 ServiceGuard Storage Management Suite ）時、請針對包含資料檔案、重作記錄檔、歸檔記錄檔和控制檔的檔案系統、使用這些掛載選項：

....
delaylog,cio
....

NOTE: 參數 `db_file_multiblock_read_count` 在 VxFS 環境中尤其重要。Oracle 建議在 Oracle 10g R1 及更新版本中保留此參數、除非另有特別指示。Oracle 8KB 區塊大小的預設值為 128 。如果此參數的值強制為 16 或更少、請移除 `convosync=direct` 裝載選項、因為它可能會損害連續 I/O 效能。此步驟會損害其他效能層面、只有在的價值下才應採取 `db_file_multiblock_read_count` 必須從預設值變更。
