---
sidebar: sidebar 
permalink: oracle/oracle-dp-online-backup.html 
keywords: oracle, data protection, hot backup 
summary: Oracle 資料庫快照型備份與還原 
searchtitle: Oracle 資料庫線上備份 
---
= 線上備份
:allow-uri-read: 


[role="lead"]
在備份模式中保護和恢復 Oracle 資料庫需要兩組資料。請注意、這不是唯一的 Oracle 備份選項、而是最常見的選項。

* 備份模式中資料檔案的快照
* 資料檔案處於備份模式時所建立的歸檔記錄


如果需要完整恢復（包括所有已提交的交易）、則需要第三個項目：

* 一組目前的重做記錄


有許多方法可以推動線上備份的還原。許多客戶使用 ONTAP CLI 還原快照、然後使用 Oracle RMAN 或 sqlplus 來完成還原。這在大型正式作業環境中尤其常見、因為資料庫還原的可能性和頻率極低、而且任何還原程序都是由熟練的 DBA 來處理。為了實現完整的自動化、 NetApp SnapCenter 等解決方案包含 Oracle 外掛程式、其中包含命令列和圖形介面。

有些大型客戶已在主機上設定基本指令碼、以便在特定時間將資料庫置於備份模式、以準備排程的快照、藉此採取更簡單的方法。例如、排程命令 `alter database begin backup` 23 時 58 分、 `alter database end backup` 於 00 ： 02 、然後於午夜直接在儲存系統上排程快照。如此一來、就能實現簡單易用、擴充性極高的備份策略、無需外部軟體或授權。



== 資料配置

最簡單的佈局是將資料檔案隔離在一個或多個專用磁碟區、LUN 或 NVMe 命名空間中。儲存資源必須不受任何其他檔案類型的污染。這樣做是為了確保可以透過 SnapRestore 操作快速還原資料檔案，而不會破壞重要的重做日誌、控制檔或歸檔日誌。

SAN 對專用資源內的資料檔案隔離也有類似的要求。對於使用 AFF 儲存設備的作業系統（例如 Microsoft Windows）、單一磁碟區可能包含多個資料檔案 LUN、每個 LUN 都使用 NTFS 檔案系統。而對於其他作業系統、通常會有一個邏輯磁碟區管理程式。例如、對於 Oracle ASM、最簡單的方案是將 ASM 磁碟群組的 LUN 限制在一個可以整體備份和還原的單一磁碟區中。如果出於效能或容量管理的原因需要額外的磁碟區、則在新磁碟區上建立額外的磁碟群組可以簡化管理。

ASA 不具備 AFF 系統上可以承載多個 LUN 的磁碟區級抽象化。ASA 則使用一致性群組。在許多情況下，單一 LUN 或 NVMe 命名空間即可滿足資料庫的管理和效能要求。如果需要多個 LUN 或命名空間，可以新增額外的資源並將其綁定到一個一致性群組中，該一致性群組即為資料檔案容器。

如果遵循這些準則，可以直接在儲存系統上排程快照。

* 注意： * 驗證 ASM `spfile` 和 `passwd` 檔案不在主控資料檔案的磁碟群組中。這會影響選擇性還原資料檔案和僅還原資料檔案的能力。



== 本機恢復程序— NFS

此程序可以手動或透過 SnapCenter 等應用程式來驅動。基本程序如下：

. 關閉資料庫。
. 將資料檔案 NFS 磁碟區還原到所需還原點之前的快照。
. 將歸檔記錄重播至所需的點。
. 如果需要完整還原、請重新播放目前的重做記錄。


此程序假設所需的歸檔記錄檔仍存在於作用中的檔案系統中。如果沒有、則必須還原歸檔記錄、或將 RMAN/sqlplus 導向快照目錄中的資料。

此外、對於較小的資料庫、終端使用者可以直接從中復原資料檔案 `.snapshot` 目錄、無需自動化工具或儲存管理員協助執行 `snaprestore` 命令。



== 本機恢復程序— SAN

此程序可以手動或透過 SnapCenter 等應用程式來驅動。基本程序如下：

. 關閉資料庫。
. 將託管資料檔案的磁碟群組置於系統中。此程序會因所選的邏輯磁碟區管理程式而異。使用 ASM 時、此程序需要卸除磁碟群組。在 Linux 中、必須卸除檔案系統、且必須停用邏輯磁碟區和磁碟區群組。目標是停止要還原之目標 Volume 群組上的所有更新。
. 將裝載資料檔案磁碟群組的 LUN 還原至所需還原點之前的 Snapshot。
. 重新啟動新還原的磁碟群組。
. 將歸檔記錄重播至所需的點。
. 如果需要完整還原、請重新播放所有重做記錄。


此程序假設所需的歸檔記錄仍存在於作用中檔案系統中。如果不存在、則必須將歸檔記錄 LUN/ 命名空間完全離線並執行還原、以還原歸檔記錄（或建立先前快照的複本、由於在同一主機上建立重複的 UUID 或 LVM 名稱、因此可能很困難）。這也是將歸檔記錄分隔成專屬儲存資源的實用範例。如果歸檔記錄與重做記錄共用磁碟區群組、則必須先將重做記錄複製到其他位置、才能還原整組 LUN 。此步驟可防止遺失最後記錄的交易。
