---
sidebar: sidebar 
permalink: oracle/oracle-ontap-config-capacity-limits.html 
keywords: capacity 
summary: 資料庫與 ONTAP 儲存容量與可用空間 
searchtitle: Oracle 資料庫與儲存容量管理 
---
= 容量管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
使用可預測、可管理的高效能企業儲存設備來管理資料庫或其他企業應用程式、需要磁碟機上的一些可用空間來進行資料和中繼資料管理。所需的可用空間量取決於使用的磁碟機類型和業務程序。

可用空間是指未用於實際資料的任何空間，包括 Aggregate 本身的未分配空間以及組成磁碟區中的未使用空間。也必須考慮精簡配置。例如，一個 AFF 磁碟區可能包含一個 1TB 的 LUN，其中只有 50% 用於實際資料。在精簡配置環境中，這看起來會正確佔用 500GB 的空間。然而，在完全配置的環境中，1TB 的全部容量看起來都已被使用。這 500GB 的未分配空間被隱藏了。這部分空間未被實際資料使用，因此應計入總可用空間的計算中。

NetApp 對於企業應用程式所使用的儲存系統建議如下：



== AFF SSD Aggregate 和 ASA 儲存可用區


TIP: * NetApp 建議 * 至少有 10% 的可用空間。這包括所有未使用的空間、包括集合體或磁碟區內的可用空間、以及因使用完整資源配置而分配但實際資料未使用的任何可用空間。邏輯空間並不重要、問題在於實際可用的實體空間可用於資料儲存。

10% 可用空間的建議非常保守。SSD 集合體可支援使用率更高的工作負載、而不會對效能造成任何影響。不過、隨著 Aggregate 的使用率增加、如果未仔細監控使用率、則用盡空間的風險也會增加。此外、當系統的容量達到 99% 時、可能不會導致效能降低、但在訂購額外硬體時、可能需要管理人員努力避免系統完全裝滿、而且可能需要一些時間來採購和安裝額外的磁碟機。



== HDD 集合體、包括 Flash Pool 集合體


TIP: * 使用旋轉磁碟機時、 NetApp 建議 * 至少有 15% 的可用空間。這包括所有未使用的空間、包括集合體或磁碟區內的可用空間、以及因使用完整資源配置而分配但實際資料未使用的任何可用空間。當可用空間接近 10% 時、效能會受到影響。
