---
sidebar: sidebar 
permalink: oracle/oracle-dp-snaprestore.html 
keywords: ontap, snaprestore 
summary: 利用快照快速復原 Oracle 資料庫 
searchtitle: 利用快照快速復原 Oracle 資料庫 
---
= SnapRestore
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 中從快照進行的快速資料還原是由 NetApp SnapRestore 技術提供，該技術可讓您立即還原 AFF 磁碟區或 ASA LUN 的狀態。

當關鍵資料集無法使用時、關鍵業務營運就會中斷。磁帶可能會中斷、甚至是從磁碟型備份還原、在網路上傳輸速度可能會很慢。SnapRestore 可提供近乎即時的資料集還原功能、避免這些問題。即使是 PB 規模的資料庫、只要花幾分鐘的時間就能完全還原。

雖然 AFF 和 ASA 平台的基本技術相同，但它們的使用方式略有不同。



== AFF 概述

AFF 系統上有兩種形式的 SnapRestore - 基於檔案的和基於磁碟區的：

* 無論是 2TB 的 LUN 還是 4KB 的檔案，都可以在幾秒鐘內還原個別 AFF 檔案、LUN 和命名空間以及個別 ASA LUN 和命名空間。
* 無論是 10GB 還是 100TB 的資料，AFF 磁碟區的全部內容都可以在幾秒鐘內恢復。


SnapRestore 之所以如此快速且高效，是因為快照的特性。快照本質上是磁碟區、LUN 或命名空間在特定時間點的內容的平行唯讀檢視。作用中區塊是實際可以變更的資料區塊，而快照則是建立快照時構成檔案和 LUN 的資料區塊狀態的唯讀檢視。

ONTAP 僅允許對快照資料進行唯讀存取，但可以使用 SnapRestore 重新啟動資料。重新啟動後，快照將以讀寫資料的形式呈現，使資料恢復到先前的狀態。SnapRestore 可以在磁碟區、檔案、LUN 或命名空間層級進行操作。該技術本質上相同，僅在行為上存在一些細微差別。



=== AFF Volume SnapRestore

基於磁碟區的 SnapRestore 會將整個磁碟區的內容還原到先前的狀態。此作業無需移動資料，這意味著還原程序幾乎是瞬間完成的，儘管 API 或 CLI 作業可能需要幾秒鐘的處理時間。還原 1GB 的資料與還原 1PB 的資料一樣簡單又快速。正是這項功能促使許多企業客戶遷移到 ONTAP 儲存系統。即使對於最大的資料集，它也能提供以秒為單位的 RTO。

Volume 型 SnapRestore 的缺點之一、是因為磁碟區內的變更會隨時間累積。因此、每個快照和作用中檔案資料都取決於到該點之前的變更。將磁碟區還原為較早的狀態、表示捨棄所有後續對資料所做的變更。然而、不太明顯的是、這包括後續建立的快照。這並不總是理想的。

例如、資料保留 SLA 可能會指定每晚備份 30 天。將資料集還原至五天前以 Volume SnapRestore 建立的快照、將會捨棄前五天建立的所有快照、違反 SLA 。

有許多選項可解決此限制：

. 資料可從先前的快照複製、而非執行整個 Volume 的 SnapRestore 。此方法最適合較小的資料集。
. 您可以複製快照、而非還原快照。此方法的限制在於來源快照是複本的相依性。因此、除非也刪除複本、或將其分割成一個不同的 Volume 、否則無法將其刪除。
. 使用檔案型 SnapRestore 。




=== AFF 檔案 SnapRestore

以檔案為基礎的 SnapRestore 是搭配 AFF 磁碟區使用的更精細快照型還原程序。它不會還原整個磁碟區的狀態，而是還原個別檔案、LUN 或命名空間的狀態。不需要刪除任何快照，此作業也不會對先前的快照產生任何相依性。檔案或 LUN 會立即在作用中磁碟區中可用。

在 SnapRestore 還原檔案或 LUN 期間，不需要移動資料。不過，需要進行一些內部中繼資料更新，以反映還原資料中的基礎區塊現在同時存在於快照和作用中磁碟區中。這應該不會影響效能，但此程序會封鎖快照的建立，直到完成為止。根據還原檔案的總大小，處理速率約為 5GBps（18TB/ 小時）。



== ASA LUN / 命名空間還原

在 ASA 上還原資料與 AFF SnapRestore 類似。資料只是還原到先前的狀態。此程序幾乎是即時的、不需要移動資料。它也有相同的限制、包括還原快照會導致後續刪除的快照也被刪除。如果這造成問題、有兩種選項。第一、可以從較早的快照複製 LUN/ 命名空間、同時保持來源磁碟區不變。這是即時且節省空間的程序。它本質上是對快照中區塊的唯讀指標進行讀寫複本。第二個選項是透過 REST API、它可以使用與 AFF 系統相同的單一檔案 SnapRestore 邏輯。結果是使用快照中的資料即時還原 LUN/ 命名空間、並保留所有快照。
