---
sidebar: sidebar 
permalink: oracle/oracle-asar2-storage-san-config-lun-sizing.html 
keywords: SAN, ASM, LVM, oracle, lun, sizing, count, ASA r2 
summary: Oracle 資料庫 LUN 大小調整和 LUN 數量指南（ ASA r2） 
searchtitle: 使用ASA r2 進行 Oracle 資料庫 LUN 大小調整和 LUN 計數 
---
= LUN 規模調整和 LUN 數量
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
選擇最佳 LUN 大小和要使用的 LUN 數量、對於 Oracle 資料庫的最佳效能和管理性至關重要。

LUN 是ONTAP上的虛擬化對象，它存在於ASA r2 系統上託管儲存可用區 (SAZ) 的所有磁碟機中。因此，LUN 的效能不受其大小的影響，因為無論選擇什麼大小，LUN 都能充分利用 SAZ 的全部效能潛力。

為了方便起見、客戶可能想要使用特定大小的 LUN 。例如、如果資料庫建置在由兩個 LUN 組成的 LVM 或 Oracle ASM 磁碟群組上、每個 LUN 均為 1TB 、則該磁碟群組必須以 1TB 為增量來擴充。最好是從八個 LUN （每個 LUN 爲 500GB ）構建磁盤組，以便可以以更小的增量來增加磁盤組。

我們不鼓勵建立通用標準 LUN 大小的做法、因為這樣做可能會使管理變得複雜。例如、當資料庫或資料存放區的範圍介於 1TB 到 2TB 時、 100GB 的標準 LUN 大小可能運作良好、但大小為 20TB 的資料庫或資料存放區需要 200 個 LUN 。這表示伺服器重新開機時間較長、不同 UI 中需要管理的物件較多、而 SnapCenter 等產品必須在許多物件上執行探索。使用較少、較大的 LUN 可避免此類問題。

* ASA r2 注意事項：*

* ASA r2 的最大 LUN 大小為 128TB，這允許使用更少但更大的 LUN，而不會影響效能。
* ASA r2 使用儲存可用區 (SAZ) 而不是聚合，但這並不會改變 Oracle 工作負載的 LUN 大小調整邏輯。
* 預設啟用精簡配置；調整 LUN 大小不會造成中斷，也不需要將其離線。




== LUN 計數

與 LUN 大小不同、 LUN 數量確實會影響效能。應用程式效能通常取決於透過 SCSI 層執行平行 I/O 的能力。因此、兩個 LUN 的效能優於單一 LUN 。使用 LVM （例如 Veritas VxVM 、 Linux LVM2 或 Oracle ASM ）是提高平行度的最簡單方法。

對於ASA r2，LUN 計數的原則與AFF/ FAS相同，因為ONTAP在跨平台處理並行 I/O 的方式類似。然而， ASA r2 的 SAN 專用架構和主動-主動對稱路徑確保了所有 LUN 的一致性能。

NetApp 客戶通常從 LUN 數量增加到 16 個以上獲得最小的效益、不過測試 100% SSD 環境時、隨機 I/O 非常繁重、這已證實可進一步改善至 64 個 LUN 。

[TIP]
====
* NetApp 建議 * 下列事項：

一般來說，4 到 16 個 LUN 足以滿足任何給定 Oracle 資料庫工作負載的 I/O 需求。由於主機 SCSI 實作方面的限制，少於四個 LUN 可能會造成效能限制。除了極端情況（例如非常高的隨機 I/O SSD 工作負載）之外，將 LUN 數量增加到 16 個以上很少能提高效能。

====