---
sidebar: sidebar 
permalink: oracle/oracle-dp-snaprestore.html 
keywords: ontap, snaprestore 
summary: 使用 SnapRestore 快速恢復 Oracle 資料庫 
---
= 使用 SnapRestore 快速恢復 Oracle 資料庫
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp SnapRestore 技術可從快照快速還原 ONTAP 中的資料。

當關鍵資料集無法使用時、關鍵業務營運就會中斷。磁帶可能會中斷、甚至是從磁碟型備份還原、在網路上傳輸速度可能會很慢。SnapRestore 可提供近乎即時的資料集還原功能、避免這些問題。即使是 PB 規模的資料庫、只要花幾分鐘的時間就能完全還原。

SnapRestore 有兩種形式：檔案 /LUN 型和磁碟區型。

* 無論是 2TB LUN 或 4KB 檔案、個別檔案或 LUN 都能在數秒內還原。
* 無論是 10GB 或 100TB 的資料、檔案或 LUN 的容器都能在數秒內還原。


「檔案或 LUN 的容器」通常指的是 FlexVol Volume 。例如、您可以在單一磁碟區中擁有 10 個組成 LVM 磁碟群組的 LUN 、或是一個磁碟區可以儲存 1000 位使用者的 NFS 主目錄。您可以將整個磁碟區還原為單一作業、而不需為每個個別檔案或 LUN 執行還原作業。此程序也適用於包含多個磁碟區的橫向擴充容器、例如 FlexGroup 或 ONTAP 一致性群組。

SnapRestore 之所以能如此快速有效地運作、是因為 Snapshot 複本的本質、基本上是在特定時間點平行檢視 Volume 內容的唯讀檢視。作用中區塊是可以變更的實際區塊、而快照則是建立快照時構成檔案和 LUN 之區塊狀態的唯讀檢視。

ONTAP 僅允許唯讀存取快照資料、但可透過 SnapRestore 重新啟動資料。快照會重新啟用為資料的讀寫檢視、並將資料恢復至先前的狀態。SnapRestore 可以在磁碟區或檔案層級運作。這項技術基本上相同、但行為上有一些小差異。



== Volume SnapRestore

Volume 型 SnapRestore 會將整個資料量傳回至較早的狀態。這項作業不需要資料移動、也就是說還原程序基本上是即時的、雖然 API 或 CLI 作業可能需要幾秒鐘的時間才能處理。還原 1GB 的資料並不比還原 1PB 的資料複雜或耗時。這項功能是許多企業客戶移轉至 ONTAP 儲存系統的主要原因。即使是最大的資料集、也能以秒為單位提供 RTO 。

Volume 型 SnapRestore 的缺點之一、是因為磁碟區內的變更會隨時間累積。因此、每個快照和作用中檔案資料都取決於到該點之前的變更。將磁碟區還原為較早的狀態、表示捨棄所有後續對資料所做的變更。然而、不太明顯的是、這包括後續建立的快照。這並不總是理想的。

例如、資料保留 SLA 可能會指定每晚備份 30 天。將資料集還原至五天前以 Volume SnapRestore 建立的快照、將會捨棄前五天建立的所有快照、違反 SLA 。

有許多選項可解決此限制：

. 資料可從先前的快照複製、而非執行整個 Volume 的 SnapRestore 。此方法最適合較小的資料集。
. 您可以複製快照、而非還原快照。此方法的限制在於來源快照是複本的相依性。因此、除非也刪除複本、或將其分割成一個不同的 Volume 、否則無法將其刪除。
. 使用檔案型 SnapRestore 。




== File SnapRestore

檔案型 SnapRestore 是更精細的快照型還原程序。個別檔案或 LUN 的狀態會還原、而非還原整個磁碟區的狀態。不需要刪除快照、此作業也不需要對先前的快照建立任何相依性。檔案或 LUN 會立即在作用中磁碟區中可用。

SnapRestore 還原檔案或 LUN 時不需要移動資料。不過、需要進行一些內部中繼資料更新、以反映檔案或 LUN 中的基礎區塊現在同時存在於快照和作用中磁碟區中。不應影響效能、但此程序會封鎖快照的建立、直到快照完成為止。根據還原的檔案總大小、處理速度約為 5Gbps （ 18TB/ 小時）。
