---
sidebar: sidebar 
permalink: oracle/oracle-asar2-app-config-block-sizes.html 
keywords: oracle, database, ASA r2, ontap, SAN, ASM, blocks 
summary: 使用ASA r2 的 Oracle 資料庫區塊大小 
searchtitle: 使用ASA r2 的 Oracle 資料庫區塊大小 
---
= 區塊大小
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP內部使用可變區塊大小，這表示 Oracle 資料庫可以配置為所需的任何區塊大小。然而，檔案系統區塊大小會影響效能，在某些情況下，更大的重做區塊大小可以提高效能。

與AFF/ FAS系統相比， ASA r2 對 Oracle 區塊大小建議沒有任何改變。ONTAP在所有平台上的行為保持一致。



== 資料檔案區塊大小

部分作業系統提供多種檔案系統區塊大小選擇。對於支援 Oracle 資料檔案檔案的檔案系統、使用壓縮時區塊大小應為 8KB 。不需要壓縮時、可以使用 8KB 或 4KB 的區塊大小。

如果資料檔案放在具有 512 位元組區塊的檔案系統上、則可能會有未對齊的檔案。根據 NetApp 建議、 LUN 和檔案系統可能已正確對齊、但檔案 I/O 可能未對齊。這種錯誤的調整會導致嚴重的效能問題。



== 重做區塊大小

支援重做記錄的檔案系統必須使用重做區塊大小的倍數。這通常需要重做記錄檔系統和重做記錄本身都使用 512 位元組的區塊大小。

重做率極高時、 4KB 區塊大小可能會執行得更好、因為重做率較高、可在較少且更有效率的作業中執行 I/O 。如果重做速率大於 50Mbps 、請考慮測試 4KB 區塊大小。

在具有 4KB 區塊大小和許多極小型交易的檔案系統上、使用 512 位元組區塊大小的重做記錄檔來識別資料庫中的一些客戶問題。將多個 512 位元組的變更套用到單一 4KB 檔案系統區塊所涉及的額外負荷、導致效能問題、而這些問題已透過將檔案系統變更為使用 512 位元組的區塊大小來解決。


TIP: * NetApp 建議 * 除非相關客戶支援或專業服務組織建議您變更重做區塊大小、否則請勿變更重做區塊大小、否則變更將以正式產品文件為基礎。
