---
sidebar: sidebar 
permalink: oracle/oracle-migration-fli-completion.html 
keywords: migration, oracle, FLI 
summary: Oracle 移轉與 FLI ：完成 
---
= Oracle 移轉與 FLI ：完成
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
從主機的角度來看、移轉已完成、但在匯入關係刪除之前、仍會從外部陣列提供 I/O 。

刪除關係之前、您必須確認所有 LUN 的移轉程序已完成。

....
Cluster01::*> lun import show -vserver vserver1 -fields foreign-disk,path,operational-state
vserver   foreign-disk path              operational-state
--------- ------------ ----------------- -----------------
vserver1 800DT$HuVWB/ /vol/new_asm/LUN4 completed
vserver1 800DT$HuVWBW /vol/new_asm/LUN0 completed
vserver1 800DT$HuVWBX /vol/new_asm/LUN1 completed
vserver1 800DT$HuVWBY /vol/new_asm/LUN2 completed
vserver1 800DT$HuVWBZ /vol/new_asm/LUN3 completed
vserver1 800DT$HuVWBa /vol/new_asm/LUN5 completed
vserver1 800DT$HuVWBb /vol/new_asm/LUN6 completed
vserver1 800DT$HuVWBc /vol/new_asm/LUN7 completed
vserver1 800DT$HuVWBd /vol/new_asm/LUN8 completed
vserver1 800DT$HuVWBe /vol/new_asm/LUN9 completed
vserver1 800DT$HuVWBf /vol/new_lvm/LUN0 completed
vserver1 800DT$HuVWBg /vol/new_lvm/LUN1 completed
vserver1 800DT$HuVWBh /vol/new_lvm/LUN2 completed
vserver1 800DT$HuVWBi /vol/new_lvm/LUN3 completed
vserver1 800DT$HuVWBj /vol/new_lvm/LUN4 completed
vserver1 800DT$HuVWBk /vol/new_lvm/LUN5 completed
vserver1 800DT$HuVWBl /vol/new_lvm/LUN6 completed
vserver1 800DT$HuVWBm /vol/new_lvm/LUN7 completed
vserver1 800DT$HuVWBn /vol/new_lvm/LUN8 completed
vserver1 800DT$HuVWBo /vol/new_lvm/LUN9 completed
20 entries were displayed.
....


== 刪除匯入關係

移轉程序完成後、請刪除移轉關係。完成後、 I/O 將由 ONTAP 上的磁碟機獨家提供。

....
Cluster01::*> lun import delete -vserver vserver1 -path /vol/new_asm/LUN0
Cluster01::*> lun import delete -vserver vserver1 -path /vol/new_asm/LUN1
...
Cluster01::*> lun import delete -vserver vserver1 -path /vol/new_lvm/LUN8
Cluster01::*> lun import delete -vserver vserver1 -path /vol/new_lvm/LUN9
....


== 取消註冊外部 LUN

最後、修改磁碟以移除 `is-foreign` 指定。

....
Cluster01::*> storage disk modify {-serial-number 800DT$HuVWBW} -is-foreign false
Cluster01::*> storage disk modify {-serial-number 800DT$HuVWBX} -is-foreign false
...
Cluster01::*> storage disk modify {-serial-number 800DT$HuVWBn} -is-foreign false
Cluster01::*> storage disk modify {-serial-number 800DT$HuVWBo} -is-foreign false
Cluster01::*>
....