= SnapCenter
:allow-uri-read: 


[role="lead"]
資料庫備份策略應以確定的業務需求為基礎、而非理論能力。透過結合 ONTAP 的 Snapshot 技術並運用 Microsoft SQL Server API 、無論使用者資料庫的大小為何、您都能快速進行應用程式一致的備份。如需更進階或橫向擴充的資料管理需求、 NetApp 提供 SnapCenter 。



== SnapCenter

SnapCenter 是適用於企業應用程式的 NetApp 資料保護軟體。使用適用於 SQL Server 的 SnapCenter 外掛程式、以及由 SnapCenter Plug-in for Microsoft Windows 管理的作業系統作業、即可快速輕鬆地保護 SQL Server 資料庫。

SQL Server 執行個體可以是獨立式安裝、容錯移轉叢集執行個體、也可以永遠位於可用性群組。結果是、從單一窗口即可保護、複製及還原主要或次要複本的資料庫。SnapCenter 可以同時管理內部部署、雲端和混合式組態的 SQL Server 資料庫。資料庫複本也可以在幾分鐘內在原始主機或替代主機上建立、以供開發或報告之用。

SQL Server 也需要作業系統與儲存設備之間的協調、以確保建立時快照中有正確的資料。在大多數情況下、唯一安全的方法是使用 SnapCenter 或 T-SQL 。在沒有這種額外協調的情況下建立的快照、可能無法可靠地恢復。

如需適用於 SnapCenter 的 SQL Server 外掛程式的詳細資訊、請參閱 link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf["TR-4714 ：使用 NetApp SnapCenter 的 SQL Server 最佳實務指南"^]。



== 使用 T-SQL 快照保護資料庫

在 SQL Server 2022 中、 Microsoft 推出了 T-SQL 快照、可提供建立指令碼和自動化備份作業的路徑。您可以為資料庫準備快照、而非執行完整大小的複本。資料庫準備好備份之後、您就可以利用 ONTAP REST API 來建立快照。

以下是備份工作流程範例：

. 使用 ALTER 命令凍結資料庫。如此一來、資料庫就能在基礎儲存設備上準備一致的快照。凍結之後、您可以使用備份命令來解凍資料庫並記錄快照。
. 使用新的備份群組和備份伺服器命令，在儲存單元上同時執行多個資料庫的快照。
. 如果資料庫工作負載橫跨多個儲存單元，請建立一致性群組以簡化管理工作。一致性群組是以單一單元管理的儲存單元集合。
. 執行完整備份或僅複製完整備份。這些備份也會記錄在 msdb 中。
. 使用快照完整備份後以正常串流方式進行的記錄備份、執行時間點還原。如果需要、也支援串流差異備份。


若要深入瞭解、請參閱 link:https://learn.microsoft.com/en-us/sql/relational-databases/databases/create-a-database-snapshot-transact-sql?view=sql-server-ver16["瞭解 T-SQL 快照的 Microsoft 文件"^]。


TIP: * NetApp 建議 * 使用 SnapCenter 來建立 Snapshot 複本。上述 T-SQL 方法也能正常運作，但 SnapCenter 提供完整的備份，還原及複製程序自動化功能。它也會執行探索、以確保建立正確的快照。
