---
sidebar: sidebar 
permalink: mssql/mssql-overview.html 
keywords: MSSQL,SQL Server,TR-4590, SnapCenter, ONTAP 
summary: ONTAP 上的 Microsoft SQL Server 
searchtitle: ONTAP 上的 Microsoft SQL Server 
---
= 總覽
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 為您的 Microsoft SQL Server 資料庫提供企業級的安全性與效能解決方案、同時也提供世界級的工具來管理您的環境。


NOTE: 本文件取代先前發佈的技術報告 _TR-4590 ： Microsoft SQL Server 與 ONTAP 的最佳實務做法指南

NetApp 假設讀者具備下列工作知識：

* ONTAP
* Microsoft SQL Server 架構與管理
* NetApp SnapCenter 做為備份軟體、包括：
+
** 適用於Microsoft Windows的解決方案SnapCenter
** 適用於 SQL Server 的 SnapCenter 外掛程式




本最佳實務做法一節的範圍僅限於根據 NetApp 建議的儲存基礎架構原則和偏好的標準進行技術設計。端點對端點實作超出範圍。

如需 NetApp 產品的相容性資訊，請參閱link:https://mysupport.netapp.com/matrix/["NetApp互通性對照表工具IMT （不含）"^]。



== Microsoft SQL Server 工作負載

部署 SQL Server 之前、您必須先瞭解 SQL Server 資料庫執行個體所支援之應用程式的工作負載需求。每個應用程式對於容量、效能和可用度的需求各不相同、因此每個資料庫都應該設計成能以最佳方式支援這些需求。許多組織會使用應用程式需求來定義 SLA 、將資料庫分類為多個管理層。SQL Server 工作負載通常分類如下：

* OLTP 通常是組織中最重要的資料庫。這些資料庫通常會支援面對客戶的應用程式、因此被視為是公司核心營運不可或缺的一環。關鍵任務 OLTP 資料庫及其支援的應用程式通常都有需要高效能的 SLA 、對效能降低敏感且需要最大可用度。他們也可能是永遠在容錯移轉叢集或永遠在可用度群組的候選對象。這些資料庫類型的 I/O 混合通常以 75% 到 90% 的隨機讀取和 25% 到 10% 的寫入為特徵。
* 決策支援系統（ DSS ）資料庫、有時稱為資料倉儲。這些資料庫對於許多仰賴分析來協助其業務的組織而言、都是關鍵任務。執行查詢時、這些資料庫會對 CPU 使用率和從磁碟讀取作業敏感。在許多組織中、 DSS 資料庫在月底、每季和每年都是最重要的此工作負載通常有將近 100% 的讀取 I/O 混合、而 IO 處理量通常比 IOPS 更重要。

