---
sidebar: sidebar 
permalink: mssql/mssql-disaster-recovery.html 
keywords: MSSQL,SQL Server, disaster recovery, snapmirror 
summary: 使用 ONTAP 進行 Microsoft SQL Server 災難恢復 
---
= 使用 ONTAP 進行 Microsoft SQL Server 災難恢復
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
企業資料庫和應用程式基礎架構通常需要複寫、才能在最短的停機時間內、避免自然災難或非預期的業務中斷。

SQL Server 全年無休可用性群組複寫功能是絕佳的選項、 NetApp 提供多種選項、可將資料保護與全年無休整合。不過、在某些情況下、您可能會想要考慮使用 ONTAP 複寫技術。有三個基本選項。



== SnapMirror

SnapMirror 技術提供快速靈活的企業解決方案、可在 LAN 和 WAN 上複寫資料。SnapMirror 技術只會在建立初始鏡射後、將變更的資料區塊傳輸到目的地、大幅降低網路頻寬需求。可以在同步或非同步模式中設定。



== NetApp MetroCluster

MetroCluster 組態有助於為應用程式、資料庫和虛擬化平台提供高可用度、零資料遺失的儲存解決方案。此解決方案是結合陣列型叢集與同步複寫來實作、為整個儲存設備和主機環境提供額外的保護層。



== SnapMirror Active Sync （前身為 SnapMirror Business Continuity ）

SnapMirror 主動式同步是以 SnapMirror Synchronous 及其將多個 LUN 複寫到複本儲存設備的能力為基礎、同時維持寫入順序的一致性。使用 MetroCluster 時、包括網路組態在內的 ONTAP 控制器在站台之間應相同。有了 SnapMirror 主動式同步、您基本上擁有兩個不同的 ONTAP 系統、可維護 LUN 資料的獨立複本、但可以合作呈現該 LUN 的單一執行個體。從主機的角度來看、這是單一 LUN 實體。

MetroCluster 與 SnapMirror 主動式同步的主要差異在於精細度和擴充性。如果您只需要選取要同步複寫的特定工作負載、或兩個站台都應該提供 LUN 以進行讀寫作業、則 SnapMirror 主動式同步是更好的選擇。如果您需要複寫整個環境、甚至是資料中心、 MetroCluster 是更好的選擇。此外、 SnapMirror 主動式同步目前僅適用於 SAN 、而 MetroCluster 則是多重傳輸協定、包括 SAN 、 NFS 和 SMB 。

如需 SnapMirror 的詳細資訊，請參閱link:https://www.netapp.com/pdf.html?item=/media/17229-tr4015pdf.pdf["TR-4015 ： ONTAP 9 的 SnapMirror 組態與最佳實務做法指南"^]。
