---
sidebar: sidebar 
permalink: mssql/mssql-storage-considerations-ASA.html 
keywords: MSSQL,SQL Server, volumes, LUN, SnapCenter 
summary: ASA 系統上的 Microsoft SQL Server 儲存考量 
searchtitle: Microsoft SQL Server 儲存考量 
---
= 總覽
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
NetApp ASA R2 為僅限執行關鍵任務工作負載的 SAN 客戶，提供簡化且功能強大的解決方案。執行 ONTAP 儲存解決方案的 ASA R2 平台與 Microsoft SQL Server 的結合，可實現企業級資料庫儲存設計，滿足現今最嚴苛的應用程式需求。

下列 ASA 平台歸類為支援所有 SAN 傳輸協定（ iSCSI ， FC ， NVMe / FC ， NVMe / TCP ）的 ASA R2 系統。iSCSI ， FC ， NVMe / FC 和 NVMe / TCP 傳輸協定支援對稱的雙主動式架構，可執行多重路徑，讓主機和儲存設備之間的所有路徑都處於主動 / 最佳化狀態：

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20


如需詳細資訊、請參閱 link:https://docs.netapp.com/us-en/asa-r2/index.html["NetApp ASA"]

在 ONTAP 解決方案上最佳化 SQL Server 需要瞭解 SQL Server I/O 模式和特性。SQL Server 資料庫設計完善的儲存配置必須支援 SQL Server 的效能需求、同時提供整個基礎架構的最大管理能力。良好的儲存配置也能讓初始部署成功、並隨著業務成長、環境隨時間而順利成長。



== 資料儲存設計

Microsoft 建議將資料和記錄檔放在不同的磁碟機上。對於同時更新和要求資料的應用程式、記錄檔會密集寫入、而且資料檔（視應用程式而定）會密集讀寫。對於資料擷取、不需要記錄檔。因此、您可以從放在自己磁碟機上的資料檔案來滿足資料要求。

當您建立新資料庫時、Microsoft建議您為資料和記錄指定個別的磁碟機。若要在資料庫建立之後移動檔案、資料庫必須離線。如需更多 Microsoft 建議、請參閱 link:https://docs.microsoft.com/en-us/sql/relational-databases/policy-based-management/place-data-and-log-files-on-separate-drives?view=sql-server-ver15["將資料和記錄檔放在不同的磁碟機上"^]。



=== 儲存單元考量

ASA 中的儲存單元是指 SCSI/FC 主機的 LUN ，或 NVMe 主機的 NVMe 命名空間。根據支援的傳輸協定，系統會提示您建立 LUN ， NVMe 命名空間或兩者。在您建立資料庫部署的儲存單元之前，請務必瞭解 SQL Server I/O 模式和特性的差異，視工作負載及備份與還原需求而定。請參閱下列儲存單元的 NetApp 建議：

* 避免在同一主機上執行的多個 SQL Server 之間共用相同的儲存單元，以避免複雜的管理作業。在同一主機上執行多個 SQL Server 執行個體的情況下，除非您接近節點上的儲存單元限制，否則請避免共用，而每個主機的每個執行個體都有個別的儲存單元，以便於資料管理。
* 請使用 NTFS 掛載點而非磁碟機代號、以超越 Windows 中 26 個磁碟機代號的限制。
* 停用快照排程和保留原則。而是使用 SnapCenter 來協調 SQL Server 資料儲存單元的 Snapshot 複本。
* 將 SQL Server 系統資料庫放在專用的儲存單元上。
* Tempdb 是 SQL Server 用來做為暫用工作區的系統資料庫，特別是用於 I/O 密集型 DBCC CHECKDB 作業。因此，請將此資料庫放在專用的儲存單元上。在儲存單元數是一項挑戰的大型環境中，您可以在仔細規劃之後，將 tempdb 與系統資料庫整合到同一個儲存單元中。對 tempdb 的資料保護不是高優先順序、因為每次重新啟動 SQL Server 時都會重新建立此資料庫。
* 將使用者資料檔案放(`.mdf`在不同的儲存單元上，因為它們是隨機讀取 / 寫入工作負載。建立交易記錄備份的頻率通常高於資料庫備份。因此(`.ldf`，請將交易記錄檔放在不同的儲存單元或 VMDK 上，以建立每個儲存單元的獨立備份排程。這種分隔方式也能將記錄檔的連續寫入I/O與資料檔案的隨機讀寫I/O隔離、大幅提升SQL Server效能。
* 請確定要儲存記錄備份的使用者資料庫檔案和記錄目錄位於不同的儲存單元上，以防止保留原則在將快照與 SnapMirror 功能搭配資料保險箱原則使用時覆寫快照。
* 請勿在同一個儲存單元上混合使用資料庫和非資料庫檔案，例如全文搜尋相關檔案。
* 將資料庫次要檔案（作為檔案群組的一部分）放置在不同的儲存單元上，可改善 SQL Server 資料庫的效能。只有當資料庫的檔案未與任何其他檔案共用其儲存單元 `.mdf`時，此分隔才有效 `.mdf`。
* 在 Windows 伺服器中使用磁碟管理程式格式化磁碟時，請確定分割區的分配單元大小設為 64K 。
* 請勿將使用者資料庫或系統資料庫放置在裝載點的儲存單元上。
* 請參閱 link:https://www.netapp.com/media/10680-tr4080.pdf["適用於現代 SAN 的 ONTAP 最佳實務做法下的 Microsoft Windows 和原生 MPIO"] 將 Windows 上的多重路徑支援套用至 MPIO 內容中的 iSCSI 裝置。
* 如果您使用的是 Always on 容錯移轉叢集執行個體，則使用者資料庫必須放置在跨 Windows 伺服器容錯移轉叢集節點共用的儲存單元上，而且實體磁碟叢集資源會指派給與 SQL Server 執行個體相關聯的叢集群組。

