---
sidebar: sidebar 
permalink: mssql/mssql-log-directory.html 
keywords: MSSQL,SQL Server, volumes, LUN, SnapCenter 
summary: Microsoft SQL Server 記錄目錄 
searchtitle: Microsoft SQL Server 記錄目錄 
---
= 記錄目錄
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
記錄目錄是在 SQL Server 中指定、用於在主機層級儲存交易記錄備份資料。如果您使用 SnapCenter 來備份記錄檔、則 SnapCenter 使用的每個 SQL Server 主機都必須設定一個主機記錄目錄、才能執行記錄備份。由於包含資料庫儲存庫、因此與備份、還原或複製作業相關的中繼資料會儲存在中央資料庫儲存庫中SnapCenter 。

主機記錄目錄的大小計算方式如下：
主機記錄目錄大小 = （（最大 DB LDF 大小 x 每日記錄變更率 % ） x （快照保留） ÷ （ 1 - LUN 額外負荷空間 % ）
主機記錄目錄大小調整公式假設 LUN 負荷空間為 10%

將記錄目錄放在專用磁碟區或 LUN 上。主機記錄目錄中的資料量取決於備份的大小和保留備份的天數。SnapCenter 每個 SQL Server 主機只允許一個主機記錄目錄。您可以在 SnapCenter --> 主機 --> 組態外掛程式中設定主機記錄目錄。

[TIP]
====
* NetApp 建議 * 下列主機記錄目錄：

* 請確定主機記錄目錄未被任何其他可能毀損備份快照資料的資料類型共用。
* 請勿將使用者資料庫或系統資料庫放置在裝載點的 LUN 上。
* 在 SnapCenter 複製交易記錄檔的專用磁碟區上建立主機記錄目錄。
* 使用 SnapCenter 精靈將資料庫移轉至 NetApp 儲存設備、以便將資料庫儲存在有效位置、進而成功執行 SnapCenter 備份與還原作業。請記住、移轉程序會中斷運作、並可能導致資料庫在移轉進行中時離線。
* SQL Server 的容錯移轉叢集執行個體（ FCI ）必須符合下列條件：
+
** 如果您使用容錯移轉叢集執行個體、則主機記錄目錄 LUN 必須是與要備份 SnapCenter 的 SQL Server 執行個體位於同一個叢集群組中的叢集磁碟資源。
** 如果您使用容錯移轉叢集執行個體、則使用者資料庫必須放置在共用 LUN 上、這些 LUN 是指派給與 SQL Server 執行個體相關聯的叢集群組的實體磁碟叢集資源。




====