---
sidebar: sidebar 
permalink: mssql/mssql-storage-considerations.html 
keywords: MSSQL,SQL Server, volumes, LUN, SnapCenter 
summary: Microsoft SQL Server 儲存考量 
searchtitle: Microsoft SQL Server 儲存考量 
---
= 總覽
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 儲存解決方案與 Microsoft SQL Server 的結合、可實現企業級資料庫儲存設計、滿足現今最嚴苛的應用程式需求。

在 ONTAP 解決方案上最佳化 SQL Server 需要瞭解 SQL Server I/O 模式和特性。SQL Server 資料庫設計完善的儲存配置必須支援 SQL Server 的效能需求、同時提供整個基礎架構的最大管理能力。良好的儲存配置也能讓初始部署成功、並隨著業務成長、環境隨時間而順利成長。



== 資料儲存設計

對於不使用SnapCenter 支援功能執行備份的SQL Server資料庫、Microsoft建議將資料和記錄檔放在不同的磁碟機上。對於同時更新和要求資料的應用程式、記錄檔會密集寫入、而且資料檔（視應用程式而定）會密集讀寫。對於資料擷取、不需要記錄檔。因此、您可以從放在自己磁碟機上的資料檔案來滿足資料要求。

當您建立新資料庫時、Microsoft建議您為資料和記錄指定個別的磁碟機。若要在資料庫建立之後移動檔案、資料庫必須離線。如需更多 Microsoft 建議、請參閱 link:https://docs.microsoft.com/en-us/sql/relational-databases/policy-based-management/place-data-and-log-files-on-separate-drives?view=sql-server-ver15["將資料和記錄檔放在不同的磁碟機上"^]。



== 集合體

Aggregate 是 NetApp 儲存組態的最低層級儲存容器。網際網路上存在一些舊版文件、建議將 IO 分隔到不同的基礎磁碟機集。ONTAP 不建議這麼做。NetApp 已使用資料檔案和交易記錄檔分離的共用和專用集合體、執行各種 I/O 工作負載特性分析測試。測試結果顯示、一個大型集合體含有更多 RAID 群組和磁碟機、可最佳化和改善儲存效能、而且管理員更容易管理、原因有兩個：

* 一個大型集合體可讓所有檔案都能使用所有磁碟機的 I/O 功能。
* 一個大型Aggregate可讓您以最有效率的方式使用磁碟空間。


若要獲得高可用度（ HA ）、請將 SQL Server Always On Availability Group 次要同步複本放在 Aggregate 中的獨立儲存虛擬機器（ SVM ）上。為了進行災難恢復、請將非同步複本放在 DR 站台中屬於獨立儲存叢集的集合上、並使用 NetApp SnapMirror 技術複寫內容。NetApp 建議在集合體中至少有 10% 的可用空間、以獲得最佳的儲存效能。



== 磁碟區

磁碟區會建立並位於集合體內。此術語有時會造成混淆、因為 ONTAP 磁碟區不是 LUN 。ONTAP Volume 是資料的管理容器。磁碟區可能包含檔案、 LUN 、甚至 S3 物件。磁碟區不會佔用空間、只會用於管理內含的資料。



=== Volume 設計考量

在您建立資料庫 Volume 設計之前、請務必瞭解 SQL Server I/O 模式和特性的差異、視工作負載及備份與還原需求而定。請參閱下列 NetApp 建議的彈性磁碟區：

* 避免在主機之間共用磁碟區。例如、雖然可以在單一磁碟區中建立 2 個 LUN 、並將每個 LUN 共用至不同的主機、但這應該避免、因為這樣可能會使管理複雜化。在同一主機上執行多個 SQL Server 執行個體的情況下，除非您接近節點上的磁碟區限制，否則請避免共用磁碟區，而每個主機的每個執行個體都有個別的磁碟區，以便於進行資料管理。
* 請使用 NTFS 掛載點而非磁碟機代號、以超越 Windows 中 26 個磁碟機代號的限制。使用 Volume 掛載點時、一般建議將 Volume 標籤命名為與掛載點相同的名稱。
* 適當時、請設定 Volume 自動調整大小原則、以協助避免空間不足的情況。
* 如果您在 SMB 共用上安裝 SQL Server 、請確定已在 SMB 磁碟區上啟用 Unicode 以建立資料夾。
* 將磁碟區中的快照保留值設為零、以便從作業角度進行監控。
* 停用快照排程和保留原則。而是使用 SnapCenter 來協調 SQL Server 資料磁碟區的 Snapshot 複本。
* 將 SQL Server 系統資料庫放在專用磁碟區上。
* Tempdb 是 SQL Server 用來做為暫用工作區的系統資料庫、特別是用於 I/O 密集型 DBCC CHECKDB 作業。因此、請將此資料庫放在具有獨立磁碟集的專用磁碟區上。在磁碟區數是一項挑戰的大型環境中、您可以將Tempdb整合為較少的磁碟區、並在經過仔細規劃之後、將其儲存在與其他系統資料庫相同的磁碟區中。對 tempdb 的資料保護不是高優先順序、因為每次重新啟動 SQL Server 時都會重新建立此資料庫。
* 將使用者資料檔案放(`.mdf`在不同的磁碟區上、因為它們是隨機讀取 / 寫入工作負載。建立交易記錄備份的頻率通常高於資料庫備份。因此(`.ldf`、請將交易記錄檔放在不同的磁碟區或 VMDK 上、以便為每個資料檔案建立獨立的備份排程。這種分隔方式也能將記錄檔的連續寫入I/O與資料檔案的隨機讀寫I/O隔離、大幅提升SQL Server效能。




== LUN

* 請確定使用者資料庫檔案和用於儲存記錄備份的記錄目錄位於不同的磁碟區、以防止保留原則在與 SnapVault 技術搭配使用時覆寫快照。
* 請勿在同一個 LUN 上混合使用資料庫和非資料庫檔案、例如與全文搜尋相關的檔案。
* 將資料庫次要檔案（作為檔案群組的一部分）放置在不同的磁碟區、可改善 SQL Server 資料庫的效能。只有當資料庫的檔案未與任何其他檔案共用其 LUN `.mdf` 時、此分隔才有效 `.mdf`。
* 如果您使用 DiskManager 或其他工具建立 LUN 、請確保在格式化 LUN 時、將分割區的分配單元大小設為 64K 。
* 請參閱 link:https://www.netapp.com/media/10680-tr4080.pdf["適用於現代 SAN 的 ONTAP 最佳實務做法下的 Microsoft Windows 和原生 MPIO"] 將 Windows 上的多重路徑支援套用至 MPIO 內容中的 iSCSI 裝置。

