---
sidebar: sidebar 
permalink: mssql/mssql-storage-considerations.html 
keywords: MS-SQL,mssql,SQL Server 
summary: ONTAP 上的 Microsoft SQL Server 
---
= Microsoft SQL Server 儲存考量
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
結合 NetApp 儲存解決方案與 Microsoft SQL Server 、可建立企業級資料庫儲存設計、滿足現今最嚴苛的應用程式需求。

若要最佳化這兩種技術、瞭解 SQL Server I/O 模式和特性是非常重要的。精心設計的SQL Server資料庫儲存配置可支援SQL Server的效能及SQL Server基礎架構的管理。良好的儲存配置也能讓初始部署成功、並隨著業務成長、環境隨時間而順利成長。



== 資料儲存設計

對於不使用SnapCenter 支援功能執行備份的SQL Server資料庫、Microsoft建議將資料和記錄檔放在不同的磁碟機上。對於同時更新和要求資料的應用程式、記錄檔會密集寫入、而且資料檔（視應用程式而定）會密集讀寫。對於資料擷取、不需要記錄檔。因此、您可以從放在自己磁碟機上的資料檔案來滿足資料要求。

當您建立新資料庫時、Microsoft建議您為資料和記錄指定個別的磁碟機。若要在資料庫建立之後移動檔案、資料庫必須離線。如需更多 Microsoft 建議、請參閱 link:https://docs.microsoft.com/en-us/sql/relational-databases/policy-based-management/place-data-and-log-files-on-separate-drives?view=sql-server-ver15["將資料和記錄檔放在不同的磁碟機上"^]。



== 集合體

Aggregate 是 NetApp 儲存組態的主要儲存容器、包含一個或多個 RAID 群組、其中包括資料磁碟和同位元磁碟。NetApp 已使用資料檔案和交易記錄檔分離的共用和專用集合體、執行各種 I/O 工作負載特性分析測試。測試結果顯示、一個大型集合體具有更多的 RAID 群組和磁碟、可最佳化及改善儲存效能、而且管理員更容易管理、原因有兩個：

* 一個大型集合體可讓所有磁碟的 I/O 功能可供所有檔案使用。
* 一個大型Aggregate可讓您以最有效率的方式使用磁碟空間。


若要獲得高可用度（ HA ）、請將 SQL Server Always On Availability Group 次要同步複本放在 Aggregate 中的獨立儲存虛擬機器（ SVM ）上。為了進行災難恢復、請將非同步複本放在 DR 站台中屬於獨立儲存叢集的集合上、並使用 NetApp SnapMirror 技術複寫內容。NetApp 建議在集合體中至少有 10% 的可用空間、以獲得最佳的儲存效能。



== 磁碟區

NetApp FlexVol 磁碟區會建立並位於集合體內。許多磁碟區都可以建立在單一集合體中、而且每個磁碟區都可以在集合體之間進行擴充、縮減或移動、而不會造成使用者停機。



=== Volume 設計考量

在您建立資料庫 Volume 設計之前、請務必瞭解 SQL Server I/O 模式和特性的差異、視工作負載及備份與還原需求而定。請參閱下列 NetApp 建議的彈性磁碟區：

* 使用靈活的 Volume 來儲存 SQL Server 資料庫檔案、避免在主機之間共用磁碟區。
* 請使用 NTFS 掛載點而非磁碟機代號、以超越 Windows 中 26 個磁碟機代號的限制。使用 Volume 掛載點時、一般建議將 Volume 標籤命名為與掛載點相同的名稱。
* 適當時、請設定 Volume 自動調整大小原則、以協助避免空間不足的情況。17 Microsoft SQL Server with ONTAP 最佳實務指南 © 2022 NetApp 、 Inc. 版權所有。
* 當 SQL Server 資料庫 I/O 設定檔包含大部分的大量循序讀取（例如決策支援系統工作負載）時、可在磁碟區上啟用讀取重新分配。讀取重新分配可最佳化區塊、提供更好的效能。
* 如果您在 SMB 共用上安裝 SQL Server 、請確定已在 SMB/CIFS 磁碟區上啟用 Unicode 以建立資料夾。
* 將磁碟區中的 NetApp Snapshot 複本保留值設為零、以便從作業角度進行監控。
* 停用 Storage Snapshot ™複本排程和保留原則。而是使用 SnapCenter 來協調 SQL Server 資料磁碟區的 Snapshot 複本。
* 將 SQL Server 系統資料庫放在專用磁碟區或 VMDK 上。
* Tempdb 是 SQL Server 用來做為暫用工作區的系統資料庫、特別是用於 I/O 密集型 DBCC CHECKDB 作業。因此、請將此資料庫放在具有獨立磁碟集的專用磁碟區上。在磁碟區數是一項挑戰的大型環境中、您可以將Tempdb整合為較少的磁碟區、並在經過仔細規劃之後、將其儲存在與其他系統資料庫相同的磁碟區中。對 tempdb 的資料保護不是高優先順序、因為每次重新啟動 SQL Server 時都會重新建立此資料庫。
* 將使用者資料檔（.mdf）放在不同的磁碟區上、因為它們是隨機讀取/寫入工作負載。建立交易記錄備份的頻率通常高於資料庫備份。因此、請將交易記錄檔（ .ldf ）放在不同的磁碟區、或將 VMDK 放在資料檔案中、以便為每個檔案建立獨立的備份排程。這種分隔方式也能將記錄檔的連續寫入I/O與資料檔案的隨機讀寫I/O隔離、大幅提升SQL Server效能。




== LUN

* 請確定使用者資料庫檔案和用於儲存記錄備份的記錄目錄位於不同的磁碟區、以防止保留原則在與 SnapVault 技術搭配使用時覆寫快照。
* 請確定 SQL Server 資料庫位於與具有非資料庫檔案（例如全文搜尋相關檔案）的 LUN 分開的 LUN 上。
* 將資料庫次要檔案（作為檔案群組的一部分）放置在不同的磁碟區、可改善 SQL Server 資料庫的效能。只有當資料庫的 .mdf 檔案未與任何其他 .mdf 檔案共用其 LUN 時、此分隔才有效。
* 如果您使用 DiskManager 或其他工具建立 LUN 、請確保在格式化 LUN 時、將分割區的分配單元大小設為 64K 。
* 請參閱 link:https://www.netapp.com/media/10680-tr4080.pdf["適用於現代 SAN 的 ONTAP 最佳實務做法下的 Microsoft Windows 和原生 MPIO"] 將 Windows 上的多重路徑支援套用至 MPIO 內容中的 iSCSI 裝置。




=== 記錄目錄

記錄目錄是在 SQL Server 中指定、用於在主機層級儲存交易記錄備份資料。如果您使用 SnapCenter 來備份記錄檔、則 SnapCenter 使用的每個 SQL Server 主機都必須設定一個主機記錄目錄、才能執行記錄備份。由於包含資料庫儲存庫、因此與備份、還原或複製作業相關的中繼資料會儲存在中央資料庫儲存庫中SnapCenter 。

主機記錄目錄的大小計算方式如下：
主機記錄目錄大小 = （（最大 DB LDF 大小 x 每日記錄變更率 % ） x （快照保留） ÷ （ 1 - LUN 額外負荷空間 % ）
主機記錄目錄大小調整公式假設 LUN 負荷空間為 10%

將記錄目錄放在專用磁碟區或 LUN 上。主機記錄目錄中的資料量取決於備份的大小和保留備份的天數。SnapCenter 每個 SQL Server 主機只允許一個主機記錄目錄。您可以在 SnapCenter --> 主機 --> 組態外掛程式中設定主機記錄目錄。

[TIP]
====
* NetApp 建議 * 下列主機記錄目錄：

* 請確定主機記錄目錄未被任何其他可能毀損備份快照資料的資料類型共用。
* 請勿將使用者資料庫或系統資料庫放置在裝載點的 LUN 上。
* 在 SnapCenter 複製交易記錄的專用 FlexVol 磁碟區上建立主機記錄目錄。
* 使用 SnapCenter 精靈將資料庫移轉至 NetApp 儲存設備、以便將資料庫儲存在有效位置、進而成功執行 SnapCenter 備份與還原作業。請記住、移轉程序會中斷運作、並可能導致資料庫在移轉進行中時離線。
* SQL Server 的容錯移轉叢集執行個體（ FCI ）必須符合下列條件：
+
** 如果您使用容錯移轉叢集執行個體、則主機記錄目錄 LUN 必須是與要備份 SnapCenter 的 SQL Server 執行個體位於同一個叢集群組中的叢集磁碟資源。
** 如果您使用容錯移轉叢集執行個體、則使用者資料庫必須放置在共用 LUN 上、這些 LUN 是指派給與 SQL Server 執行個體相關聯的叢集群組的實體磁碟叢集資源。




====