---
sidebar: sidebar 
permalink: mssql/mssql-disaster-recovery.html 
keywords: MSSQL,SQL Server, disaster recovery, snapmirror 
summary: 使用 ONTAP 進行 Microsoft SQL Server 災難恢復 
searchtitle: 使用 ONTAP 進行 Microsoft SQL Server 災難恢復 
---
= 災難恢復
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
企業資料庫和應用程式基礎架構通常需要複寫、才能在最短的停機時間內、避免自然災難或非預期的業務中斷。

SQL Server 全年無休可用性群組複寫功能是絕佳的選項、 NetApp 提供多種選項、可將資料保護與全年無休整合。不過、在某些情況下、您可能會想要考慮使用 ONTAP 複寫技術。有三個基本選項。



== SnapMirror

SnapMirror 技術提供快速靈活的企業解決方案、可在 LAN 和 WAN 上複寫資料。SnapMirror 技術只會在建立初始鏡射後、將變更的資料區塊傳輸到目的地、大幅降低網路頻寬需求。可以在同步或非同步模式中設定。



== NetApp MetroCluster 和 SnapMirror 作用中同步

對於許多客戶而言，災難恢復不僅需要擁有遠端資料複本，還需要能夠快速使用該資料。NetApp 提供兩種技術來滿足這種需求： MetroCluster 和 SnapMirror 主動同步

MetroCluster 指的是硬體組態中的 ONTAP 、其中包括低階同步鏡射儲存設備和許多其他功能。MetroCluster 等整合式解決方案可簡化現今複雜的橫向擴充資料庫、應用程式及虛擬化基礎架構。它以一個簡單的中央儲存陣列取代多種外部資料保護產品和策略。它也能在單一叢集式儲存系統中提供整合式備份、還原、災難恢復和高可用度（ HA ）。

SnapMirror 主動同步是以 SnapMirror Synchronous 為基礎。使用 MetroCluster 、每個 ONTAP 控制器都負責將其磁碟機資料複寫到遠端位置。有了 SnapMirror 主動式同步、您基本上擁有兩個不同的 ONTAP 系統、可維護 LUN 資料的獨立複本、但可以合作呈現該 LUN 的單一執行個體。從主機的角度來看、這是單一 LUN 實體。



== SM 與 MCC 比較

SM-AS 和 MetroCluster 在整體功能上相似，但在實作 RPO =0 複寫的方式及其管理方式上有重要差異。SnapMirror 非同步和同步也可作為 DR 計畫的一部分使用，但它們並非設計為 HA 重新安裝技術。

* MetroCluster 組態更像是一個整合式叢集，節點分散在各個站台上。SM-AS 的運作方式類似於兩個原本是相互不同的叢集，這些叢集正在合作為選取的 RPO = 0 同步複寫 LUN 提供服務。
* MetroCluster 組態中的資料只能在任何指定時間從特定站台存取。另一個資料複本位於另一個站台，但資料是被動的。如果沒有儲存系統容錯移轉，就無法存取。
* MetroCluster 和 SM-AS 執行鏡像會在不同層級執行。MetroCluster 鏡射是在 RAID 層執行。低階資料會使用 SyncMirror 以鏡射格式儲存。在 LUN ，磁碟區和傳輸協定層，使用鏡像幾乎是不可見的。
* 相反地， SM-AS 鏡射則發生在傳輸協定層。這兩個叢集都是整體上的不相關叢集。資料的兩個複本同步後，兩個叢集只需鏡射寫入。當某個叢集發生寫入時，它會複寫到另一個叢集。只有當兩個站台的寫入作業完成時，才會將寫入內容確認給主機。除了這種傳輸協定分割行為之外，這兩個叢集都是正常的 ONTAP 叢集。
* MetroCluster 的主要角色是大規模複寫。您可以使用 RPO=0 和接近零的 RTO 來複寫整個陣列。這簡化了容錯移轉程序，因為只有一件事需要容錯移轉，而且在容量和 IOPS 方面的擴充能力極佳。
* SMAS 的一個關鍵使用案例是精細複寫。有時候您不想將所有資料複寫為單一單元，或者您需要選擇性地容錯移轉特定工作負載。
* 另一個用於 SM-AS 的重要使用案例是用於雙主動式作業，您想要在兩個不同位置的兩個不同叢集上提供完全可用的資料複本，而且效能特性相同，如果需要，也不需要在各個站台之間擴充 SAN 。您可以讓應用程式同時在兩個站台上執行，以降低容錯移轉作業期間的整體 RTO 。

