---
sidebar: sidebar 
permalink: mssql/mssql-storage-efficiency.html 
keywords: MS-SQL,mssql,SQL Server 
summary: ONTAP 上的 Microsoft SQL Server 
---
= 使用 Microsoft SQL Server 實現 ONTAP 儲存效率
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
儲存效率是以消耗最少儲存空間的方式來儲存和管理 SQL Server 資料、對系統整體效能幾乎沒有影響或完全沒有影響。

儲存效率是 RAID 、資源配置（整體配置和使用率）、鏡像和其他資料保護技術的組合。NetApp 技術（例如 Snapshot 複本、精簡配置、 FlexClone ）可最佳化基礎架構中的現有儲存設備、並延後或避免未來的儲存支出、協助創造成本效益。這些技術搭配使用越多、節省的成本就越大。



== 資源隨需配置

精簡配置有多種形式、是 ONTAP 為企業應用程式環境提供的許多功能不可或缺的一部分。精簡配置也與效率技術密切相關、原因相同：效率功能可儲存比儲存系統技術更多的邏輯資料。

幾乎任何快照的使用都需要精簡配置。例如、 NetApp 儲存設備上的典型 10TB 資料庫、包含約 30 天的快照。這種配置可在作用中的檔案系統中看到大約 10TB 的資料、而在快照中則有 300TB 的資料。總儲存容量為 310TB 、通常位於大約 12TB 到 15TB 的空間上。作用中資料庫消耗 10TB 、而其餘 300TB 的資料僅需要 2TB 到 5TB 的空間、因為只會儲存對原始資料所做的變更。

複製也是精簡配置的範例。一位主要 NetApp 客戶建立 40 個 80 TB 資料庫的複本、供開發人員使用。如果使用這些複本的 40 位開發人員都在每個資料檔案中覆寫每個區塊、則需要超過 3.2PB 的儲存空間。實際上，週轉率較低，而且由於磁碟機上只儲存變更，因此集體空間需求接近 40 TB 。



== 空間管理

由於資料變更率可能會意外增加、因此精簡配置應用程式環境時必須謹慎處理。例如、如果資料庫資料表重新編製索引、或是將大規模的修補套用至 VMware 來賓系統、快照所造成的空間使用量就會迅速增加。錯誤的備份可能會在很短的時間內寫入大量資料。最後、如果檔案系統在非預期的情況下用盡可用空間、可能很難恢復某些應用程式。

幸運的是、這些風險可以透過仔細設定來解決 `volume-autogrow` 和 `snapshot-autodelete` 原則。如同其名稱所暗示、這些選項可讓使用者建立原則、以自動清除快照佔用的空間、或是增加磁碟區以容納額外資料。有許多選項可供選擇、需求因客戶而異。

請參閱 link:https://docs.netapp.com/us-en/ontap/volumes/index.html["邏輯儲存管理文件"] 以完整討論這些功能。



== LUN 精簡配置

在檔案系統環境中自動精簡配置作用中 LUN 的效率、可能會隨著資料刪除而隨時間而喪失。除非刪除的資料以零覆寫、或是以修剪 / 取消對應空間回收釋放空間、否則「清除的」資料會佔用檔案系統中越來越多的未分配空白。此外、在許多資料庫環境中、主動式 LUN 的精簡配置功能有限、因為資料檔案會在建立時初始化為全尺寸。

仔細規劃 LVM 組態可提高效率、並將儲存資源配置和 LUN 調整大小的需求降至最低。當使用 Veritas VxVM 或 Oracle ASM 等 LVM 時、基礎 LUN 會分割成僅在需要時才使用的範圍。例如、如果資料集的大小從 2TB 開始、但隨時間而成長至 10TB 、則此資料集可放置在配置在 LVM 磁碟群組中的 10TB 精簡配置 LUN 上。在建立時、它只會佔用 2TB 的空間、而且只會在分配範圍以容納資料成長時、才會要求額外的空間。只要監控空間、此程序就安全無虞。



== 部分保留

「部分保留」是指磁碟區中 LUN 在空間效率方面的行為。選項 `fractional-reserve` 設為 100% 、磁碟區中的所有資料在任何資料模式下都能達到 100% 的營業額、而不會耗盡磁碟區上的空間。

例如、假設資料庫位於 1TB 磁碟區中的單一 250GB LUN 上。建立快照將會立即在磁碟區中保留額外的 250GB 空間、以確保磁碟區不會因任何原因而用盡空間。使用分數保留通常是浪費、因為資料庫磁碟區中的每個位元組都不太可能需要覆寫。沒有理由為永遠不會發生的事件預留空間。不過、如果客戶無法監控儲存系統中的空間使用量、而且必須確定空間永遠不會用盡、則使用快照需要 100% 的部分保留。



== 壓縮與重複資料刪除

壓縮和重複資料刪除都是精簡配置的形式。例如、 50TB 的資料佔用空間可能會壓縮至 30TB 、因此可節省 20TB 。為了讓壓縮產生任何效益、其中某些 20TB 必須用於其他資料、或是儲存系統必須購買的容量低於 50TB 。因此、儲存的資料量比儲存系統技術上的資料量還多。從資料觀點來看、即使磁碟機僅佔用 30TB 、資料仍有 50TB 。

資料集的可壓縮性隨時都會變更、這會導致實際空間的使用量增加。這種使用量的增加意味著、在監控和使用方面、必須像其他形式的精簡配置一樣管理壓縮 `volume-autogrow` 和 `snapshot-autodelete`。

有關壓縮和重複資料刪除的詳細資訊、請參閱連結： efficiency.html 一節



=== 壓縮與部分保留

壓縮是一種精簡配置形式。部分保留會影響壓縮的使用、並附有一個重要附註；在建立快照之前、會保留空間。通常、只有存在快照時、部分保留才會很重要。如果沒有快照、則部分保留並不重要。這不是壓縮的情況。如果在具有壓縮功能的磁碟區上建立 LUN 、 ONTAP 會保留空間以容納快照。在組態期間、這種行為可能會令人困惑、但這是預期的。

舉例來說、請考慮使用 5GB LUN 的 10GB 磁碟區、該磁碟區已壓縮至 2.5GB 、但沒有快照。請考慮以下兩種情況：

* 分數保留 = 100 會導致 7.5 GB 使用率
* 部分保留量 =0 會導致使用率為 2.5GB


第一個案例包括目前資料使用 2.5 GB 的空間、以及 5 GB 的空間、可在預期使用快照時、讓來源的營業額達到 100% 。第二個案例不會保留額外空間。

雖然這種情況可能令人困惑、但實際上並不可能發生。壓縮意味著精簡配置、而 LUN 環境中的精簡配置則需要部分保留。壓縮資料永遠可以被無法壓縮的東西覆寫、這表示必須精簡配置磁碟區以進行壓縮、以節省任何成本。

[TIP]
====
* NetApp 建議 * 下列保留組態：

* 設定 `fractional-reserve` 與一起進行基本容量監控時為 0 `volume-autogrow` 和 `snapshot-autodelete`。
* 設定 `fractional-reserve` 如果沒有監控能力、或在任何情況下都無法排放空間、則達到 100 。


====


== 效率

空間效率功能（例如壓縮、壓縮和重複資料刪除）的設計、是為了增加符合特定實體儲存量的邏輯資料量。結果是降低成本和管理成本。

在高層級、壓縮是一種數學程序、可偵測及編碼資料模式、以減少空間需求。相反地、重複資料刪除功能會偵測實際重複的資料區塊、並移除額外的複本。資料實作可讓多個邏輯區塊在媒體上共用相同的實體區塊。


NOTE: 請參閱以下關於精簡配置的章節、以瞭解儲存效率與部分保留之間互動的說明。

SQL Server 也具備壓縮及有效管理資料的功能。SQL Server 目前支援兩種類型的資料壓縮：資料列壓縮和頁面壓縮。

資料列壓縮會變更資料儲存格式。例如、它會將整數和小數位數變更為可變長度格式、而非原生固定長度格式。它也會消除空白、將固定長度字元字串變更為可變長度格式。頁面壓縮會實作列壓縮及其他兩種壓縮策略（前置壓縮和字典壓縮）。您可以在中找到有關頁面壓縮的詳細資料 link:https://learn.microsoft.com/en-us/sql/relational-databases/data-compression/page-compression-implementation?view=sql-server-ver16&redirectedfrom=MSDN["頁面壓縮實作"^]。

SQL Server 2008 及更新版本的 Enterprise 、 Developer 及 Evaluation 版本目前支援資料壓縮。雖然壓縮可以由資料庫本身執行、但在 SQL Server 環境中很少會發生這種情況。

以下是管理 SQL Server 資料檔案空間的建議

* 在 SQL Server 環境中使用自動精簡配置、以提高空間使用率、並在使用空間保證功能時、降低整體儲存需求。
* 對於大多數常見的部署組態、請使用自動擴充、因為儲存管理員只需要監控集合體中的空間使用量。
* 建議不要在包含 SQL Server 資料檔案的任何磁碟區上啟用重複資料刪除功能、除非已知該磁碟區包含相同資料的多個複本、例如將資料庫從備份還原至單一磁碟區。




== 空間回收

空間回收可定期啟動、以恢復 LUN 中未使用的空間。有了 SnapCenter 、您可以使用下列 PowerShell 命令來啟動空間回收。

[listing]
----
Invoke-SdHostVolumeSpaceReclaim -Path drive_path
----
如果您需要執行空間回收、則此程序應在低活動期間執行、因為它最初會在主機上使用週期。
