---
sidebar: sidebar 
permalink: mssql/mssql-ag-snapcenter.html 
keywords: MSSQL,SQL Server, data protection, snapmirror, availability group 
summary: Microsoft SQL Server 可用度群組搭配 SnapCenter 
searchtitle: Microsoft SQL Server 可用度群組搭配 SnapCenter 
---
= SQL Server 可用度群組搭配 SnapCenter
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
SnapCenter 支援備份使用 Windows 容錯移轉叢集設定的 SQL Server 可用性群組資料庫。

Microsoft SQL Server 的 SnapCenter 外掛程式必須安裝在 Windows 伺服器容錯移轉叢集的所有節點上。請參閱link:https://docs.netapp.com/us-en/snapcenter/protect-scsql/concept_prerequisites_for_using_snapcenter_plug_in_for_microsoft_sql_server.html["文件"]先決條件和設定 SnapCenter 外掛程式的步驟。

SnapCenter 會探索 Windows 主機中的所有資料庫，執行個體和可用度群組，並在 SnapCenter 資源頁面上列舉資源。



=== 保護 Always On Availability 群組中的資料庫

可用度群組中的資料庫可透過多種方式受到保護。

* 資料庫層級備份：選取資料庫資源頁面的可用度資料庫，新增包含完整 / 記錄備份的原則，排程備份。無論資料庫角色是主要複本或次要複本， SnapCenter 都會進行備份。您也可以將資料庫新增至資源群組來設定保護。
* 執行個體層級備份：選取執行個體，並根據選取的原則保護執行個體上執行的所有資料庫。所有資料庫，包括執行為主要或次要複本的可用度資料庫，都會使用 SnapCenter 進行備份。也可以將執行個體新增至資源群組來設定保護。
* 可用度群組層級備份：在設定原則時， SnapCenter 有進階選項可用於可用性群組層級備份。原則中的可用性群組設定可讓使用者選取備份的複本喜好設定。您可以選取主要複本，次要複本或全部複本。預設選項是根據 SQL Server 可用性群組組組態中的備份複本集。


只有在使用可用性群組層級備份來保護可用性群組資料庫，且不適用於資料庫或執行個體層級備份時， SnapCenter 原則中的可用性群組設定才會套用。


TIP: * NetApp 建議 * 使用可用度層級備份，在 NetApp ONTAP 儲存設備上執行的所有複本之間進行備份。



=== 在 SnapCenter 中設定記錄備份

如果可用性群組是在獨立式 SQL Server 安裝程式上設定，則必須在 Windows 伺服器容錯移轉叢集的每個節點上掛載專用磁碟。應使用專用磁碟來設定記錄目錄，以儲存交易記錄備份。

如果在 SQL Server 容錯移轉叢集上設定可用性群組，則應在 SQL Server 容錯移轉叢集執行個體上建立叢集磁碟，以將其移轉至主機記錄目錄。



=== 使用 SnapCenter 還原可用度群組設定中的資料庫

* SnapCenter 提供重新植入選項，可從次複本可用的最新快照中自動恢復資料庫。重新連上的作業會自動還原，並將資料庫備份加入可用性群組。
* 在可用性群組中還原複本資料庫的另一種方法是中斷可用性群組並執行完整的完整和記錄還原。使用 SnapCenter 以 NORECOVERY 模式還原資料庫，然後使用 SQL Server Management Studio 或 T-SQL 將資料庫加入可用性群組。
* 若要只恢復資料子集，可以使用 SnapCenter 的複製功能來建立資料庫的複本。資料庫複本是使用 SnapCenter 在幾分鐘內建立，然後使用 SQL Server 原生工具將資料匯出至主要複本。


如需設定資料庫儲存配置以符合 RTO 和 RPO 需求的最佳實務做法link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf["TR-4714 使用 NetApp SnapCenter 的 Microsoft SQL Server 最佳實務做法"]，請參閱。


NOTE: SnapCenter 不支援分散式可用性群組和內含可用性群組。
