---
sidebar: sidebar 
permalink: mssql/mssql-workloads.html 
keywords: MS-SQL,mssql,SQL Server 
summary: ONTAP 上的 Microsoft SQL Server 
---
= Microsoft SQL Server 工作負載
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SQL Server 資料庫平台可以支援許多應用程式。

部署 SQL Server 之前、您必須先瞭解 SQL Server 執行個體所支援應用程式的資料庫工作負載需求。每個應用程式對於容量、效能和可用度的需求各不相同、因此每個資料庫都應該設計成能以最佳方式支援這些需求。許多組織會使用應用程式需求來定義 SLA 、將資料庫分類為多個管理層。SQL Server 工作負載的說明如下：

* OLTP 資料庫通常也是組織中最重要的資料庫。這些資料庫通常會支援面對客戶的應用程式、因此被視為是公司核心營運不可或缺的一環。關鍵任務 OLTP 資料庫及其支援的應用程式通常都有需要高效能的 SLA 、而且對效能降級和可用度很敏感。他們也可能是永遠在容錯移轉叢集或永遠在可用度群組的候選對象。這些類型資料庫的 I/O 組合通常以 75% 至 90% 隨機讀取和 25% 至 10% 寫入為特徵。
* 決策支援系統（ DSS ）資料庫也可稱為資料倉儲。這些資料庫在許多仰賴分析技術的企業中、都是關鍵任務。執行查詢時、這些資料庫會對 CPU 使用率和從磁碟讀取作業敏感。在許多組織中、 DSS 資料庫在月底、每季和每年都是最重要的此工作負載通常有 100% 的讀取 I/O 混合。




== 基準測試

交易程序委員會（ TPC ）是一家非營利組織、成立宗旨在於定義交易處理和資料庫基準、並將客觀且可驗證的 TPC 效能資料傳播給業界。TPC 測試會模擬完整的運算環境、其中有一群使用者會對資料庫執行交易。

[cols="1,1,1"]
|===
| 工作負載類型 | 案例 | 讀取 / 寫入比率（百分比） 


| OLTP | TPC-C | ~75/25 


|  | OLTP | TPC-E 


| 約 90/10 |  | DSS 


| TPC-H | ~100/0 |  
|===
雖然提供各種工作負載產生選項、但我們通常會專注於在處理交易工作負載時測量 SQL Server 資料庫的效能、我們也會使用 Microsoft 或 TPC-H 的 TPC-E 工具、使用 HammerDB （link:http://www.hammerdb.com/document.html["HammerDB.com"]^ ）。關於如何使用這些特定基準測試的詳細說明不在本文件的範圍之內。
