---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-sdrs.html 
keywords: Data protection, Space reclamation, VM and datastore cloning, Storage efficiency, thin provisioning, QoS, SIOC, Storage Distributed Resource Scheduler, DRS, Active IQ Unified Manager, Encryption 
summary: 利用此功能、您可以建立可套用至多個工作的備份原則。SnapCenter這些原則可定義排程、保留、複寫及其他功能。它們持續允許選用 VM 一致的快照、利用 Hypervisor 的能力來在拍攝 VMware 快照之前、先關閉 I/O 。 
---
= VMware Storage Distributed Resource Scheduler
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware Storage Distributed Resource Scheduler （ SDR ）是 vSphere 功能，可根據目前的 I/O 延遲和空間使用量，自動將 VM 放置在資料存放區叢集中。

接著、它會在資料存放區叢集中的資料存放區之間（也稱為Pod）、在不中斷營運的情況下移動VM或VMDK、並選取將VM或VMDK置於資料存放區叢集中的最佳資料存放區。資料存放區叢集是類似資料存放區的集合、從 vSphere 管理員的觀點來看、這些資料存放區會彙總成單一使用量單位。

搭配 ONTAP 工具使用適用於 VMware vSphere 的 SDR 時、您必須先使用外掛程式建立資料存放區、使用 vCenter 建立資料存放區叢集、然後將資料存放區新增至該叢集。建立資料存放區叢集之後、可直接從「詳細資料」頁面上的資源配置精靈、將其他資料存放區新增至資料存放區叢集。

SDR的ONTAP 其他最佳實務做法包括：

* 除非您有特定要求，否則請勿使用 SDR 。
+
** 使用 ONTAP 時不需要 SDR 。SDR 並不瞭解重複資料刪除和壓縮等 ONTAP 儲存效率功能，因此可能會做出不適合您環境的決策。
** SDR 不知道 ONTAP QoS 原則，因此可能會做出不適合效能的決策。
** SDR 不知道 ONTAP 快照複本，因此可能會做出決定，導致快照呈指數成長。例如，將 VM 移至另一個資料存放區會在新的資料存放區中建立新檔案，導致快照增加。對於擁有大型磁碟或許多快照的 VM 而言，這種情況尤其如此。然後，如果將 VM 移回原始資料存放區，原始資料存放區上的快照就會變得更大。




如果您確實使用 SDR ，請考慮下列最佳實務做法：

* 叢集中的所有資料存放區都應該使用相同類型的儲存設備（例如SAS、SATA或SSD）、無論是所有VMFS或NFS資料存放區、都具有相同的複寫和保護設定。
* 請考慮在預設（手動）模式下使用SDR。此方法可讓您檢閱建議、並決定是否要套用建議。請注意VMDK移轉的下列影響：
+
** 當 SDR 在資料存放區之間移動 VMDK 時， ONTAP 複製或重複資料刪除所節省的任何空間，可能會因其在目的地上刪除重複資料或壓縮的程度而有所降低。
** 在 SDR 移動 VMDK 之後、 NetApp 建議在來源資料存放區重新建立快照、因為其他情況下空間會被移動的 VM 鎖定。
** 在同一個集合體上的資料存放區之間移動VMDK並沒有什麼好處、而且SDR無法看到可能共用該集合體的其他工作負載。




有關 SDR 的詳細信息，請參閱 VMware 文檔，網址爲 https://knowledge.broadcom.com/external/article/320864/storage-drs-faq.html["Storage DRS 常見問題集"^]。
