---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-why.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: 客戶可以放心選擇 ONTAP for vSphere ，因為其統一化的 SAN 和 NAS 儲存解決方案，以及最新的 All SAN Array 中所採用的全新簡化的分散式儲存架構。此平台提供卓越的快照保護和強大的管理工具。ONTAP 將功能卸載至專用儲存設備，可將主機資源最大化，降低成本，並維持最佳效能。此外，使用 Storage VMotion 可在 VMFS ， NFS 或 vVols 之間輕鬆移轉工作負載。 
---
= 為何選擇 ONTAP for VMware vSphere ？
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
客戶可以放心地選擇ONTAP for vSphere 作為 SAN 和 NAS 儲存解決方案。最新的 All SAN 陣列採用了新的簡化分解儲存架構，為 SAN 儲存管理員提供了熟悉的簡化體驗，同時保留了傳統ONTAP系統的大部分整合和功能集。 ONTAP系統提供卓越的快照保護和強大的管理工具。透過將功能卸載到專用存儲， ONTAP可以最大限度地利用主機資源、降低成本並保持最佳效能。此外，可以使用 Storage vMotion 輕鬆跨 VMFS、NFS 或vVols遷移工作負載。



== 使用 ONTAP for vSphere 的優點

有許多理由讓成千上萬的客戶選擇 ONTAP 作為 vSphere 的儲存解決方案、例如支援 SAN 和 NAS 傳輸協定的統一儲存系統、使用節省空間的快照功能提供強大的資料保護功能、以及豐富的工具來協助您管理應用程式資料。使用與Hypervisor分開的儲存系統、您可以卸載許多功能、並將vSphere主機系統的投資效益最大化。這種方法不僅能確保主機資源專注於應用程式工作負載、也能避免儲存作業對應用程式造成隨機效能影響。

ONTAP與 vSphere 結合使用是一種很好的組合，可讓您減少主機硬體和 VMware 軟體的費用。您還可以以較低的成本保護您的數據，同時保持一致的高效能。由於虛擬化工作負載是移動的，您可以探索使用 Storage vMotion 的不同方法在同一儲存系統上跨 VMFS、NFS 或vVols資料儲存移動虛擬機器。

以下是當今客戶重視的關鍵因素：

* *統一儲存。 *運行ONTAP 的系統在幾個重要方面是統一的。最初，這種方法同時涉及 NAS 和 SAN 協議， ONTAP繼續成為 SAN 的領先平台，同時又具有 NAS 方面的原始優勢。在 vSphere 世界中，這種方法也意味著虛擬桌面基礎架構 (VDI) 與虛擬伺服器基礎架構 (VSI) 的統一系統。運行ONTAP 的系統對於 VSI 而言通常比傳統企業陣列更便宜，並且具有高級儲存效率功能，可在同一系統中處理 VDI。 ONTAP還統一了各種儲存介質，從 SSD 到 SATA，並且可以輕鬆擴展到雲端。沒有必要為了效能而購買一個儲存作業系統，為了歸檔而購買另一個，為了雲端而購買另一個。  ONTAP將它們全部連結在一起。
* * 所有 SAN 陣列（ ASA ） *最新的 ONTAP ASA 系統（從 A1K ， A90 ， A70 ， A50 ， A30 和 A20 開始）是以全新的儲存架構為基礎，消除了傳統的 ONTAP 儲存模式來管理集合體和磁碟區。由於沒有檔案系統共用，因此不需要磁碟區！連接至 HA 配對的所有儲存設備都會視為通用儲存可用區域（ SAZ ），其中 LUN 和 NVMe 命名空間會配置為「儲存單元」（ SUS ）。最新的 ASA 系統設計為易於管理，並為 SAN 儲存管理員提供熟悉的體驗。這種新架構非常適合 vSphere 環境，因為它能輕鬆管理儲存資源，並為 SAN 儲存管理員提供簡化的體驗。ASA 架構也支援最新的 NVMe over Fabrics （ NVMe of ）技術，為 vSphere 工作負載提供更高的效能和擴充性。
* * Snapshot 技術。 *ONTAP 是第一款提供資料保護快照技術的公司，也是業界最先進的公司。這種節省空間的資料保護方法已延伸至支援 VMware vSphere API for Array Integration （ VAAI ）。這項整合可讓您充分利用 ONTAP 的快照功能來執行備份與還原作業，進而降低對正式作業環境的影響。這種方法也可讓您使用快照來快速恢復 VM ，減少還原資料所需的時間與心力。此外， ONTAP 的快照技術也與 VMware 的即時網站恢復（ VLSR ，前身為 Site Recovery Manager [RSR] ）解決方案整合，為您的虛擬化環境提供全方位的資料保護策略。
* *虛擬捲和基於儲存策略的管理。 * NetApp是 VMware 在 vSphere Virtual Volumes (vVols) 開發方面的早期設計合作夥伴，為vVols和 VMware vSphere APIs for Storage Awareness (VASA) 提供架構輸入和早期支援。這種方法不僅為 VMFS 帶來了細粒度的 VM 儲存管理，還支援透過基於儲存策略的管理實現儲存配置的自動化。這種方法允許儲存架構師設計具有不同功能的儲存池，以便虛擬機器管理員輕鬆使用。  ONTAP在 vVol 規模方面處於儲存產業領先地位，在單一叢集中支援數十萬個vVols ，而企業陣列和小型快閃陣列供應商每個陣列僅支援數千個vVols 。  NetApp也透過即將推出的功能推動細粒度 VM 管理的發展。
* *儲存效率。 *儘管NetApp是第一個為生產工作負載提供重複資料刪除功能的公司，但這項創新並不是該領域的第一次或最後一次創新。它從快照開始，這是一種節省空間且不會影響效能的資料保護機制，同時結合FlexClone技術，可立即為生產和備份使用製作虛擬機器的讀取/寫入副本。  NetApp繼續提供內聯功能，包括重複資料刪除、壓縮和零區塊重複資料刪除，以從昂貴的 SSD 中榨取最多的儲存空間。 ONTAP還增加了使用壓縮將較小的 I/O 操作和檔案打包到磁碟區塊中的功能。這些功能的結合使得客戶普遍看到 VSI 節省高達 5:1，VDI 節省高達 30:1。最新一代ONTAP系統還包括硬體加速壓縮和重複資料刪除功能，可進一步提高儲存效率並降低成本。這種方法可讓您在更少的空間內儲存更多數據，從而降低整體儲存成本並提高效能。  NetApp對其儲存效率功能非常有信心，因此提供了一個連結： https://www.netapp.com/pdf.html?item=/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf item=/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf [效率保證^]。
* *多租戶* ONTAP長期以來一直是多租戶領域的領導者，可讓您在單一叢集上建立多個儲存虛擬機器 (SVM)。這種方法可讓您隔離工作負載並為不同的租戶提供不同等級的服務，使其成為服務提供者和大型企業的理想選擇。最新一代ONTAP系統還包括對租戶容量管理的支援。此功能可讓您為每個租用戶設定容量限制，確保沒有單一租用戶可以消耗所有可用資源。這種方法有助於確保所有租戶都能獲得他們期望的服務級別，同時也能在租戶之間提供高級別的安全性和隔離。此外，ONTAP 的多租戶功能與 VMware 的 vSphere 平台集成，讓您可以透過以下方式輕鬆管理和監控虛擬化環境 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["VMware vSphere適用的工具ONTAP"]和 https://docs.netapp.com/us-en/data-infrastructure-insights/["資料基礎架構洞見"]。
* *混合雲。 *無論用於本地私有雲、公有雲基礎架構或結合兩者優點的混合雲， ONTAP解決方案都可以協助您建置資料結構以簡化和最佳化資料管理。從高效能全快閃系統開始，然後將它們與磁碟或雲端儲存系統結合，以實現資料保護和雲端運算。從 Azure、AWS、IBM 或 Google Cloud 中選擇，以優化成本並避免鎖定。根據需要利用對 OpenStack 和容器技術的進階支援。  NetApp還為ONTAP提供基於雲端的備份（ SnapMirror Cloud、 Cloud Backup Service和Cloud Sync）以及儲存分層和歸檔工具（FabricPool ），以協助降低營運費用並利用雲端的廣泛覆蓋範圍。
* *及更多資訊。*善用NetApp AFF Sa系列陣列的極致效能、加速虛擬化基礎架構、同時管理成本。使用橫向擴充ONTAP 的叢集、享受完全不中斷營運的體驗、從維護到升級、到儲存系統的完整更換。使用NetApp加密功能保護閒置資料、無需額外成本。透過精細的服務品質功能、確保效能符合業務服務層級。它們都是業界領先的企業資料管理軟體 ONTAP 所提供的各種功能的一部分。

