---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-datastores-top.html 
keywords: vSphere, datastore, VMFS, FC, FCoE, NVMe/FC, iSCSI, NFS, vVols 
summary: 本頁說明在 VMware vSphere 環境中實作 ONTAP 儲存解決方案的最佳實務做法。 
---
= vSphere 資料存放區和傳輸協定功能概觀
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
使用七種傳輸協定將VMware vSphere連接至執行ONTAP VMware軟體的系統上的資料存放區：

* FCP
* FCoE
* NVMe / FC
* NVMe / TCP
* iSCSI
* NFS v3
* NFS v4.1


FCP、FCoE、NVMe/FC、NVMe/TCP和iSCSI是區塊傳輸協定、使用vSphere虛擬機器檔案系統（VMFS）將VM儲存在ONTAP 包含ONTAP FlexVol 在一個EesfVolume中的SesfLUN或NVMe命名空間內。請注意、從vSphere 7.0開始、VMware不再支援正式作業環境中的軟體FCoE。NFS是一種檔案傳輸協定、可將VM放入資料存放區（只是ONTAP 指不需要VMFS的功能）。SMB（CIFS）、iSCSI、NVMe / TCP或NFS也可直接從客體作業系統使用到ONTAP 不支援。

下表提供 vSphere 支援的傳統資料存放區功能與 ONTAP 。此資訊不適用於vVols資料存放區、但通常適用於使用支援ONTAP 的版本資訊的vSphere 6.x及更新版本。您也可以諮詢 https://www.vmware.com/support/pubs/["VMware 組態上限"^] 以確認特定vSphere版本的特定限制。

|===
| 功能/特色 | FC/FCoE | iSCSI | NVMe | NFS 


| 格式 | VMFS或原始裝置對應（RDM） | VMFS或RDM | VMFS | 不適用 


| 資料存放區或LUN的最大數量 | 每個主機有1024個LUN | 每個伺服器有1024個LUN | 每個伺服器256個Namespeces | 256 個掛載
預設 NFS 。最大磁碟區為8。使用VMware vSphere的VMware vSphere功能將其提升至256個。ONTAP 


| 最大資料存放區大小 | 64TB | 64TB | 64TB | 100TB FlexVol 以上的穩定區塊（含FlexGroup 不穩定區） 


| 最大資料存放區檔案大小 | 62TB | 62TB | 62TB | 62TB 、含 ONTAP 9.12.1P2 及更新版本 


| 每個LUN或檔案系統的最佳佇列深度 | 64-256 | 64-256 | 自動協商 | 請參閱中的NFS.MaxQuestue深度 link:vmware-vsphere-settings.html["建議的ESXi主機和其他ONTAP 功能設定"^]。 
|===
下表列出支援的VMware儲存相關功能。

|===
| 容量/功能 | FC/FCoE | iSCSI | NVMe | NFS 


| vMotion | 是的 | 是的 | 是的 | 是的 


| Storage VMotion | 是的 | 是的 | 是的 | 是的 


| VMware HA | 是的 | 是的 | 是的 | 是的 


| 儲存分散式資源排程器（SDR） | 是的 | 是的 | 是的 | 是的 


| 啟用資料保護（VADP）的VMware vStorage API備份軟體 | 是的 | 是的 | 是的 | 是的 


| VM內的Microsoft叢集服務（Microsoft Cluster Service、英文）或容錯移轉叢集 | 是的 | 是* | 是* | 不支援 


| 容錯能力 | 是的 | 是的 | 是的 | 是的 


| Site Recovery Manager | 是的 | 是的 | 否* | 僅適用於v3 * 


| 精簡配置的VM（虛擬磁碟） | 是的 | 是的 | 是的 | 是的
此設定是不使用 VAAI 時、 NFS 上所有 VM 的預設值。 


| VMware原生多重路徑 | 是的 | 是的 | 是、使用新的高效能外掛程式（HPP） | NFS v4.1 工作階段主幹需要 ONTAP 9.14.1 及更新版本 
|===
下表列出支援ONTAP 的功能不完整的儲存管理功能。

|===
| 功能/特色 | FC/FCoE | iSCSI | NVMe | NFS 


| 重複資料刪除技術 | 節省陣列成本 | 節省陣列成本 | 節省陣列成本 | 資料存放區的節約效益 


| 資源隨需配置 | 資料存放區或RDM | 資料存放區或RDM | 資料存放區 | 資料存放區 


| 調整資料存放區大小 | 僅成長 | 僅成長 | 僅成長 | 擴充、自動擴充及縮減 


| 適用於Windows、Linux應用程式（客體內）的列舉外掛程式SnapCenter | 是的 | 是的 | 否 | 是的 


| 使用ONTAP VMware vSphere的VMware VMware vSphere的支援工具來監控及主機組態 | 是的 | 是的 | 否 | 是的 


| 使用ONTAP VMware vSphere的VMware vSphere的VMware工具進行資源配置 | 是的 | 是的 | 否 | 是的 
|===
下表列出支援的備份功能。

|===
| 功能/特色 | FC/FCoE | iSCSI | NVMe | NFS 


| ONTAP 快照 | 是的 | 是的 | 是的 | 是的 


| SRM支援複寫備份 | 是的 | 是的 | 否* | 僅適用於v3 * 


| Volume SnapMirror | 是的 | 是的 | 是的 | 是的 


| VMDK映像存取 | 啟用VADP的備份軟體 | 啟用VADP的備份軟體 | 啟用VADP的備份軟體 | 啟用VADP的備份軟體、vSphere Client和vSphere Web Client資料存放區瀏覽器 


| VMDK檔案層級存取 | 啟用VADP的備份軟體、僅限Windows | 啟用VADP的備份軟體、僅限Windows | 啟用VADP的備份軟體、僅限Windows | 啟用VADP的備份軟體和協力廠商應用程式 


| NDMP精細度 | 資料存放區 | 資料存放區 | 資料存放區 | 資料存放區或 VM 
|===
* NetApp建議將來賓iSCSI用於Microsoft叢集、而非在VMFS資料存放區中使用支援多寫入器的VMDK。Microsoft和VMware完全支援這種方法、ONTAP 提供優異的靈活度搭配使用VMware（SnapMirror至ONTAP 內部部署或雲端的等化系統）、易於設定和自動化、SnapCenter 並可透過VMware加以保護。vSphere 7新增叢集式VMDK選項。這與啟用多寫入器的VMDK不同、因為VMDK需要透過FC傳輸協定呈現資料存放區、而且此傳輸協定已啟用叢集式VMDK支援。其他限制也適用。請參閱 VMware 的 https://docs.vmware.com/en/VMware-vSphere/7.0/vsphere-esxi-vcenter-server-70-setup-wsfc.pdf["Windows Server容錯移轉叢集的設定"^] 組態準則文件。

*使用NVMe與NFS v4.1的資料存放區需要vSphere複寫。SRM不支援陣列型複寫。



== 選擇儲存傳輸協定

執行ONTAP 支援所有主要儲存傳輸協定的系統、因此客戶可以根據現有和規劃的網路基礎架構和員工技能、選擇最適合自己環境的系統。NetApp測試通常顯示以類似線路速度執行的傳輸協定之間沒有什麼差異、因此最好將重點放在網路基礎架構和員工能力上、而不只是原始傳輸協定效能。

下列因素可能有助於考量選擇傳輸協定：

* *目前的客戶環境。*雖然IT團隊通常擅長管理乙太網路IP基礎架構、但並非所有人都擅長管理FC SAN架構。但是、使用非專為儲存流量設計的通用 IP 網路可能無法正常運作。請考量您所擁有的網路基礎架構、任何計畫性的改善、以及員工管理這些基礎架構的技能和可用度。
* *易於設定。*除了FC架構的初始組態設定（額外的交換器和纜線、分區、以及HBA和韌體的互通性驗證）之外、區塊傳輸協定也需要建立及對應LUN、以及由客體作業系統探索及格式化。NFS磁碟區建立及匯出之後、便會由ESXi主機掛載並準備好使用。NFS沒有特殊的硬體限制或韌體可管理。
* *易於管理。*有了SAN傳輸協定、如果需要更多空間、就必須採取幾個步驟、包括擴充LUN、重新掃描以探索新的大小、然後擴充檔案系統）。雖然可以擴充LUN、但減少LUN的大小並不可行、而且恢復未使用的空間可能需要額外的心力。NFS可輕鬆調整規模或縮減規模、儲存系統也能自動調整大小。SAN透過客體作業系統修剪/取消對應命令提供空間回收、讓刪除檔案的空間可以傳回陣列。NFS資料存放區的這類空間回收較為困難。
* *儲存空間的透明度。*在NFS環境中、儲存使用率通常比較容易查看、因為精簡配置可立即回收節約效益。同樣地、相同資料存放區中的其他VM或其他儲存系統磁碟區也可立即使用重複資料刪除和複製的節約效益。NFS資料存放區的VM密度通常也較高、可減少資料存放區的管理數量、進而改善重複資料刪除的節約效益、並降低管理成本。




== 資料存放區配置

可靈活建立VM和虛擬磁碟的資料存放區。ONTAP雖然ONTAP 使用VSC來配置vSphere的資料存放區時會套用許多功能不實的最佳實務做法（請參閱一節 link:vmware-vsphere-settings.html["建議的ESXi主機和其他ONTAP 功能設定"]）、以下是一些額外的考量準則：

* 部署vSphere搭配ONTAP 使用不間斷的NFS資料存放區、可實現高效能且易於管理的實作、提供VM對資料存放區的比率、而這些比率無法透過區塊型儲存傳輸協定取得。此架構可減少相關資料存放區數量、使資料存放區密度增加十倍。雖然較大的資料存放區可提升儲存效率並提供營運效益、但請考慮使用至少四個資料存放區FlexVol （VMware Volume）、將VM儲存在單ONTAP 一的VMware控制器上、以從硬體資源中獲得最大效能。此方法也可讓您建立具有不同恢復原則的資料存放區。根據業務需求、部分備份或複寫的頻率可能會比其他更高。由於資料存放區FlexGroup 是依設計進行擴充、因此不需要使用多個資料存放區來提升效能。
* NetApp 建議對大多數 NFS 資料存放區使用 FlexVol Volume 。從 ONTAP 9.8 FlexGroup 磁碟區開始、也支援作為資料存放區使用、一般建議在某些使用案例中使用。一般不建議使用其他 ONTAP 儲存容器、例如 qtree 、因為目前 VMware vSphere 的 ONTAP 工具或 VMware vSphere 的 NetApp SnapCenter 外掛程式都不支援這些容器。也就是說、將資料存放區部署為單一磁碟區中的多個 qtree 、對於高度自動化的環境來說可能很有用、因為資料存放區層級配額或 VM 檔案複本可以讓環境受益。
* 適用於不只FlexVol 4TB、更能滿足8TB的需求。這種規模對於效能、管理簡易性和資料保護來說、是一個很好的平衡點。從小規模開始（例如4TB）、視需要擴充資料存放區（最高100TB）。較小的資料存放區可更快從備份或災難後恢復、並可在叢集之間快速移動。請考慮使用ONTAP 不同步自動調整大小、以便在使用空間變更時自動擴充及縮小磁碟區。VMware vSphere資料存放區資源配置精靈的「VMware vSphere資料存放區資源配置精靈」預設會針對新的資料存放區使用自動調整大小。ONTAP您可以使用System Manager或命令列、進一步自訂「成長」和「縮減」臨界值、以及最大和最小大小。
* 此外、VMFS資料存放區也可以設定LUN、以供FC、iSCSI或FCoE存取。VMFS可讓叢集中的每個ESX伺服器同時存取傳統LUN。VMFS資料存放區的大小最多可達64TB、最多可包含32個2TB LUN（VMFS 3）或單一64TB LUN（VMFS 5）。大部分系統的LUN大小僅為16TB、ONTAP All SAN陣列系統的LUN大小上限為12TB。因此、在ONTAP 大多數的不實系統上、可使用四個16TB LUN來建立最大大小的VMFS 5資料存放區。雖然多個LUN的高I/O工作負載（使用高階FAS 的功能或AFF 功能性系統）可獲得效能優勢、但由於建立、管理及保護資料存放區LUN的管理複雜度增加、以及提高可用度風險、因此這項優勢已被抵銷。NetApp一般建議針對每個資料存放區使用單一大型LUN、而且只有在需要超越16TB資料存放區的情況下才需要跨距。與NFS一樣、請考慮使用多個資料存放區（Volume）、在單ONTAP 一的VMware控制器上發揮最大效能。
* 老舊的客體作業系統（OS）需要與儲存系統一致、才能獲得最佳效能和儲存效率。然而、Microsoft和Linux經銷商（例如Red Hat）所支援的現代化作業系統不再需要調整、以使檔案系統分割區與虛擬環境中基礎儲存系統的區塊保持一致。如果您使用的是可能需要調整的舊作業系統、請在NetApp支援知識庫中搜尋文章、使用「VM對齊」、或向NetApp銷售或合作夥伴聯絡人索取TR-3747的複本。
* 避免在來賓作業系統中使用重組公用程式、因為這不會帶來效能效益、也會影響儲存效率和快照空間使用量。也請考慮在客體作業系統中關閉虛擬桌面的搜尋索引。
* 以創新的儲存效率功能引領業界、讓您充分發揮可用磁碟空間的效益。ONTAP利用預設的即時重複資料刪除與壓縮技術、支援更高的效率。AFF資料會在集合體中的所有磁碟區中進行重複資料刪除、因此您不再需要將類似的作業系統和類似的應用程式群組在單一資料存放區中、以達到最大的節約效益。
* 在某些情況下、您甚至不需要資料存放區。為獲得最佳效能與管理能力、請避免將資料存放區用於高I/O應用程式、例如資料庫和某些應用程式。相反地、請考慮使用來賓擁有的檔案系統、例如NFS或iSCSI檔案系統、由來賓或RDM管理。如需特定的應用程式指南、請參閱適用於您應用程式的NetApp技術報告。例如、 link:../oracle/oracle-overview.html["Oracle資料庫ONTAP"] 提供虛擬化的相關章節、並提供實用的詳細資料。
* 一流磁碟（或改良的虛擬磁碟）可讓vCenter管理的磁碟獨立於vSphere 6.5及更新版本的VM。雖然主要是由API管理、但在vVols上也很實用、尤其是由OpenStack或Kubernetes工具管理時。支援的項目包括ONTAP VMware ONTAP vSphere的VMware vSphere的支援功能和VMware vSphere的支援功能。




== 資料存放區與VM移轉

將VM從另一個儲存系統上的現有資料存放區移轉至ONTAP 支援區時、請謹記以下幾項實務做法：

* 使用Storage VMotion將大部分虛擬機器移至ONTAP VMware。這種方法不僅不中斷虛ONTAP 擬機器的執行、還能讓諸如即時重複資料刪除和壓縮等儲存效率功能、在資料移轉時處理資料。請考慮使用vCenter功能從清單清單清單中選取多個VM、然後在適當的時間排程移轉（按一下「Actions」（動作）時使用Ctrl鍵）。
* 雖然您可以仔細規劃移轉至適當的目的地資料存放區、但通常較容易大量移轉、然後視需要組織。如果您有特定的資料保護需求、例如不同的 Snapshot 排程、您可能會想要使用此方法來引導您移轉至不同的資料存放區。
* 大多數VM及其儲存設備可能會在執行（Hot）時移轉、但從其他儲存系統移轉附加（非資料存放區）儲存設備（例如ISO、LUN或NFS磁碟區）可能需要冷移轉。
* 需要更謹慎移轉的虛擬機器包括使用附加儲存設備的資料庫和應用程式。一般而言、請考慮使用應用程式的工具來管理移轉。對於Oracle、請考慮使用Oracle工具（例如RMAN或ASM）來移轉資料庫檔案。請參閱 https://www.netapp.com/us/media/tr-4534.pdf["TR-4534"^] 以取得更多資訊。同樣地、對於SQL Server、請考慮使用SQL Server Management Studio或NetApp工具、例如SnapManager 適用於SQL Server或SnapCenter VMware。




== VMware vSphere適用的工具ONTAP

搭配執行ONTAP VMware vCenter軟體的系統使用vSphere時、最重要的最佳實務做法是安裝及使用ONTAP VMware vSphere外掛程式（前身為虛擬儲存主控台）的VMware VMware vSphere資訊工具。無論使用SAN或NAS、此vCenter外掛程式都能簡化儲存管理、提升可用度、並降低儲存成本和營運成本。它採用最佳實務做法來配置資料存放區、並針對多重路徑和HBA逾時最佳化ESXi主機設定（如附錄B所述）。由於它是 vCenter 外掛程式、因此可用於所有連線至 vCenter 伺服器的 vSphere Web 用戶端。

外掛程式也能協助您在ONTAP vSphere環境中使用其他的功能。它可讓您安裝適用於 VMware VAAI 的 NFS 外掛程式、以便將複本卸載至 ONTAP 進行虛擬機器複製作業、保留大型虛擬磁碟檔案的空間、以及 ONTAP 快照卸載。

外掛程式也是VASA Provider許多功能的管理介面、ONTAP 可支援vVols的儲存原則型管理。在登錄VMware vSphere的VMware vSphere基礎架構工具之後ONTAP 、請使用它來建立儲存功能設定檔、將其對應至儲存設備、並確保資料存放區在一段時間內符合設定檔的要求。VASA Provider也提供一個介面、可用來建立及管理VVol資料存放區。

一般而言、NetApp建議在ONTAP vCenter內使用VMware vSphere的VMware vCenter功能的VMware vCenter功能、來配置傳統和vVols資料存放區、以確保遵循最佳實務做法。



== 一般網路

使用vSphere搭配執行ONTAP VMware軟體的系統時、設定網路設定很簡單、而且類似於其他網路組態。以下是幾點需要考量的事項：

* 將儲存網路流量與其他網路區隔。使用專屬的VLAN或獨立的交換器來儲存、即可建立獨立的網路。如果儲存網路共用實體路徑（例如上行鏈路）、您可能需要QoS或額外的上行鏈路連接埠、以確保有足夠的頻寬。請勿將主機直接連線至儲存設備；請使用交換器來建立備援路徑、並讓 VMware HA 在不需介入的情況下運作。請參閱 link:vmware-vsphere-network.html["直接連線網路"] 以取得更多資訊。
* 如果您的網路需要並支援巨型框架、尤其是使用iSCSI時、可以使用巨型框架。如果使用、請確定在儲存設備和ESXi主機之間的路徑中、所有網路裝置、VLAN等上的設定都相同。否則、您可能會看到效能或連線問題。MTU也必須在ESXi虛擬交換器、VMkernel連接埠、以及每ONTAP 個節點的實體連接埠或介面群組上設定相同。
* NetApp僅建議停用ONTAP 叢集內叢集網路連接埠上的網路流量控制。對於用於資料流量的其餘網路連接埠、NetApp並未提出其他最佳實務做法建議。您應視需要啟用或停用。請參閱 http://www.netapp.com/us/media/tr-4182.pdf["TR-4182"^] 以取得流程控制的更多背景資訊。
* 當ESXi和ONTAP VMware ESXi儲存陣列連接至乙太網路儲存網路時、NetApp建議將這些系統連接的乙太網路連接埠設定為快速擴充樹狀傳輸協定（RSTP）邊緣連接埠、或使用Cisco PortFast功能。NetApp建議在使用Cisco PortFast功能的環境中、啟用跨距樹狀結構PortFast主幹功能、並在ESXi伺服器或ONTAP VMware®儲存陣列上啟用802.1Q VLAN主幹連線。
* NetApp建議下列連結集合最佳實務做法：
+
** 使用交換器、透過 Cisco 的 Virtual PortChannel （ VPC ）等多機箱連結集合群組方法、在兩個獨立的交換器機箱上支援連接埠的連結集合。
** 除非您使用已設定LACP的DVSwitches 5.1或更新版本、否則請停用連接至ESXi的交換器連接埠LACP。
** 使用 LACP 為具有連接埠或 IP 雜湊的動態多重模式介面群組的 ONTAP 儲存系統建立連結集合體。請參閱 https://docs.netapp.com/us-en/ontap/networking/combine_physical_ports_to_create_interface_groups.html#dynamic-multimode-interface-group["網路管理"^] 以取得進一步指引。
** 在 ESXi 上使用靜態連結集合（例如、 EtherChannel ）和標準 vSwitch 、或是搭配 vSphere Distributed Switch 使用 LACP 型連結集合時、請使用 IP 雜湊成組原則。如果未使用連結集合、請改用「根據來源虛擬連接埠 ID 建立路由」。




下表提供網路組態項目的摘要、並指出套用設定的位置。

|===
| 項目 | ESXi | 交換器 | 節點 | SVM 


| IP 位址 | VMkernel | 否* | 否* | 是的 


| 連結集合體 | 虛擬交換器 | 是的 | 是的 | 否* 


| VLAN | VMkernel和VM連接埠群組 | 是的 | 是的 | 否* 


| 流程控制 | NIC | 是的 | 是的 | 否* 


| 跨距樹狀結構 | 否 | 是的 | 否 | 否 


| MTU（用於巨型框架） | 虛擬交換器與VMkernel連接埠（9000） | 是（設為上限） | 有（9000） | 否* 


| 容錯移轉群組 | 否 | 否 | 是（建立） | 是（選取） 
|===
* SVM lifs連接到具有VLAN、MTU及其他設定的連接埠、介面群組或VLAN介面。不過、這些設定不會在SVM層級進行管理。

這些裝置擁有自己的IP位址進行管理、但這些位址並未用於ESXi儲存網路環境。
