---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-datastores-top.html 
keywords: vSphere, datastore, VMFS, FC, NVMe/FC, NVMe/TCP, iSCSI, NFS, vVols 
summary: 本頁說明在 VMware vSphere 環境中實作 ONTAP 儲存解決方案的最佳實務做法。 
---
= vSphere 資料存放區和傳輸協定功能概觀
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
六種通訊協定用於將 VMware vSphere 連接至執行 ONTAP 的系統上的資料存放區：

* FCP
* NVMe / FC
* NVMe / TCP
* iSCSI
* NFS v3
* NFS v4.1


FCP ， NVMe / FC ， NVMe / TCP 和 iSCSI 是區塊傳輸協定，使用 vSphere 虛擬機器檔案系統（ VMFS ）將 VM 儲存在 ONTAP FlexVol volume 中的 ONTAP LUN 或 NVMe 命名空間內。NFS是一種檔案傳輸協定、可將VM放入資料存放區（只是ONTAP 指不需要VMFS的功能）。SMB（CIFS）、iSCSI、NVMe / TCP或NFS也可直接從客體作業系統使用到ONTAP 不支援。

下表列出 vSphere 支援的傳統資料存放區功能與 ONTAP 。此資訊不適用於 vVols 資料存放區，但通常適用於使用受支援 ONTAP 版本的 vSphere 6.x 及更高版本。您也可以查閱 link:https://configmax.broadcom.com/guest?vmwareproduct=vSphere&release=vSphere%208.0&categories=2-0["VMware 組態最大值工具"^] 以取得特定 vSphere 版本的資訊，以確認特定限制。

|===
| 功能/特色 | FC | iSCSI | NVMe | NFS 


| 格式 | VMFS或原始裝置對應（RDM） | VMFS或RDM | VMFS | 不適用 


| 資料存放區或LUN的最大數量 | 每個 ESXi 主機 1024 個 LUN、每個 LUN 最多 32 個路徑、每個主機最多 4096 個路徑總數、每個資料存放區最多 128 個主機 | 每個 ESXi 主機 1024 個 LUN、每個 LUN 最多 32 個路徑、每個主機最多 4096 個路徑總數、每個資料存放區最多 128 個主機 | 每個 ESXi 主機 256 個命名空間、每個主機每個命名空間最多 32 個路徑、每個主機總共 2048 個路徑、每個資料存放區最多 16 個主機 | 每部主機 256 個 NFS 連線（受 nconnect 和工作階段主幹傳輸影響）預設 NFS 。最大磁碟區為8。使用VMware vSphere的VMware vSphere功能將其提升至256個。ONTAP 


| 最大資料存放區大小 | 64TB | 64TB | 64TB | 300TB FlexVol 以上的穩定區塊（含FlexGroup 不穩定區） 


| 最大資料存放區檔案大小 | 62TB | 62TB | 62TB | 62TB 、含 ONTAP 9.12.1P2 及更新版本 


| 每個LUN或檔案系統的最佳佇列深度 | 64-256 | 64-256 | 自動協商 | 請參閱中的NFS.MaxQuestue深度 link:vmware-vsphere-settings.html["建議的ESXi主機和其他ONTAP 功能設定"^]。 
|===
下表列出支援的VMware儲存相關功能。

|===
| 容量/功能 | FC | iSCSI | NVMe | NFS 


| vMotion | 是的 | 是的 | 是的 | 是的 


| Storage VMotion | 是的 | 是的 | 是的 | 是的 


| VMware HA | 是的 | 是的 | 是的 | 是的 


| 儲存分散式資源排程器（SDR） | 是的 | 是的 | 是的 | 是的 


| 啟用資料保護（ VADP ）的 VMware vStorage API 備份軟體 | 是的 | 是的 | 是的 | 是的 


| VM內的Microsoft叢集服務（Microsoft Cluster Service、英文）或容錯移轉叢集 | 是的 | 是 ^1^ | 是 ^1^ | 不支援 


| 容錯能力 | 是的 | 是的 | 是的 | 是的 


| 即時站台恢復 / 站台恢復管理程式 | 是的 | 是的 | 沒有 ^2^ | 僅 v3 ^2^ 


| 精簡配置的VM（虛擬磁碟） | 是的 | 是的 | 是的 | 是的
此設定是不使用 VAAI 時、 NFS 上所有 VM 的預設值。 


| VMware原生多重路徑 | 是的 | 是的 | 是的 | NFS v4.1 工作階段主幹需要 ONTAP 9.14.1 及更新版本 
|===
下表列出支援ONTAP 的功能不完整的儲存管理功能。

|===
| 功能/特色 | FC | iSCSI | NVMe | NFS 


| 重複資料刪除技術 | 節省陣列成本 | 節省陣列成本 | 節省陣列成本 | 資料存放區的節約效益 


| 資源隨需配置 | 資料存放區或RDM | 資料存放區或RDM | 資料存放區 | 資料存放區 


| 調整資料存放區大小 | 僅成長 | 僅成長 | 僅成長 | 擴充、自動擴充及縮減 


| 適用於Windows、Linux應用程式（客體內）的列舉外掛程式SnapCenter | 是的 | 是的 | 是的 | 是的 


| 使用ONTAP VMware vSphere的VMware VMware vSphere的支援工具來監控及主機組態 | 是的 | 是的 | 是的 | 是的 


| 使用ONTAP VMware vSphere的VMware vSphere的VMware工具進行資源配置 | 是的 | 是的 | 是的 | 是的 
|===
下表列出支援的備份功能。

|===
| 功能/特色 | FC | iSCSI | NVMe | NFS 


| ONTAP 快照 | 是的 | 是的 | 是的 | 是的 


| SRM支援複寫備份 | 是的 | 是的 | 沒有 ^2^ | 僅 v3 ^2^ 


| Volume SnapMirror | 是的 | 是的 | 是的 | 是的 


| VMDK映像存取 | 啟用 SnapCenter 和 VADP 的備份軟體 | 啟用 SnapCenter 和 VADP 的備份軟體 | 啟用 SnapCenter 和 VADP 的備份軟體 | 啟用 SnapCenter 和 VADP 的備份軟體， vSphere Client 和 vSphere Web Client 資料存放區瀏覽器 


| VMDK檔案層級存取 | SnapCenter 和 VADP 備份軟體，僅限 Windows | SnapCenter 和 VADP 備份軟體，僅限 Windows | SnapCenter 和 VADP 備份軟體，僅限 Windows | 啟用 SnapCenter 和 VADP 的備份軟體和協力廠商應用程式 


| NDMP精細度 | 資料存放區 | 資料存放區 | 資料存放區 | 資料存放區或 VM 
|===
^1^ *NetApp 建議*在 Microsoft 叢集中使用客體內 iSCSI，而不是在 VMFS 資料存放區中使用啟用多重寫入器的 VMDK。這種方法完全受 Microsoft 和 VMware 支援，與 ONTAP（SnapMirror 至內部部署或雲端的 ONTAP 系統）配合使用時具有極高的靈活性，易於配置和自動化，並且可以使用 SnapCenter 進行保護。vSphere 7 新增了一個叢集 VMDK 選項。這與啟用多重寫入器的 VMDK 不同，後者需要啟用叢集 VMDK 支援的 VMFS 6 資料存放區。其他限制也適用。如需組態指南，請參閱 VMware 的 link:https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/setup-for-windows-server-failover-clustering.html["Windows Server容錯移轉叢集的設定"^] 文件。

^2^ 使用 NVMe 的資料存放區和 NFS v4.1 需要 vSphere 複寫。SRM 目前不支援以陣列為基礎的 NFS v4.1 複寫。適用於 VMware vSphere 儲存複寫介面卡（）的 ONTAP 工具目前不支援 NVMe 型陣列複寫。



== 選擇儲存傳輸協定

執行 ONTAP 的系統支援所有主要儲存傳輸協定，因此客戶可以根據現有和規劃的網路基礎架構以及員工技能，選擇最適合其環境的傳輸協定。以往 NetApp 測試通常顯示，在類似的線路速度和連線數量下執行的傳輸協定之間差異不大。然而、NVMe-oF（NVMe/TCP 和 NVMe/FC）在 IOPS 方面顯示出顯著的提升、延遲降低、以及儲存 IO 的主機 CPU 使用量減少高達 50% 或更多。另一方面、NFS 提供最大的靈活性和易於管理性、尤其適用於大量 VM。所有這些傳輸協定都可以使用 ONTAP tools for VMware vSphere 進行使用和管理、該工具提供簡單的介面來建立和管理資料存放區。

下列因素可能有助於考量選擇傳輸協定：

* * 目前的作業環境。 *雖然 IT 團隊通常擅長管理乙太網路 IP 基礎架構，但並非所有團隊都擅長管理 FC SAN 架構。但是、使用非專為儲存流量設計的通用 IP 網路可能無法正常運作。請考量您所擁有的網路基礎架構、任何計畫性的改善、以及員工管理這些基礎架構的技能和可用度。
* *易於設定。*除了FC架構的初始組態設定（額外的交換器和纜線、分區、以及HBA和韌體的互通性驗證）之外、區塊傳輸協定也需要建立及對應LUN、以及由客體作業系統探索及格式化。NFS磁碟區建立及匯出之後、便會由ESXi主機掛載並準備好使用。NFS沒有特殊的硬體限制或韌體可管理。
* *易於管理*。使用 SAN 協定時，如果需要更多空間，則需要執行多個步驟，包括擴充 LUN、重新掃描以確定新的大小，然後擴充檔案系統。雖然可以擴充 LUN，但無法縮小 LUN。NFS 允許輕鬆地擴展或縮小大小，並且儲存系統可以自動執行此調整。SAN 提供透過客體作業系統 DEALLOCATE/TRIM/UNMAP 指令回收空間的功能，允許將已刪除檔案的空間返回陣列。NFS 資料儲存區不支援這種空間回收方式。
* *儲存空間的透明度。*在NFS環境中、儲存使用率通常比較容易查看、因為精簡配置可立即回收節約效益。同樣地、相同資料存放區中的其他VM或其他儲存系統磁碟區也可立即使用重複資料刪除和複製的節約效益。NFS資料存放區的VM密度通常也較高、可減少資料存放區的管理數量、進而改善重複資料刪除的節約效益、並降低管理成本。




== 資料存放區配置

可靈活建立VM和虛擬磁碟的資料存放區。ONTAP雖然在使用 ONTAP 工具為 vSphere 佈建資料存放區時會套用許多 ONTAP 最佳實務做法（列於一節link:vmware-vsphere-settings.html["建議的ESXi主機和其他ONTAP 功能設定"]），但以下是一些額外的準則可供考量：

* 使用 ONTAP NFS 資料存放區部署 vSphere 可實現高效能、易於管理的實作、並提供區塊型儲存傳輸協定無法達到的 VM 對資料存放區比率。此架構可將資料存放區密度提高十倍、同時相應減少資料存放區的數量。雖然較大的資料存放區可以提高儲存效率並帶來營運效益、但請考慮在單一 ONTAP 控制器上使用每個節點至少四個資料存放區（FlexVol 磁碟區）來儲存 VM、以充分發揮硬體資源的最大效能。此方法也可讓您建立具有不同還原原則的資料存放區。根據業務需求、某些資料存放區可以比其他資料存放區更頻繁地進行備份或複寫。FlexGroup 磁碟區不需要多個資料存放區來提升效能、因為它們在設計上具有擴充性。
* *NetApp 建議* 大多數 NFS 資料存放區使用 FlexVol 磁碟區。從 ONTAP 9.8 開始，也支援將 FlexGroup 磁碟區用作資料存放區，並且通常建議用於特定使用情境。其他 ONTAP 儲存容器，例如 qtrees，通常不建議使用，因為目前 ONTAP tools for VMware vSphere 或 NetApp SnapCenter plugin for VMware vSphere 都不支援這些容器。
* 適用於不只FlexVol 4TB、更能滿足8TB的需求。這種規模對於效能、管理簡易性和資料保護來說、是一個很好的平衡點。從小規模開始（例如4TB）、視需要擴充資料存放區（最高300TB）。較小的資料存放區可更快從備份或災難後恢復、並可在叢集之間快速移動。請考慮使用ONTAP 不同步自動調整大小、以便在使用空間變更時自動擴充及縮小磁碟區。VMware vSphere 資料存放區資源配置精靈的 ONTAP 工具預設會針對新的資料存放區使用自動調整大小。您可以使用System Manager或命令列、進一步自訂「成長」和「縮減」臨界值、以及最大和最小大小。
* 此外， VMFS 資料存放區也可以使用 LUN 或 NVMe 命名空間（在新的 ASA 系統中稱為儲存單元）進行設定，這些名稱空間可由 FC ， iSCSI ， NVMe / FC 或 NVMe / TCP 存取。VMFS 可讓叢集中的每個 ESX 伺服器同時存取資料存放區。VMFS資料存放區的大小最多可達64TB、最多可包含32個2TB LUN（VMFS 3）或單一64TB LUN（VMFS 5）。AFF ， ASA 和 FAS 系統上的 ONTAP 最大 LUN 大小為 128TB 。NetApp 一律建議為每個資料存放區使用單一大型 LUN ，而非嘗試使用擴充。與 NFS 一樣，請考慮使用多個資料存放區（磁碟區或儲存單元），在單一 ONTAP 控制器上發揮最大效能。
* 老舊的客體作業系統（OS）需要與儲存系統一致、才能獲得最佳效能和儲存效率。然而、Microsoft和Linux經銷商（例如Red Hat）所支援的現代化作業系統不再需要調整、以使檔案系統分割區與虛擬環境中基礎儲存系統的區塊保持一致。如果您使用的是需要調整的舊作業系統，請在 NetApp 支援知識庫中搜尋使用「 VM 調整」的文章，或是向 NetApp 銷售或合作夥伴聯絡人索取一份 TR-3747 複本。
* 避免在來賓作業系統中使用重組公用程式、因為這不會帶來效能效益、也會影響儲存效率和快照空間使用量。也請考慮在客體作業系統中關閉虛擬桌面的搜尋索引。
* 以創新的儲存效率功能引領業界、讓您充分發揮可用磁碟空間的效益。ONTAP利用預設的即時重複資料刪除與壓縮技術、支援更高的效率。AFF資料會在集合體中的所有磁碟區中進行重複資料刪除、因此您不再需要將類似的作業系統和類似的應用程式群組在單一資料存放區中、以達到最大的節約效益。
* 在某些情況下、您甚至不需要資料存放區。請考慮來賓擁有的檔案系統，例如 NFS ， SMB ， NVMe / TCP 或由來賓管理的 iSCSI 檔案系統。如需特定的應用程式指南、請參閱適用於您應用程式的NetApp技術報告。例如，link:../oracle/oracle-overview.html["Oracle資料庫ONTAP"]有一節關於虛擬化的內容，其中包含實用的詳細資料。
* 一流磁碟（或改良的虛擬磁碟）可讓vCenter管理的磁碟獨立於vSphere 6.5及更新版本的VM。雖然主要是由API管理、但在vVols上也很實用、尤其是由OpenStack或Kubernetes工具管理時。支援的項目包括ONTAP VMware ONTAP vSphere的VMware vSphere的支援功能和VMware vSphere的支援功能。




== 資料存放區與VM移轉

將VM從另一個儲存系統上的現有資料存放區移轉至ONTAP 支援區時、請謹記以下幾項實務做法：

* 使用Storage VMotion將大部分虛擬機器移至ONTAP VMware。這種方法不僅不中斷虛ONTAP 擬機器的執行、還能讓諸如即時重複資料刪除和壓縮等儲存效率功能、在資料移轉時處理資料。請考慮使用vCenter功能從清單清單清單中選取多個VM、然後在適當的時間排程移轉（按一下「Actions」（動作）時使用Ctrl鍵）。
* 雖然您可以精心規劃遷移到合適的目標資料存儲，但通常批量遷移更簡單，之後再根據需要進行組織。如果您有特定的資料保護需求（例如不同的 Snapshot 排程），則可以使用此方法來指導遷移到不同的資料儲存。此外，虛擬機一旦部署到 NetApp 叢集中，儲存 vMotion 就可以使用 VAAI 卸載功能在叢集上的資料儲存之間移動虛擬機，而無需在主機上進行複製。請注意，NFS 不會卸載已啟動虛擬機器的儲存 vMotion；但 VMFS 會。
* 需要更謹慎移轉的虛擬機器包括使用附加儲存設備的資料庫和應用程式。一般而言、請考慮使用應用程式的工具來管理移轉。對於Oracle、請考慮使用Oracle工具（例如RMAN或ASM）來移轉資料庫檔案。如需詳細資訊、請參閱 https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-migration-overview.html["將 Oracle 資料庫移轉至 ONTAP 儲存系統"^] 。同樣地、對於SQL Server、請考慮使用SQL Server Management Studio或NetApp工具、例如SnapManager 適用於SQL Server或SnapCenter VMware。




== VMware vSphere適用的工具ONTAP

在使用搭載 ONTAP 的系統與 vSphere 時，最重要的最佳實踐是安裝並使用 ONTAP tools for VMware vSphere 外掛程式（前稱 Virtual Storage Console）。這個 vCenter 外掛程式簡化了儲存管理、提升可用性，並降低儲存成本與營運負擔，無論是在 ASA、AFF、FAS，或甚至是 ONTAP Select（在 VMware 或 KVM VM 上執行的軟體定義版 ONTAP）上，使用 SAN 或 NAS 都適用。它會依照最佳實踐來配置資料存放區，並針對多路徑與 HBA 逾時優化 ESXi 主機設定（這些內容在附錄 B 中有說明）。由於它是 vCenter 外掛程式，所有連線至 vCenter 伺服器的 vSphere 網頁用戶端都能使用。

外掛程式也能協助您在ONTAP vSphere環境中使用其他的功能。它可讓您安裝適用於 VMware VAAI 的 NFS 外掛程式、以便將複本卸載至 ONTAP 進行虛擬機器複製作業、保留大型虛擬磁碟檔案的空間、以及 ONTAP 快照卸載。


NOTE: 對於基於映像的 vSphere 叢集，您仍然需要將 NFS Plug-In 新增至您的映像中，這樣在使用 ONTAP tools 安裝時就不會出現不合規的情況。

ONTAP 工具也是 VASA Provider for ONTAP 許多功能的管理介面，可支援以 vVols 為基礎的儲存原則管理。

一般而言， * NetApp 建議 * 在 vCenter 內使用 ONTAP 工具 for VMware vSphere 介面來配置傳統和 vVols 資料存放區，以確保遵循最佳實務做法。



== 一般網路

在執行 ONTAP 的系統上使用 vSphere 時設定網路設定非常簡單，與其他網路設定類似。以下是一些需要考慮的事項：

* 將儲存網路流量與其他網路區隔。使用專屬的VLAN或獨立的交換器來儲存、即可建立獨立的網路。如果儲存網路共用實體路徑（例如上行鏈路）、您可能需要QoS或額外的上行鏈路連接埠、以確保有足夠的頻寬。請勿將主機直接連線至儲存設備；請使用交換器來建立備援路徑、並讓 VMware HA 在不需介入的情況下運作。請參閱 link:vmware-vsphere-network.html["直接連線網路"] 以取得更多資訊。
* 如果您的網路需要並支援巨型框架、尤其是使用iSCSI時、可以使用巨型框架。如果使用、請確定在儲存設備和ESXi主機之間的路徑中、所有網路裝置、VLAN等上的設定都相同。否則、您可能會看到效能或連線問題。MTU也必須在ESXi虛擬交換器、VMkernel連接埠、以及每ONTAP 個節點的實體連接埠或介面群組上設定相同。
* NetApp 僅建議停用 ONTAP 叢集內叢集互連連接埠上的網路流程控制。對於用於資料流量的其餘網路連接埠、NetApp並未提出其他最佳實務做法建議。您應視需要啟用或停用。如需流程控制的更多背景資訊、請參閱 https://www.netapp.com/pdf.html?item=/media/16885-tr-4182pdf.pdf["TR-4182"^]。
* 當 ESXi 和 ONTAP 儲存陣列連線至乙太網路儲存網路時， * NetApp 建議 * 將這些系統連線的乙太網路連接埠設定為快速擴充樹協定（ RSTP ）邊緣連接埠，或使用 Cisco PortFast 功能。* NetApp 建議 * 在使用 Cisco PortFast 功能且啟用 802.1Q VLAN 主幹的環境中，啟用擴充樹 PortFast 主幹功能至 ESXi 伺服器或 ONTAP 儲存陣列。
* * NetApp 建議 * 下列連結集合的最佳實務做法：
+
** 使用支援鏈路聚合的交換器，透過多機箱鏈路聚合群組方法，將兩個獨立交換器機箱上的連接埠進行鏈路聚合，例如 Cisco 的 Virtual PortChannel（vPC）。
** 除非您使用已設定LACP的DVSwitches 5.1或更新版本、否則請停用連接至ESXi的交換器連接埠LACP。
** 使用 LACP 為具有連接埠或 IP 雜湊的動態多重模式介面群組的 ONTAP 儲存系統建立連結集合體。請參閱 https://docs.netapp.com/us-en/ontap/networking/combine_physical_ports_to_create_interface_groups.html#dynamic-multimode-interface-group["網路管理"^] 以取得進一步指引。
** 在 ESXi 上使用靜態連結集合（例如、 EtherChannel ）和標準 vSwitch 、或是搭配 vSphere Distributed Switch 使用 LACP 型連結集合時、請使用 IP 雜湊成組原則。如果未使用連結集合、請改用「根據來源虛擬連接埠 ID 建立路由」。



