---
sidebar: sidebar 
permalink: vmware/vmware-srm-overview.html 
keywords: ontap, vsphere, srm, srm, hybrid, cloud, migration, vmware, site, recovery manager, vsrm,VLSR 
summary: 適用於 VMware Live Site Recovery （ VSR ）和 Site Recovery Manager （ SRM ）的 ONTAP 解決方案 
---
= VMware Live Site Recovery with ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 自 2002 年推出現代化資料中心以來，一直是 VMware vSphere 和雲端基礎環境的主要儲存解決方案。它持續推出創新功能，可簡化管理並降低成本。

本文件介紹 VMware Live Site Recovery （ VLSR ）的 ONTAP 解決方案，先前稱為 Site Recovery Manager （ SRM ），這是 VMware 領先業界的災難恢復（ DR ）軟體，其中包括最新的產品資訊和最佳實務做法，可簡化部署，降低風險並簡化後續管理。


NOTE: 本文件取代先前發佈的技術報告 _TR-4900: VMware Site Recovery Manager with ONTAP

最佳實務做法是輔助其他文件、例如指南和相容性工具。這些技術是根據實驗室測試和NetApp工程師與客戶廣泛的現場經驗所開發。在某些情況下、建議的最佳實務做法可能不適合您的環境；不過、它們通常是最簡單的解決方案、能滿足大多數客戶的需求。

本文件著重於最新版 ONTAP 9 中的功能，這些功能搭配適用於 VMware vSphere 10.4 的 ONTAP 工具（包括 NetApp 儲存複寫介面卡 [SRA] 和 VASA 提供者 [VP] ），以及 VMware Live Site Recovery 9 。



== 為何要將 ONTAP 搭配 VSR 或 SRM 使用？

採用 ONTAP 技術的 NetApp 資料管理平台是 VLSR 最廣泛採用的儲存解決方案之一。理由十分豐富：安全、高效能、統一化的傳輸協定（ NAS 與 SAN 一起）資料管理平台、提供業界定義的儲存效率、多租戶、服務控制品質、節省空間的快照資料保護、以及使用 SnapMirror 進行複寫。所有這些工具都能運用原生混合式多雲端整合技術來保護VMware工作負載、並在彈指之間提供大量的自動化與協調工具。

當您使用 SnapMirror 進行陣列型複寫時、您將會充分利用 ONTAP 最成熟的技術之一。SnapMirror可讓您享有安全且高效率的資料傳輸優勢、只複製變更的檔案系統區塊、而非複製整個VM或資料存放區。即使是這些區塊、也能善用空間節約效益、例如重複資料刪除、壓縮及壓縮等。現代化ONTAP 的支援系統現在使用獨立於版本的SnapMirror、讓您能夠靈活選擇來源和目的地叢集。SnapMirror已真正成為最強大的災難恢復工具之一。

無論您使用傳統NFS、iSCSI或光纖通道附加資料存放區（現在支援vVols資料存放區）、VLSR都能提供強大的第一方產品、充分發揮ONTAP 災難恢復或資料中心移轉規劃與協調的最佳功能。



== VLSR如何運用ONTAP VMware®

VLSR利用ONTAP VMware ONTAP vSphere的進階資料管理技術與VMware vSphere的VMware vSphere工具整合、此虛擬應用裝置包含三個主要元件：

* ONTAP 工具 vCenter 外掛程式（前身為虛擬儲存主控台（ VSC ））可簡化儲存管理與效率功能，提升可用度，並降低儲存成本與營運成本，無論您使用的是 SAN 或 NAS 。它採用最佳實務做法來配置資料存放區、並針對NFS和區塊儲存環境最佳化ESXi主機設定。為了獲得所有這些優點、 NetApp 建議在搭配執行 ONTAP 的系統使用 vSphere 時使用此外掛程式。
* ONTAP 工具 VASA Provider 支援 VMware vStorage API for Storage Aware （ VASA ）架構。VASA Provider將vCenter Server與ONTAP VMware連線、以協助資源配置及監控VM儲存設備。這項功能可支援 VMware 虛擬磁碟區（ vVols ），並可管理 VM 儲存原則和個別 VM vVols 效能。它也提供監控容量和設定檔法規遵循的警示。
* SRA與VLSR搭配使用、可管理傳統VMFS與NFS資料存放區的正式作業與災難恢復站台之間的VM資料複寫、也可用於災難恢復複本的不中斷測試。它有助於自動化探索、還原及重新保護等工作。其中包括適用於 Windows SRM 伺服器的 SRA 伺服器應用裝置和 SRA 介面卡，以及 VSR 應用裝置。


在 VSR 伺服器上安裝並設定了用於保護非 VVols 資料存放區的 SRA 介面卡之後，您就可以開始設定 vSphere 環境以進行災難恢復。

SRA 為 VSR 伺服器提供命令與控制介面，可管理內含 VMware 虛擬機器（ VM ）的 ONTAP FlexVol 磁碟區，以及保護這些磁碟區的 SnapMirror 複寫。

VLSR 可以使用 NetApp 專屬的 FlexClone 技術、在不中斷營運的情況下測試您的災難恢復計畫、在災難恢復站台上為受保護的資料存放區建立近乎即時的複本。VLSR會建立沙箱以安全地進行測試、讓組織和客戶在發生真正災難時受到保護、讓您對組織在災難期間執行容錯移轉的能力充滿信心。

如果發生真正的災難、甚至是計畫性的移轉、VLSR可讓您透過最終的SnapMirror更新（如果您選擇這樣做）、將任何最後一分鐘的變更傳送至資料集。然後中斷鏡射、並將資料存放區掛載至DR主機。此時、您的VM可以根據預先規劃的策略、以任何順序自動開機。


NOTE: 雖然 ONTAP 系統可讓您將同一個叢集中的 SVM 配對，以進行 SnapMirror 複寫，但該案例並未通過 VLSR 的測試和認證。因此，建議您在使用 VLSR 時，僅使用不同叢集的 SVM 。



== VLSR搭配ONTAP 功能完善和其他使用案例：混合雲和移轉

與ONTAP 本地儲存選項相比、將VLSR部署與豐富的資料管理功能整合、可大幅提升擴充性與效能。除此之外、它還能帶來混合雲的靈活度。混合雲可將未使用的資料區塊從高效能陣列分層、到您偏好的超大規模擴充系統（FabricPool 例如NetApp Sirse-）、藉此節省成本StorageGRID 。您也可以使用 SnapMirror 搭配軟體定義的 ONTAP Select 或雲端型災難恢復（使用 Cloud Volumes ONTAP （ CVO ）或，或其他代管 ONTAP 服務），用於邊緣型系統 https://www.equinix.com/partners/netapp["Equinix Metal? 上的 NetApp 儲存設備"^]。

接著、您可以在雲端服務供應商的資料中心內執行測試容錯移轉、因為 FlexClone 的儲存佔用空間接近零。保護組織的成本現在比以往更低。

VLSR也可利用SnapMirror、將VM從一個資料中心有效地傳輸到另一個資料中心、甚至是同一個資料中心內、無論您是自己、或是透過任何數量的NetApp合作夥伴服務供應商、來執行計畫性的移轉作業。
