---
sidebar: sidebar 
permalink: vmware/vmware-srm-overview.html 
keywords: ontap, vsphere, srm, srm, hybrid, cloud, migration, vmware, site, recovery manager, vsrm,VLSR 
summary: 適用於 VMware Live Site Recovery （ VSR ）和 Site Recovery Manager （ SRM ）的 ONTAP 解決方案 
---
= VMware Live Site Recovery with ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
自從 ESX 在二十多年前引進現代化資料中心以來， ONTAP一直是 VMware vSphere 以及最近的 Cloud Foundation 的領先儲存解決方案。 NetApp持續推出創新系統，例如最新一代ASA A 系列，以及SnapMirror主動同步等功能。這些進步簡化了管理，增強了彈性，並降低了 IT 基礎架構的總擁有成本 (TCO)。

本文檔介紹了適用於 VMware Live Site Recovery (VLSR)（以前稱為 Site Recovery Manager (SRM)，VMware 業界領先的災難復原 (DR) 軟體）的ONTAP解決方案，包括最新產品資訊和最佳實踐，以簡化部署、降低風險並簡化持續管理。


NOTE: 本文檔取代了先前發布的技術報告《TR-4900：使用 ONTAP 的 VMware Site Recovery Manager》

最佳實務做法是輔助其他文件、例如指南和相容性工具。這些技術是根據實驗室測試和NetApp工程師與客戶廣泛的現場經驗所開發。在某些情況下、建議的最佳實務做法可能不適合您的環境；不過、它們通常是最簡單的解決方案、能滿足大多數客戶的需求。

本文件著重於最新版 ONTAP 9 中的功能，這些功能搭配適用於 VMware vSphere 10.4 的 ONTAP 工具（包括 NetApp 儲存複寫介面卡 [SRA] 和 VASA 提供者 [VP] ），以及 VMware Live Site Recovery 9 。



== 為何要將 ONTAP 搭配 VSR 或 SRM 使用？

由ONTAP提供支援的NetApp資料管理平台是 VLSR 最廣泛採用的儲存解決方案之一。原因有很多：一個安全、高效能、統一協議（NAS 和 SAN 結合）的資料管理平台，提供產業定義的儲存效率、多租戶、服務品質控制、使用空間高效快照的資料保護以及使用SnapMirror的複製。所有這些都利用原生混合多雲整合來保護 VMware 工作負載，並提供大量自動化和編排工具。

當您使用SnapMirror進行基於陣列的複製時，您可以利用 ONTAP 最成熟、最成熟的技術之一。 SnapMirror為您提供安全、高效的資料傳輸優勢，僅複製更改的檔案系統區塊，而不是整個虛擬機器或資料儲存區。即使這些區塊也利用了空間節省功能，例如重複資料刪除、壓縮和壓縮。現代ONTAP系統現在使用與版本無關的SnapMirror，讓您可以靈活地選擇來源叢集和目標叢集。  SnapMirror確實已成為最強大的災難復原工具之一。

無論您使用的是傳統的 NFS、iSCSI 或光纖通道連接的資料儲存（現在支援vVols資料儲存），VLSR 都能提供強大的第一方產品，利用ONTAP的最佳功能進行災難復原或資料中心遷移規劃和編排。



== VLSR如何運用ONTAP VMware®

VLSR利用ONTAP VMware ONTAP vSphere的進階資料管理技術與VMware vSphere的VMware vSphere工具整合、此虛擬應用裝置包含三個主要元件：

* ONTAP 工具 vCenter 外掛程式（前身為虛擬儲存主控台（ VSC ））可簡化儲存管理與效率功能，提升可用度，並降低儲存成本與營運成本，無論您使用的是 SAN 或 NAS 。它採用最佳實務做法來配置資料存放區、並針對NFS和區塊儲存環境最佳化ESXi主機設定。為了獲得所有這些優點、 NetApp 建議在搭配執行 ONTAP 的系統使用 vSphere 時使用此外掛程式。
* ONTAP 工具 VASA Provider 支援 VMware vStorage API for Storage Aware （ VASA ）架構。VASA Provider將vCenter Server與ONTAP VMware連線、以協助資源配置及監控VM儲存設備。這項功能可支援 VMware 虛擬磁碟區（ vVols ），並可管理 VM 儲存原則和個別 VM vVols 效能。它也提供監控容量和設定檔法規遵循的警示。
* SRA與VLSR搭配使用、可管理傳統VMFS與NFS資料存放區的正式作業與災難恢復站台之間的VM資料複寫、也可用於災難恢復複本的不中斷測試。它有助於自動化探索、還原及重新保護等工作。其中包括適用於 Windows SRM 伺服器的 SRA 伺服器應用裝置和 SRA 介面卡，以及 VSR 應用裝置。


在 VLSR 伺服器上安裝並設定 SRA 適配器以保護非 vVols 資料儲存區後，您可以開始設定 vSphere 環境以進行災難復原的任務。

SRA 為 VSR 伺服器提供命令與控制介面，可管理內含 VMware 虛擬機器（ VM ）的 ONTAP FlexVol 磁碟區，以及保護這些磁碟區的 SnapMirror 複寫。

VLSR 可以使用 NetApp 專有的FlexClone技術無中斷地測試您的 DR 計劃，以便在您的 DR 站點幾乎即時地克隆受保護的資料儲存。  VLSR 創建了一個沙箱來進行安全測試，以便在發生真正的災難時保護您的組織和客戶，讓您對組織在災難期間執行故障轉移的能力充滿信心。

如果發生真正的災難、甚至是計畫性的移轉、VLSR可讓您透過最終的SnapMirror更新（如果您選擇這樣做）、將任何最後一分鐘的變更傳送至資料集。然後中斷鏡射、並將資料存放區掛載至DR主機。此時、您的VM可以根據預先規劃的策略、以任何順序自動開機。


NOTE: 雖然 ONTAP 系統可讓您將同一個叢集中的 SVM 配對，以進行 SnapMirror 複寫，但該案例並未通過 VLSR 的測試和認證。因此，建議您在使用 VLSR 時，僅使用不同叢集的 SVM 。



== VLSR搭配ONTAP 功能完善和其他使用案例：混合雲和移轉

將 VLSR 部署與ONTAP高級資料管理功能相集成，與本地儲存選項相比，可大幅提高規模和效能。但更重要的是，它帶來了混合雲的靈活性。混合雲可讓您透過使用FabricPool將高效能陣列中未使用的資料塊分層到您首選的超大規模器（可以是本地 S3 存儲，例如NetApp StorageGRID ）來節省資金。您也可以將SnapMirror用於基於邊緣的系統，並使用軟體定義的ONTAP Select或基於雲端的 DR https://www.equinix.com/partners/netapp["Equinix Metal 上的NetApp存儲"^]或其他託管ONTAP服務。

接著、您可以在雲端服務供應商的資料中心內執行測試容錯移轉、因為 FlexClone 的儲存佔用空間接近零。保護組織的成本現在比以往更低。

VLSR也可利用SnapMirror、將VM從一個資料中心有效地傳輸到另一個資料中心、甚至是同一個資料中心內、無論您是自己、或是透過任何數量的NetApp合作夥伴服務供應商、來執行計畫性的移轉作業。
