---
sidebar: sidebar 
permalink: vmware/vmware-security-snapcenter.html 
keywords: WP-7355, security, snapcenter, treat modeling, dast, vulnerability scanning, penetration testing,SCV,VMware,vSphere 
summary: 本文件說明適用於 VMware 的 SnapCenter 外掛程式的安全性層面。 
---
= SnapCenter 外掛程式 VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
適用於VMware vSphere軟體工程的NetApp SnapCenter 支援外掛程式使用下列安全開發活動：

* *威脅建模。*威脅建模的目的是在軟體開發生命週期初期、發現某項功能、元件或產品的安全性瑕疵。威脅模式是對影響應用程式安全性的所有資訊的結構化呈現。基本上、它是透過安全性觀點來檢視應用程式及其環境。
* *動態應用程式安全性測試（dast）。*專為偵測應用程式執行狀態中的易受影響狀況而設計的技術。Dast會測試開放Web應用程式的公開HTTP和HTML介面。
* *協力廠商程式碼貨幣。*在開發軟體及使用開放原始碼軟體（開放原始碼軟體）的過程中、必須解決與產品整合的開放原始碼軟體（開放原始碼軟體）相關的安全性弱點。這是一項持續努力、因為開放源碼軟體會元件的版本可能隨時報告新發現的弱點。
* *弱點掃描。*弱點掃描的目的是在NetApp產品中發現常見且已知的安全性弱點之後、再將弱點發佈給客戶。
* *滲透測試。*滲透測試是評估系統、Web應用程式或網路以找出攻擊者可能利用的安全性弱點的程序。NetApp的滲透測試（筆測試）是由一群獲核准且值得信賴的第三方公司進行。其測試範圍包括利用精密的利用方法或工具、對惡意入侵者或駭客等應用程式或軟體發動攻擊。
* * 產品安全性事件回應活動。 * 公司內部和外部都發現安全性弱點、如果未及時解決、可能會對 NetApp 的聲譽造成嚴重風險。為了推動此程序、產品安全性事件回應團隊（PSIRT）會報告並追蹤弱點。




== 產品安全功能

適用於VMware vSphere的NetApp SnapCenter VMware vCenter外掛程式在每個版本中都包含下列安全功能：

* *受限的Shell存取。* SSH預設為停用、且只有在從VM主控台啟用時、才允許一次性登入。
* *登入橫幅中的存取警告。*使用者在登入提示中輸入使用者名稱後、會顯示下列登入橫幅：
+
*警告：*禁止未經授權存取本系統、並依法律予以起訴。存取本系統即表示您同意、若懷疑有未獲授權的使用情形、您的行動可能受到監控。

+
使用者透過SSH通道完成登入後、會顯示下列輸出：



....
Linux vsc1 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64
The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
....
* *角色型存取控制（RBAC）。* ONTAP 有兩種RBAC控制項與VMware Tools相關聯：
+
** 原生vCenter Server權限。
** VMware vCenter外掛程式特定權限。如需詳細資訊、請參閱 https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_role_based_access_control.html["角色型存取控制（RBAC）"^]。


* *加密的通訊通道。*所有外部通訊都是使用TLS透過HTTPS進行。
* *最小的連接埠曝光。*只有必要的連接埠會在防火牆上開啟。


下表提供開放連接埠詳細資料。

|===
| TCP v4/v6連接埠號碼 | 功能 


| 8144. | 用於REST API的HTTPS連線 


| 8080 | 用於OVA GUI的HTTPS連線 


| 22 | SSH（預設為停用） 


| 3306. | MySQL（僅限內部連線；預設為停用外部連線） 


| 443.. | Ngin像（資料保護服務） 
|===
* *支援憑證授權單位（CA）簽署的憑證。* SnapCenter VMware vSphere的支援外掛程式支援CA簽署憑證的功能。請參閱 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_create_and_or_import_an_SSL_certificate_to_SnapCenter_Plug-in_for_VMware_vSphere["如何建立及/或將SSL憑證匯入SnapCenter VMware vSphere（選擇控制器）的VMware外掛程式"^]。
* *密碼原則。*下列密碼原則有效：
+
** 密碼不會記錄在任何記錄檔中。
** 密碼不會以純文字形式傳達。
** 密碼是在安裝程序本身期間設定的。
** 所有認證資訊均使用SHA256雜湊來儲存。


* *基本作業系統映像*。*本產品隨附適用於OVA的Debian基礎作業系統、存取受限且停用Shell存取。如此可減少攻擊佔用空間。每SnapCenter 個發行版基礎作業系統都會更新最新的安全修補程式、以達到最大的安全覆蓋範圍。


NetApp針對SnapCenter VMware vSphere應用裝置開發有關VMware vSphere外掛程式的軟體功能與安全性修補程式、然後將其作為套裝軟體平台發佈給客戶。由於這些應用裝置包括特定的Linux子作業系統相依性、以及我們的專屬軟體、因此NetApp建議您不要變更子作業系統、因為這會對NetApp應用裝置造成重大影響。這可能會影響NetApp支援應用裝置的能力。NetApp建議測試及部署我們最新的應用裝置程式碼版本、因為這些版本已發行以修補任何與安全性相關的問題。
