---
sidebar: sidebar 
permalink: vmware/vmware-srm-vvol-troubleshooting.html 
keywords: vmware, site, recovery manager, vsrm, hybrid, cloud, srm, vvols, replication 
summary: 與 SRA 和傳統資料存放區相比、 VVols 複寫搭配 VASA 提供獨特的功能。 
---
= 使用vVols複寫時疑難排解SRM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
使用vVols複寫時、SRM內部的工作流程與SRA和傳統資料存放區使用的工作流程大不相同。例如、沒有Array Manager概念。因此、 `discoverarrays` 和 `discoverdevices` 從未見過命令。

疑難排解時、瞭解下列新工作流程會有所助益：

. 查詢複製對等方：探索兩個故障網域之間的複寫合約。
. 查詢FaultDomain：探索故障網域階層。
. 查詢複製群組：探索來源或目標網域中的複寫群組。
. SyncReplicationGroup：在來源與目標之間同步資料。
. 查詢點時間複本：探索目標上的時間點複本。
. testFailoverReplicationGroupStart：開始測試容錯移轉。
. testFailoverReplicationGroupStop：結束測試容錯移轉。
. 促銷複製群組：將目前正在測試的群組推廣至正式作業。
. PrepareFailoverReplicationGroup：準備災難恢復。
. 容錯移轉複製群組：執行災難恢復。
. 混響複寫群組：啟動反轉複寫。
. queryMatchingContainer：尋找容器（連同主機或複寫群組）、以特定原則來滿足資源配置要求。
. 查詢資源中繼資料：從VASA提供者探索所有資源的中繼資料、可傳回資源使用率做為查詢配對Container功能的答案。


設定vVols複寫時最常見的錯誤是無法發現SnapMirror關係。這是因為磁碟區和SnapMirror關係是在ONTAP 不屬於「需求工具」範圍的情況下建立。因此、最佳實務做法是在ONTAP 嘗試建立複寫的vVols資料存放區之前、務必確認SnapMirror關係已完全初始化、並在兩個站台上執行「ReDiscovery工具」中的重新探索。
