---
sidebar: sidebar 
permalink: vmware/vmware-srm-deployment_best_practices.html 
keywords: vmware, site, recovery manager, vsrm, svm, layout, segmentation, smt, best, practices, deploy, ontap, tools, vvols, srm, vlsr 
summary: 利用NetApp技術、儲存虛擬機器（SVM）的概念可在安全的多租戶環境中提供嚴格的區隔。ONTAP 
---
= 部署最佳實務做法
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
以下各節概述 ONTAP 和 VMware SRM 的部署最佳實務做法。



== 使用最新版的 ONTAP 工具 10

ONTAP 工具 10 比舊版大幅改善，包括：

* 測試容錯移轉速度加快 8 倍 *
* 清理與重新保護速度加快 2 倍 *
* 故障切換速度加快 32%*
* 擴充性更高
* 原生支援共用網站配置


這些改進是根據內部測試而定，可能會因您的環境而有所不同。



== 適用於SMT的SVM配置與區隔

利用NetApp技術、儲存虛擬機器（SVM）的概念可在安全的多租戶環境中提供嚴格的區隔。ONTAP某個SVM上的SVM使用者無法從另一個SVM存取或管理資源。如此一ONTAP 來、您就能為不同的業務單位建立獨立的SVM、以便在同一個叢集上管理自己的SRM工作流程、進而提升整體儲存效率、進而充分運用此項技術。

考慮ONTAP 使用SVM範圍的帳戶和SVM管理生命體來管理功能、不僅能改善安全控管、也能提升效能。使用SVM範圍的連線時、效能自然會更高、因為SRA不需要處理整個叢集中的所有資源、包括實體資源。而是只需要瞭解抽象化至特定SVM的邏輯資產。



== 管理ONTAP 功能的最佳實務做法

如前所述、您可以ONTAP 使用叢集或SVM範圍內的認證和管理生命體來管理等叢集。為了達到最佳效能、您可能想要在不使用 vVols 時、考慮使用 SVM 範圍的認證。不過、在這樣做的過程中、您應該瞭解某些需求、而且您確實會失去某些功能。

* 預設的vsadmin SVM帳戶沒有執行ONTAP 各項功能工作所需的存取層級。因此，您需要建立新的 SVM 帳戶。 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/configure-user-role-and-privileges.html["設定 ONTAP 使用者角色和權限"]使用隨附的 JSON 檔案。這可用於SVM或叢集範圍內的帳戶。
* 由於 vCenter UI 外掛程式， VASA Provider 和 SRA 伺服器都是完全整合的微服務，因此您必須將儲存設備新增至 SRM 中的介面卡，方法與在 vCenter UI for ONTAP 工具中新增儲存設備的方式相同。否則、SRA伺服器可能無法辨識透過SRA介面卡從SRM傳送的要求。
* 使用 SVM 範圍的認證時不會執行 NFS 路徑檢查，除非您先 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["內建叢集"]在 ONTAP 工具管理程式中，並將其與 vCenter 相關聯。這是因為實體位置從SVM邏輯上抽象化。不過這並不是令人擔心的問題、因為使用ONTAP 間接路徑時、現代的功能不再受到明顯的效能下降影響。
* 可能不會報告儲存效率所節省的Aggregate空間。
* 在支援的情況下、無法更新負載共用鏡像。
* 可能無法在ONTAP 以SVM範圍認證來管理的各種系統上執行EMS記錄。

