---
sidebar: sidebar 
permalink: vmware/vsphere/flexgroups.html 
keywords: vSphere, datastore, VMFS, FC, FCoE, NVMe/FC, iSCSI, NFS, vVols 
summary: 本頁說明在ONTAP VMware vSphere環境中實作NetApp解決方案的最佳實務做法。 
---
= FlexGroups
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
支援vSphere中的VMware vSphere資料存放區、以及VMware vSphere 9.8版的VMware vCenter工具。ONTAP FlexGroup ONTAP

此功能可簡化大型資料存放區的建立作業、並自動建立多個組成磁碟區、以發揮整個系統的最大效能。FlexGroup ONTAP利用vSphere的功能將VMware支援功能用於單一、可擴充的vSphere資料存放區、並具備完整的VMware叢集功能。FlexGroup ONTAP

除了針對vSphere工作負載進行廣泛的系統測試之外、ONTAP 還為FlexGroup VMware資料存放區新增了複本卸載機制。這會使用改良的複製引擎、在背景中的成員之間複製檔案、同時允許存取來源和目的地。根據規模、當需要時、多個複本會使用可立即使用且節省空間的檔案複本。

此外、針對VMware vSphere儀表板和VM報告、還新增檔案型效能指標（IOPS、處理量和延遲）、這些指標可在VMware vSphere儀表板和VM報告的「參考」工具中檢視。ONTAP FlexGroup ONTAPVMware vSphere外掛程式的支援功能也可讓您使用最大和/或最小IOPS的組合來設定服務品質（QoS）規則。ONTAP這些設定可以跨資料存放區中的所有VM進行設定、也可以針對特定VM個別設定。

以下是NetApp開發的其他一些最佳實務做法：

* 使用FlexGroup 預設的資源配置。建議使用VMware vSphere的VMware vSphere功能、因為它能在vSphere中建立及掛載功能、但可能會使用VMware System Manager或命令列來滿足特殊需求。ONTAP FlexGroup ONTAP即使如此、仍會使用預設值、例如每個節點的組成成員數目、因為這是vSphere測試過的項目。
* 調整FlexGroup VMware資料存放區規模時、請記住FlexGroup 、此功能包含FlexVol 多個較小的、可建立較大命名空間的支援區。因此、請將資料存放區的大小調整為最大虛擬機器的8倍以上。例如、如果您的環境中有6TB的VM、FlexGroup 請將該資料存放區的大小調整至不小於48TB。
* 允許FlexGroup 執行功能以管理資料存放區空間。vSphere資料存放區已測試過自動調整規模與彈性調整。如果資料存放區接近完整容量、請使用ONTAP VMware vSphere的VMware vCenter功能或其他工具來調整FlexGroup VMware Volume的大小。如果容量允許、則可將資料夾（VM）內的檔案優先順序設定為相同的組成要素、藉此平衡各成員的容量和inode。FlexGroup
* VMware與NetApp目前不支援通用的多重路徑網路方法。對於NFSv4.1、NetApp支援pNFS、而VMware則支援工作階段主幹連線。NFSv3不支援多個實體路徑通往磁碟區。針對使用VMware vSphere的VMware 9.8、我們建議的最佳實務做法是讓VMware vSphere的VMware vSphere使用VMware vSphere的VMware Tools進行單一掛載、因為間接存取的影響通常很小（微秒）FlexGroup ONTAP ONTAP 。您可以使用循環 DNS 、在 FlexGroup 的不同節點上、將 ESXi 主機分散到不同的動態層級、但這需要在沒有適用於 VMware vSphere 的 ONTAP 工具的情況下、建立和掛載 FlexGroup 。因此效能管理功能將無法使用。
* vSphere資料存放區支援已在9.8版中測試高達1500部VM。FlexGroup
* 使用適用於VMware VAAI的NFS外掛程式進行複本卸載。請注意FlexGroup 、ONTAP 雖然在VMware資料存放區內強化複製功能、但在FlexVol 將VM複製到VMware和/或FlexGroup VMware磁碟區之間時、與ESXi主機複本相比、VMware不提供顯著的效能優勢。
* 使用VMware vSphere 9.8的支援功能、使用VMware vSphere 9.8的支援指標（儀表板和VM報告）來監控各個VM的效能、以及管理個別VM上的QoS。ONTAP FlexGroup ONTAP目前無法透過ONTAP REST指令或API取得這些指標。
* QoS（最大/最小IOPS）可在個別VM或資料存放區中的所有VM上設定。在所有VM上設定QoS會取代任何個別VM設定。設定未來不會延伸至新的或移轉的VM；您可以在新的VM上設定QoS、或是將QoS重新套用至資料存放區中的所有VM。
* VMware vSphere 4.4版的支援VMware vSphere的子外掛程式、可在主儲存系統的VMware資料存放區中備份及還原VM。SnapCenter FlexGroup雖然SnapMirror可手動用於將FlexGroup 某個不間斷資料複製到二線系統、但4號選擇控制閥並不會管理二線複本。

