---
sidebar: sidebar 
permalink: vmware/vsphere/settings.html 
keywords:  
summary:  
---
= 建議的ESXi主機和其他ONTAP 功能設定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
NetApp已開發出一套ESXi主機多重路徑和HBA逾時設定、可根據ONTAP NetApp測試、以正確的方式執行功能。使用ONTAP VMware vSphere的VMware VMware vSphere的VMware VMware Infrastructure可輕鬆設定這些功能。在「摘要」儀表板中、按一下「主機系統」入口小程式中的「編輯設定」、或在vCenter中的主機上按一下滑鼠右鍵、然後瀏覽ONTAP 至「VMware工具」>「設定建議值」。以下是9.8版目前建議的主機設定。

|===


| *主機設定* | * NetApp推薦價值* | *需要重新開機* 


3+| * ESXi進階組態* 


| VMFS3.HardwareAcceleratedLocking | 保留預設值（ 1 ） | 否 


| VMFS3.EnablBlockDelete | 保留預設值（ 0 ）、但可視需要進行變更。
如需詳細資訊、請參閱 link:https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2007427["VMware KB 2007427"] | 否 


| VMFS3.EnableVMFS6 取消對應 | 保留預設值（ 1 ）
如需詳細資訊、請參閱 link:https://core.vmware.com/resource/vmware-vsphere-apis-array-integration-vaai#sec9426-sub4["VMware vSphere API ：陣列整合（ VAAI ）"] | 否 


3+| * NFS 設定 * 


| net.TcpipHeapSize. | vSphere 6.0或更新版本、設定為32。
所有其他NFS組態、設定為30 | 是的 


| net.TcpipHeapMax | 大多數vSphere 6.x版本的設定為512MB。
若為6.5U3、6.7U3及7.0或更新版本、則設為1024MB。 | 是的 


| NFS.MaxVolumes | vSphere 6.0 或更新版本、設定為 256
所有其他 NFS 組態、設為 64 。 | 否 


| NFS41.MaxVolumes | vSphere 6.0 或更新版本、設定為 256 。 | 否 


| NFS.MaxQuesteepeth1^ | vSphere 6.0或更新版本、設定為128 | 是的 


| NFS.HeartbeatMaxFailures | 所有NFS組態皆設為10 | 否 


| NFS.Heartbeat頻率 | 針對所有 NFS 組態設定為 12 | 否 


| NFS.Heartbeattimeout | 針對所有 NFS 組態設定為 5 。 | 否 


| SUNPC。MaxConnPerIP | vSphere 7.0 或更新版本、設定為 128 。 | 否 


3+| * FC/FCoE設定* 


| 路徑選擇原則 | 使用具有ALUA的FC路徑時、設定為RR（循環配置資源）。所有其他組態皆設為「固定」。
將此值設為RR有助於在所有主動/最佳化路徑之間提供負載平衡。
固定值適用於舊版非ALUA組態、有助於防止Proxy I/O換句話說、它有助於在Data ONTAP 以7-Mode運作的環境中、讓I/O不再移至高可用度（HA）配對的其他節點 | 否 


| disk.QFullSampleSize. | 所有組態皆設為32。
設定此值有助於避免I/O錯誤。 | 否 


| disk.QFullThreshold | 所有組態均設為8。
設定此值有助於避免I/O錯誤。 | 否 


| Emulex FC HBA逾時 | 使用預設值。 | 否 


| QLogic FC HBA逾時 | 使用預設值。 | 否 


3+| * iSCSI設定* 


| 路徑選擇原則 | 所有iSCSI路徑均設為RR（循環配置資源）。
將此值設為RR有助於在所有主動/最佳化路徑之間提供負載平衡。 | 否 


| disk.QFullSampleSize. | 所有組態皆設為32。
設定此值有助於避免I/O錯誤 | 否 


| disk.QFullThreshold | 所有組態均設為8。
設定此值有助於避免I/O錯誤。 | 否 
|===

NOTE: 1 -使用VMware vSphere ESXi 7.0.1和VMware vSphere ESXi 7.0.2時、NFS進階組態選項MaxQuesteDepth可能無法如預期運作。請參閱 link:https://kb.vmware.com/s/article/86331?lang=en_US["VMware KB 86331"] 以取得更多資訊。

建立完等量磁碟區和LUN時、也會指定特定的預設設定：ONTAP ONTAP FlexVol

|===


| *《*》工具* ONTAP | *預設設定* 


| Snapshot保留（-%快照空間） | 0% 


| 部分保留（-分數保留） | 0% 


| 存取時間更新（-atime-update） | 錯 


| 最小預先讀取（-min-readahead） | 錯 


| 排程快照 | 無 


| 儲存效率 | 已啟用 


| Volume保證 | 無（精簡配置） 


| Volume自動調整大小 | 大幅縮減 


| LUN空間保留 | 已停用 


| LUN空間配置 | 已啟用 
|===


== 效能的多重路徑設定

雖然目前未由可用的 ONTAP 工具進行設定、 NetApp 仍會建議下列組態選項：

* 在高效能環境中或使用單一LUN資料存放區測試效能時、請考慮將循環配置資源（VMW_PSP_RR）路徑選擇原則（PSP）的負載平衡設定、從預設的IOPS設定1000變更為1。請參閱VMware KB https://kb.vmware.com/s/article/2069356["2069356"^] 以取得更多資訊。
* 在vSphere 6.7 Update 1中、VMware為Round Robin PSP引進新的延遲負載平衡機制。新選項會在選取I/O最佳路徑時、考量I/O頻寬和路徑延遲在具有非等效路徑連線的環境中使用IT、例如某個路徑上的網路躍點比另一個路徑多、或是使用NetApp All SAN Array系統時、您可能會受益匪淺。請參閱 https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-B7AD0CA0-CBE2-4DB4-A22C-AD323226A257.html?hWord=N4IghgNiBcIA4Gc4AIJgC4FMB2BjAniAL5A["路徑選取外掛程式和原則"^] 以取得更多資訊。




== 其他文件

對於帶有 vSphere 7 的 FCP 和 iSCSI 、詳細資料請參閱 https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_7.html["搭配 ONTAP 使用 VMware vSphere 7.x"^]
對於帶有 vSphere 8 的 FCP 和 iSCSI 、詳細資料請參閱 https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html["搭配 ONTAP 使用 VMware vSphere 8.x"^]
如需使用 vSphere 7 的 NVMe 、請參閱 https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_7.html["如需更多詳細資料、請參閱適用於 ESXi 7.x with ONTAP 的 NVMe 主機組態"^]
如需使用 vSphere 8 的 NVMe 、請參閱 https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["如需更多詳細資料、請參閱適用於 ESXi 8.x 與 ONTAP 的 NVMe 主機組態"^]
