---
sidebar: sidebar 
permalink: epic/epic-overview.html 
keywords: epic,cache,iris 
summary: EPIC on ONTAP 概覽 
---
= ONTAP 上的 EPIC
:allow-uri-read: 


[role="lead"]
數位化轉型的關鍵在於讓資料發揮更大效益。


NOTE: 本文件取代先前發表的技術報告 _TR-3923 ：適用於 Epic 的 NetApp 最佳實務做法。

醫院需要大量資料才能開始數位轉型。治療病患、管理工作人員排程和醫療資源的程序、是收集和處理資訊的過程之一。不過、許多行動仍是手動執行、或是透過過時的系統執行。一種常態是資料量持續呈指數成長、因此越來越難以管理。

造成此問題的主要原因是醫院資料通常儲存在資料封閉環境中。手動輸入和更新花費太多時間、導致工作時間耗盡和錯誤。本文件是醫療資料的一部分、即 Epic 電子健康記錄（ EHR ）。不過、此處涵蓋的資料管理策略可以也應該套用至所有醫療資料。NetApp 擁有現代化及簡化數位基礎架構的經驗證明。我們的智慧型資料基礎架構是數位轉型的基礎。

NetApp 提供單一的資料管理解決方案、可滿足所有醫療需求、我們能夠引導醫院完成數位化轉型的過程。醫療業以結構和智慧解決方案為基礎、可充分發揮這項寶貴資訊的全部價值。此架構可協助醫療供應商更快診斷疾病、並制定個人化治療計畫、以更有效地支援緊急情況下的決策程序。您也可以建置自己的智慧型資料基礎架構、讓醫院能夠解除資料封閉環境的鎖定、促進資料互通性、並保護敏感的病患資訊。

請參考本文件、成功建構及實作 Epic EHR 。與其建置多個 Epic 封閉環境、不如建置單一 Epic 資料基礎架構、並改造醫院。



== 目的

本文件說明將 NetApp 儲存設備整合至 Epic 軟體環境的最佳實務做法。其中包含下列各節：

* 對 Epic 軟體環境及其儲存需求的技術瞭解、涵蓋各種組態。
* Epic 儲存設備考量事項、說明 Epic 解決方案的重要決策因素。
* NetApp 儲存建議、說明符合 Epic 儲存需求的 NetApp 儲存組態最佳實務做法。




== 範圍

本文件不涵蓋下列主題：

* 量化效能需求與規模調整指南、請見 https://fieldportal.netapp.com/content/192412?assetComponentId=192510["TR-3930i：《NetApp Epic規模調整準則》（NetApp Sizing Guidelines for Epic）"^]（需要 NetApp 登入）




== 對象

NetApp假設讀者具備下列背景知識：

* 深入瞭解SAN和NAS概念
* 熟悉 ONTAP 儲存系統的技術知識
* 熟悉 ONTAP 的組態與管理

