---
sidebar: sidebar 
permalink: vmware/srm/deployment_best_practices.html 
keywords: vmware, site, recovery manager, vsrm, svm, layout, segmentation, smt, best, practices, deploy, ontap, tools, vvols 
summary: 利用NetApp技術、儲存虛擬機器（SVM）的概念可在安全的多租戶環境中提供嚴格的區隔。ONTAP 
---
= 部署最佳實務做法
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== 適用於SMT的SVM配置與區隔

利用NetApp技術、儲存虛擬機器（SVM）的概念可在安全的多租戶環境中提供嚴格的區隔。ONTAP某個SVM上的SVM使用者無法從另一個SVM存取或管理資源。如此一ONTAP 來、您就能為不同的業務單位建立獨立的SVM、以便在同一個叢集上管理自己的SRM工作流程、進而提升整體儲存效率、進而充分運用此項技術。

考慮ONTAP 使用SVM範圍的帳戶和SVM管理生命體來管理功能、不僅能改善安全控管、也能提升效能。使用SVM範圍的連線時、效能自然會更高、因為SRA不需要處理整個叢集中的所有資源、包括實體資源。而是只需要瞭解抽象化至特定SVM的邏輯資產。

僅使用NAS傳輸協定（無法存取SAN）時、您甚至可以設定下列參數來使用新的NAS最佳化模式（請注意、此名稱是如此、因為SRA和VASA在應用裝置中使用相同的後端服務）：

. 登入控制面板、網址為 `\https://<IP address>:9083` 然後按一下「網路型 CLI 介面」。
. 執行命令 `vp updateconfig -key=enable.qtree.discovery -value=true`。
. 執行命令 `vp updateconfig -key=enable.optimised.sra -value=true`。
. 執行命令 `vp reloadconfig`。




== 部署ONTAP vVols的各種功能與考量

如果您打算搭配vVols使用SRM、則必須使用叢集範圍認證和叢集管理LIF來管理儲存設備。這是因為VASA供應商必須瞭解基礎實體架構、才能滿足VM儲存原則所需的原則。例如、如果您的原則需要All Flash儲存設備、則VASA Provider必須能夠查看哪些系統是Flash。

另一個部署最佳實務做法是、切勿將ONTAP 您的VMware Tools應用裝置儲存在其所管理的vVols資料存放區。這可能會導致您無法開啟VASA供應商的電源、因為您無法為應用裝置建立切換VVol、因為應用裝置離線。



== 管理ONTAP 功能的最佳實務做法

如前所述、您可以ONTAP 使用叢集或SVM範圍內的認證和管理生命體來管理等叢集。為了達到最佳效能、您可能想要在不使用 vVols 時、考慮使用 SVM 範圍的認證。不過、在這樣做的過程中、您應該瞭解某些需求、而且您確實會失去某些功能。

* 預設的vsadmin SVM帳戶沒有執行ONTAP 各項功能工作所需的存取層級。因此、您需要建立新的SVM帳戶。
* 如果您使用的是 ONTAP 9.8 或更新版本、 NetApp 建議您使用 ONTAP 系統管理員的使用者功能表、以及 ONTAP 工具應用裝置上的 JSON 檔案來建立 RBAC 最低權限使用者帳戶 `\https://<IP address>:9083/vsc/config/`。使用您的系統管理員密碼下載Json檔案。這可用於SVM或叢集範圍內的帳戶。
+
如果您使用ONTAP 的是32個以上版本的版本、則應使用中提供的RBAC使用者建立工具（RUC） https://mysupport.netapp.com/site/tools/tool-eula/rbac["NetApp 支援網站工具箱"^]。

* 由於vCenter UI外掛程式、VASA Provider和SRA伺服器都是完全整合的服務、因此您必須以在vCenter UI中新增儲存設備以供ONTAP 支援VMware工具的相同方式、將儲存設備新增至SRM的SRA介面卡。否則、SRA伺服器可能無法辨識透過SRA介面卡從SRM傳送的要求。
* 使用SVM範圍認證時、不會執行NFS路徑檢查。這是因為實體位置從SVM邏輯上抽象化。不過這並不是令人擔心的問題、因為使用ONTAP 間接路徑時、現代的功能不再受到明顯的效能下降影響。
* 可能不會報告儲存效率所節省的Aggregate空間。
* 在支援的情況下、無法更新負載共用鏡像。
* 可能無法在ONTAP 以SVM範圍認證來管理的各種系統上執行EMS記錄。

