---
sidebar: sidebar 
permalink: oracle/dp/oracle-data-availability.html 
keywords: data protection, availability, takeover, giveback, switchover, switchback 
summary: 透過 ONTAP 上的 Oracle 、將可用度最大化 
---
= ONTAP 提供 Oracle 資料可用度
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP 旨在提供最大的 Oracle 資料庫可用度。ONTAP 高可用度功能的完整說明不在本文件的範圍之內。然而、與資料保護一樣、在設計資料庫基礎架構時、對此功能的基本瞭解非常重要。



== HA 配對

高可用度的基本單位是 HA 配對。每對都包含備援連結、可支援將資料複寫到 NVRAM 。NVRAM 不是寫入快取。控制器內的 RAM 會做為寫入快取。NVRAM 的用途是暫時記錄資料、以防止發生非預期的系統故障。在這方面、它與資料庫重做記錄類似。

NVRAM 和資料庫重做記錄都可用來快速儲存資料、讓資料的變更能夠儘快提交。磁碟機（或資料檔案）上的持續資料更新直到稍後在 ONTAP 和大多數資料庫平台上稱為檢查點的程序期間才會進行。正常作業期間不會讀取 NVRAM 資料或資料庫重做記錄。

如果控制器突然故障、可能會有擱置中的變更、這些變更儲存在 NVRAM 中、但尚未寫入磁碟機。合作夥伴控制器會偵測故障、控制磁碟機、並套用儲存在 NVRAM 中的必要變更。



== 接管與恢復

接管與恢復是指在 HA 配對中的節點之間轉移儲存資源責任的程序。接管和恢復有兩個層面：

* 管理可存取磁碟機的網路連線能力
* 管理磁碟機本身


支援 CIFS 和 NFS 流量的網路介面、都是設定在主位置和容錯移轉位置。接管包括將網路介面移至與原始位置位於同一子網路的實體介面上的暫存主目錄。贈品包括將網路介面移回其原始位置。您可以視需要調整確切行為。

支援 SAN 區塊傳輸協定（例如 iSCSI 和 FC ）的網路介面不會在接管和恢復期間重新定位。而是應使用包含完整 HA 配對的路徑來佈建 LUN 、以產生主要路徑和次要路徑。


NOTE: 您也可以設定其他控制器的路徑、以支援在較大叢集中的節點之間重新放置資料、但這並不屬於 HA 程序的一部分。

接管與恢復的第二個層面是磁碟擁有權的轉移。確切的程序取決於多種因素、包括接管 / 恢復的原因、以及發出的命令列選項。目標是盡可能有效率地執行作業。雖然整體程序可能需要幾分鐘的時間、但磁碟機的實際擁有權從節點移轉至節點的時間通常只需幾秒鐘。



== 接管時間

主機 I/O 在接管和恢復作業期間會短暫暫停 I/O 、但在正確設定的環境中不應發生應用程式中斷。I/O 延遲的實際轉換程序通常是以秒為單位來測量、但主機可能需要額外的時間來識別資料路徑的變更並重新提交 I/O 作業。

中斷的性質取決於傳輸協定：

* 支援 NFS 和 CIFS 流量的網路介面會在移轉至新實體位置後、向網路發出位址解析傳輸協定（ ARP ）要求。這會導致網路交換器更新其媒體存取控制（ MAC ）位址表、並繼續處理 I/O在計畫性接管和恢復的情況下、中斷通常以秒為單位來衡量、在許多情況下都無法偵測到。有些網路可能會較慢、無法完全辨識網路路徑的變更、有些作業系統可能會在很短的時間內排入大量 I/O 、因此必須重新嘗試。這可能會延長恢復 I/O 所需的時間
* 支援 SAN 通訊協定的網路介面不會轉換到新位置。主機作業系統必須變更使用中的路徑。主機觀察到 I/O 暫停的情形取決於多種因素。從儲存系統的角度來看、無法提供 I/O 的時間只有幾秒鐘。不過、不同的主機作業系統可能需要額外的時間、才能讓 I/O 逾時、再重試。較新的作業系統更能更快辨識路徑變更、但較舊的作業系統通常需要 30 秒才能辨識變更。


下表顯示儲存系統無法將資料提供給應用程式環境的預期接管時間。在任何應用程式環境中都不應發生任何錯誤、而是在 IO 處理過程中、接管應該會顯示為短暫的暫停。

|===


|  | NFS | AFF | ASA 


| 計畫性接管 | 15 秒 | 6-10 秒 | 2-3 秒 


| 非計畫性接管 | 30 秒 | 6-10 秒 | 2-3 秒 
|===