---
sidebar: sidebar 
permalink: mysql/overview.html 
keywords: MySQL,MariaDB,TR-4722 
summary: ONTAP 上的 MySQL 
---
= ONTAP 上的 MySQL 資料庫
:allow-uri-read: 


[role="lead"]
MySQL 及其變種、包括 MariaDB 和 Percona MySQL 、是全球最受歡迎的資料庫。


NOTE: ONTAP 和 MySQL 資料庫上的本文件取代先前發佈的 _TR-4722 ： NetApp ONTAP 最佳實務做法的 MySQL 資料庫。 _

MySQL 的功能包括：

* * 降低 TCO 。 * MySQL 是一款功能強大、免費的開放原始碼資料庫管理系統、已推出多年。非常穩定。它擁有社群支援、可協助維護、除錯及新增功能。如果 Web 應用程式需要的不只是資料庫、或是需要負載平衡或分區、您可以輕鬆設定資料庫執行個體、只需花費硬體成本、而非每個執行個體都需要單一授權的商業資料庫。
* * 可靠性、效能和易用性。 * MySQL 的標誌之一是卓越的效能和擴充性、這也是許多網路型企業使用它的原因。MySQL 運用多項關鍵優勢來提供快速效能。因為競爭總是只要按一下滑鼠（或觸控螢幕）、所以快速回應客戶的詢問和活動是最重要的。服務網路型應用程式的資料庫、需要為讀取（簡單和複雜的查詢）和寫入作業提供極高的效能。
* * 資料庫開發、設計與管理。 * MySQL Workbench 提供整合式開發、設計與管理環境、讓開發人員與 DBA 更具生產力。不同的開發人員會在資料庫中尋找不同的功能、而 MySQL 則提供多種功能。它可以在筆記型電腦和桌上型電腦上充分執行。它可以輕鬆適應環境、確保不會與現有的 Web 伺服器或應用程式發生衝突。
* * 全面的交易支援。 * MySQL 是市面上最強大的交易資料庫引擎之一。這是完整資料完整性的解決方案、提供完整的原子、一致、隔離、持久的交易支援、多重版本交易支援等功能； 以及不受限制的列層鎖定。它透過伺服器強制的參考完整性、提供即時死鎖識別功能。
* * 資料安全。 * MySQL 以最安全可靠的資料庫管理系統聞名全球、適用於熱門的網路應用程式、例如 WordPress 、 Drupal 、 Joomla 、 Facebook 、 Google 、 和 Twitter 。最新版 MySQL 所隨附的交易處理資料安全性與支援、可讓任何企業受益、尤其是經常轉帳的電子商務企業。
* * 可插拔架構 * 。 * MySQL 可插拔儲存引擎架構可讓資料庫專業人員針對特定應用程式需求選擇專用的儲存引擎、而無需管理應用程式編碼需求。MySQL 伺服器架構可將應用程式設計人員和 DBA 與儲存層級的所有低層實作詳細資料隔離、提供一致且簡單的應用程式模型和 API 。雖然不同的儲存引擎有不同的功能、但應用程式卻能避免這些差異。


如果您想要鎖定特定應用程式需求（例如資料倉儲、交易處理或 HA 情況）、同時使用獨立於任何一種儲存引擎的介面和服務、 MySQL 的高效率模組化架構可帶來巨大效益。
