---
sidebar: sidebar 
permalink: oracle/dr/metrocluster/oracle-failover-on-metrocluster.html 
keywords: Metrocluster, mcc, MCC-IP 
summary: Oracle with MetroCluster 
---
= MetroCluster 的 Oracle 容錯移轉
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../../media/


[role="lead"]
使用 MetroCluster 並不一定能新增或變更營運企業應用程式和資料庫的任何最佳實務做法。

通常的最佳實務做法仍適用、如果您的需求只需要 RPO = 0 資料保護、則 MetroCluster 會滿足您的需求。然而、大多數客戶不僅使用 MetroCluster 來保護 RPO =0 資料、還能在災難期間改善 RTO 、並在站台維護活動中提供透明的容錯移轉。



== 使用預先設定的作業系統進行容錯移轉

SyncMirror 在災難恢復站點上提供資料的同步複本、但要讓資料可用、則需要作業系統和相關應用程式。基本自動化可大幅改善整體環境的容錯移轉時間。Oracle RAC 、 Veritas 叢集伺服器（ VCS ）或 VMware HA 等叢集式產品通常用於在站台之間建立叢集、在許多情況下、容錯移轉程序可以使用簡單的指令碼來驅動。

如果主節點遺失、叢集軟體（或指令碼）會設定為在替代站台上線應用程式。其中一個選項是建立預先針對構成應用程式的 NFS 或 SAN 資源所預先設定的待命伺服器。如果主站台發生故障、叢集軟體或指令碼替代方案會執行類似下列的一系列動作：

. 強制 MetroCluster 進行重新操作
. 執行 FC LUN 探索（僅限 SAN ）
. 掛載檔案系統
. 啟動應用程式


此方法的主要需求是在遠端站台上執行作業系統。它必須預先設定應用程式二進位檔、也就是說、修補等工作必須在主要站台和待命站台上執行。或者、應用程式二進位檔可鏡射至遠端站台、並在宣告災難時掛載。

實際的啟動程序很簡單。LUN 探索等命令每個 FC 連接埠只需要幾個命令。檔案系統掛載只不過是 `mount` 只需一個命令、即可在 CLI 上啟動和停止資料庫和 ASM 。如果在切換之前、磁碟區和檔案系統並未在災難恢復站台上使用、則無需設定 `dr-force- nvfail` 在磁碟區上。



== 使用虛擬化作業系統進行容錯移轉

資料庫環境的容錯移轉可延伸至包含作業系統本身。理論上、此容錯移轉可以使用開機 LUN 來完成、但通常是使用虛擬化的作業系統來完成。此程序類似於下列步驟：

. 強制 MetroCluster 進行重新操作
. 裝載託管資料庫伺服器虛擬機器的資料存放區
. 啟動虛擬機器
. 手動啟動資料庫、或將虛擬機器設定為自動啟動資料庫


例如、 ESX 叢集可以跨越站台。在發生災難時、虛擬機器可在移至災難恢復站台後上線。只要主控虛擬化資料庫伺服器的資料存放區在災難發生時並未使用、就不需要設定 `dr-force- nvfail` 在相關的磁碟區上。
