---
sidebar: sidebar 
permalink: postgres/postgres-overview.html 
keywords: PostgreSQL,database,postgres 
summary: ONTAP 上的 PostgreSQL 資料庫 
---
= ONTAP 上的 PostgreSQL 資料庫
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
PostgreSQL 隨附的變種包括 PostgreSQL 、 PostgreSQL Plus 和 EDBS PostgreSQL 進階伺服器（ EPAS ）。PostgreSQL 通常部署為多層應用程式的後端資料庫。它受一般中介軟體套件的支援（例如 PHP 、 Java 、 Python 、 Tcl/Tk 、 ODBC 、 和 JDBC) ，過去一直是開放原始碼資料庫管理系統的熱門選擇。NetApp ONTAP 是執行 PostgreSQL 資料庫的絕佳選擇、可確保其可靠性、高效能及高效率的資料管理功能。


NOTE: ONTAP 和 PostgreSQL 資料庫上的這份文件取代先前發佈的 _TR-4770 ： ONTAP 最佳實務做法的 PostgreSQL 資料庫。 _

隨著資料呈指數成長、企業的資料管理變得更加複雜。這種複雜性會增加授權、營運、支援和維護成本。若要降低整體 TCO 、請考慮使用可靠、高效能的後端儲存設備、從商業資料庫切換為開放原始碼資料庫。

ONTAP 是理想的平台、因為 ONTAP 是專為資料庫所設計。為了滿足資料庫工作負載的需求、我們特別建立了許多功能、例如隨機 IO 延遲最佳化、以提供進階服務品質（ QoS ）到基本 FlexClone 功能。

其他功能（例如不中斷升級）（包括儲存設備更換）、可確保關鍵資料庫仍可使用。您也可以透過 MetroCluster 為大型環境進行即時災難恢復、或是使用 SnapMirror 主動式同步來選擇資料庫。

最重要的是、 ONTAP 提供無與倫比的效能、並能根據您的獨特需求調整解決方案的規模。我們的高階系統可提供超過 1M IOPS 、延遲時間以微秒為測量單位、但如果您只需要 10 萬次 IOPS 、您可以使用仍執行相同儲存作業系統的較小控制器來調整儲存解決方案的大小。
