---
sidebar: sidebar 
permalink: postgres/snapshot-dp.html 
keywords: PostgreSQL,database,postgres 
summary: ONTAP 上的 PostgreSQL 資料庫 
---
= 快照
:allow-uri-read: 


[role="lead"]
PostgreSQL 的 Snapshot 型備份需要為資料檔案、 Wal 檔案和歸檔的 Wal 檔案組態快照、才能提供完整或時間點還原。

對於 PostgreSQL 資料庫而言、快照的平均備份時間介於數秒到數分鐘之間。此備份速度比快 60 至 100 倍 `pg_basebackup` 以及其他檔案系統備份方法。

NetApp 儲存設備上的快照既可一致當機、也可一致應用程式。當機一致的快照是在儲存設備上建立、而不會停止資料庫、而在資料庫處於備份模式時則會建立應用程式一致的快照。NetApp 也可確保後續快照是永久遞增備份、以節省儲存成本並提高網路效率。

由於快照速度很快、不會影響系統效能、因此您可以每天排程多個快照、而不必像其他串流備份技術一樣建立單一的每日備份。當需要還原與還原作業時、系統停機時間會減少兩項重要功能：

* NetApp SnapRestore 資料還原技術代表還原作業只需數秒即可完成。
* 積極的恢復點目標（ RPO ）意味著必須套用較少的資料庫記錄、同時也加速轉送恢復。


若要備份 PostgreSQL 、您必須使用（一致性群組） Wal 和歸檔記錄、確保資料磁碟區同時受到保護。使用 Snapshot 技術複製 Wal 檔案時、請務必執行 `pg_stop` 清除所有必須歸檔的 Wal 項目。如果您在還原期間清除 Wal 項目、則只需要停止資料庫、卸載或刪除現有的資料目錄、並在儲存設備上執行 SnapRestore 作業。還原完成後、您可以掛載系統並將其恢復至目前狀態。對於時間點恢復、您也可以還原 Wal 和歸檔記錄檔、然後 PostgreSQL 會決定最一致的點並自動恢復。

一致性群組是 ONTAP 中的一項功能、建議在有多個磁碟區掛載到單一執行個體或具有多個資料表空間的資料庫時使用。一致性群組快照可確保將所有磁碟區分組並加以保護。一致性群組可從 ONTAP 系統管理員有效管理、您甚至可以複製它來建立資料庫的執行個體複本、以供測試或開發之用。

如需一致性群組的詳細資訊、請參閱 link:../../ontap/consistency-groups/index.html["NetApp 一致性群組總覽"]。
